### ISSUE TITLE
NetTcp Negotiate framing code is wrong and leads to crash

### ISSUE THREAD

**Issue by cyanite** [CoreWCF/CoreWCF#1013]
The frame size code in DuplexPipeStream's NegotiateInputLengthDecider uses big endian to parse the frame size, which is incorrect according to the standard (https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-NNS/%5bMS-NNS%5d.pdf) and reality, and leads to a crash when large amounts of data are transferred.

DuplexPipeStream sits below the system's own NegotiateStream (when using negotiate auth), and tries to follow along with the frames (for reasons that don't make sense to me; see below). The first data frame that is read typically has a size of 17 bytes, which is interpreted as 285212672 due to the endian bug. This means that for the next 285212672 bytes (if using the same channel), everything is fine, and the framing code in DuplexPipeStream is effectively completely disabled. After this, four more, essentially random, bytes are read, often parsing to a negative number, which leads to a full crash (debug mode) or connection termination (release mode).

This is, of course, easy to fix, by doing the conversion little-endian instead. But the question is why bother? Why does DuplexPipeStream even peek at the frame size? It's used for just one thing: To truncate reads from the containing stream early, in case they read across a frame boundary. But why do this? Because,

1. NegotiateStream (the containing stream) never reads across a frame boundary, because it obviously has to parse the frame counts and strip them away from the data.
2. Even if it did, why bother trying to adapt to an upstream protocol? It can handle its own data just fine. It evidently works just fine without this feature, as it is, as noted, effectively disabled in practice.

The mechanism is clearly not important since, due to the bug, it's effectively disabled anyway, and communication works just great... for the first 280MB on a given channel.

Framing code is also used for TLS authentication streams, which I didn't analyze; it may have a necessary function there (although I am skeptical of that; it seems to do exactly the same: truncate reads to the frame size, which, presumably, is already done by the containing stream; it also seems brittle, as the containing protocol stream is complex).

I propose that the framing code for negotiate be removed entirely, as it serves no purpose. I'll help with pull requests when we've made a decision on this. Note the framing code has been wrong since it was introduced.

This is the same issue that causes the bug reported in #846

**Comment by cyanite** [comment]
@mconnew ?  I'd be happy to provide a fix. We currently need to hack around it ourselves.

**Comment by mconnew** [comment]
My work to bring NET NamedPipe support should fix this. This code was introduced because SslStream is greedy and over consumes the incoming data. This breaks connection reuse as it prevents being able to downgrade the connection. NegotiateStream it turns out isn't greedy and only reads the data for the current frame anyway so this wasn't needed for NegotiateStream, only SslStream.

**Comment by cyanite** [comment]
@mconnew right. Well, needed or not, it's clearly a logic error. Anyway, do you have some kind of time frame for this work on NamedPipe? We will need to work around this in the meantime, unless I provide a PR to fix it, if the time frame favors it :)
