### ISSUE TITLE
IncludeExceptionDetailInFaults is missing in ServiceBehaviorAttribute

### ISSUE THREAD

**Issue by 0x53A** [CoreWCF/CoreWCF#102]
https://github.com/CoreWCF/CoreWCF/blob/c3c476a5b977e9046efb9e06f39ddd0122082adc/src/CoreWCF.Primitives/src/CoreWCF/ServiceBehaviorAttribute.cs#L16

https://github.com/CoreWCF/CoreWCF/blob/c3c476a5b977e9046efb9e06f39ddd0122082adc/src/CoreWCF.Primitives/src/CoreWCF/ServiceBehaviorAttribute.cs#L153

The field is still there, but the Property to actually set it is missing

**Comment by mconnew** [comment]
How urgent is this for you? I'm in the middle of a significant reworking of the dispatcher code so if this can wait until after, that would be better for me. If this is more pressing, I can make this change in the current master branch ahead of my bigger change.

**Comment by 0x53A** [comment]
Hey, thanks!

It's not urgent at all for me, I just noticed it when trying to port some code.

If you take suggestions for your priority list, this is used by the WCF server I am trying to port:

```c#
            serviceHost.Credentials.UserNameAuthentication.UserNamePasswordValidationMode = UserNamePasswordValidationMode.Custom;
            serviceHost.Credentials.UserNameAuthentication.CustomUserNamePasswordValidator = new CustomUserNamePasswordValidator(this.wcfUser, logger);
            serviceHost.Credentials.ServiceCertificate.Certificate = this.serverCertificate;
            serviceHost.Credentials.ClientCertificate.Authentication.CertificateValidationMode = X509CertificateValidationMode.None;
```

A drop-in replacement would be awesome, but I own both client and server, so I can also modify them.

In CoreWCF, ``.Credentials`` is always null and I haven't found a way to inject it from outside.

The only hard requirement I have is that I need some form of encryption, and that I can't use Windows Authentication, so I would need either Client certificates or username/pw.

This is using net.tcp with ClientCallbacks.

**Comment by mconnew** [comment]
For now you will need to do the authentication stuff in ASP.NET Core. I haven't had time to work out how to get this information from ASP.NET Core yet to be able to present it to a custom authenticator.

**Comment by AAATechGuy** [comment]
hi @mconnew , when can we have this? 
sending specific exception detail back, is a backward compatible feature, we do want to retain, while porting APIs from .net framework to .net core.

**Comment by mconnew** [comment]
This is in PR and will make it to GA
