### ISSUE TITLE
Custom certificate validation for NetTcpBinding

### ISSUE THREAD

**Issue by ibrahimabtula** [CoreWCF/CoreWCF#1032]
Is it possible to add custom certificate validation.

I am using NetTcpBinding.

I migrated old .NET Framework Client and Server to .NET 7 with CoreWCF and I am using the following code on client side and it does work when I call the old NET Framework server from the new  NET 7 client but it doesn't work when I call the new NET 7 server.
Old server had custom certificate validation added by deriving from `ServerHost` class, but in .NET 7 `ServerHost` is no longer available.

I tried to follow the solution from this issue https://github.com/CoreWCF/CoreWCF/issues/918 but with no success.
If it's possible to add custom certificate validation I would really appreciate some example client and server code.
How do I have to pass the certificate on client side and how I have to validate the certificate on server side.

```C#
// Client
var callback = serviceProvider.GetRequiredService<IServiceContractCallback>();
InstanceContext instanceContext = new InstanceContext(callback);

var binding = new NetTcpBinding(SecurityMode.Transport);
binding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Certificate;

var endpoint = new EndpointAddress(new Uri($"net.tcp://localhost:{portTcp}/Server"), identity);
var factory = new DuplexChannelFactory<IServerContract>(instanceContext, binding, endpoint);

factory.Credentials.ClientCertificate.Certificate = clientCertificate;
```

**Comment by mconnew** [comment]
I see you closed this, did you find the solution?

**Comment by ibrahimabtula** [comment]
Hi Matt, sorry for the late reply. Yes I indeed found a solution.
This is my server code that worked.
ChangeHostBehavior was the main part I was missing.

Maybe I was unlucky but I couldn't find any example or docs for how to use custom certificate.
Adding an examples folder or separate repo with examples would be nice addition I believe so.
As alternative could be adding a test case with custom certificate, I can do this during the weekend as well, as I was using the tests as examples while migrating to .NET 7 and they helped me couple of times.

```C#
// Change ServiceHostBase to accept custom certificate 
public static void ChangeHostBehavior(ServiceHostBase host)
{
	var serverCertificate = new X509Certificate2(pathToCertificate + "/Certificate.pfx", "wcf");
	var srvCredentials = new CoreWCF.Description.ServiceCredentials();
	srvCredentials.ClientCertificate.Authentication.CertificateValidationMode = CoreWCF.Security.X509CertificateValidationMode.Custom;
	srvCredentials.ClientCertificate.Authentication.CustomCertificateValidator = new DabisX509CertificateValidator(serverCertificate);
	srvCredentials.ServiceCertificate.Certificate = serverCertificate;
	host.Description.Behaviors.Add(srvCredentials);
}

// And when building use ChangeHostBehavior method
app.UseServiceModel(serviceBuilder => 
{
	Action<ServiceHostBase> serviceHost = host => ChangeHostBehavior(host);
	serviceBuilder.ConfigureServiceHostBase<ServiceImpl>(serviceHost);
	
	var binding = new NetTcpBinding(SecurityMode.Transport);
	binding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Certificate;
	serviceBuilder.AddService<ServiceImpl>();
	serviceBuilder.AddServiceEndpoint<ServiceImpl, IService>(binding, "Web");
				
})
```
