### ISSUE TITLE
Various failures in CoreWCF

### ISSUE THREAD

**Issue by simonegli8** [CoreWCF/CoreWCF#1044]
Hello,

I'm porting some Web Services to CoreWCF, and some Exceptions are thrown when calling the services. I've created a Github repository with some unit tests that reproduce the errors, it's at [https://github.com/simonegli8/CoreWCF.Tests](https://github.com/simonegli8/CoreWCF.Tests). I made a video describing the failures.

**Comment by mconnew** [comment]
The video is 35 minutes long, and your application is quite large. That's too much to be able to investigate. The ideal thing would be a simple standalone app which reproduces the problem, but I will also work with simple written instructions on how to hit the failure using the repo you've provided, along with the exception call stack you are seeing. If you have multiple failures which look unrelated, please open an issue for each one.

I did have a quick skip through the video and saw you have some code to basically support asmx style attributes for having SOAP headers applied to parameters. Just an FYI, the WCF way to do that is with [Message Contracts](https://learn.microsoft.com/en-us/dotnet/framework/wcf/feature-details/using-message-contracts). If you wanted to simplify your code, it would be a good alternative.

**Comment by simonegli8** [comment]
And don't forget to pull the CoreWCF.Tests repo, I've made some small changes
