### ISSUE TITLE
CoreWCF and Session

### ISSUE THREAD

**Issue by tskong** [CoreWCF/CoreWCF#1045]
Hi CoreWCF community,

I am converting a .net framewortk 4.7.2 MVC application, which self hosts some WCF webservices.

It's all going well, I have got the WCF services up and running and they are responding to client requests, but I've noticed that the following code isn't working

```
                var httpContext = httpContextAccessor.HttpContext == null ? OperationContext.Current.IncomingMessageProperties["Microsoft.AspNetCore.Http.HttpContext"] as HttpContext :
                    httpContextAccessor.HttpContext;

                httpContext.Session.SetString("id", JsonConvert.SerializeObject(principal));
```

I have a httpContext, but the session is NULL.  I'm using 

```
   services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromMinutes(Double.Parse(Configuration["appSettings:SessionTimeoutMinutes"]));
                options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
                options.Cookie.Name = Configuration["appSettings:SessionCookieName"];
            });

   app.UseSession();
```

and when I use the web front end, the session is available, it's just when I call the webservices that there is no session.

Thanks,

Tat

**Comment by mconnew** [comment]
Presuming the client is a WCF client, did you enable cookies? As SOAP has its own session mechanism and cookies aren't generally needed, it's off by default. When the service returns a cookie to the client, it doesn't get sent on the next request. If you are using BasicHttpBinding, then you can set BasicHttpBinding.AllowCookies to true. The other HTTP bindings also have an equivalent property. One thing to be aware of is that the scope of the underlying cookie collection is the ChannelFactory (as it uses a shared HttpClientHandler for all channels). If you create two clients from a single ChannelFactory, they will share cookies between them.

**Comment by tskong** [comment]
Thanks for the help.

I do have a WCF client, and I just tried set allowcookies = true, but it's the same.  It would also mean a change to all the clients that are connecting to our WCF services so I don't think that would be practical.

**Comment by mconnew** [comment]
If you don't turn on use of cookies on the client, that means any cookies sent by the service to the client will never get returned in subsequent requests. There is nothing that can be done on the service side to change that.  

I took a look at the implementation of UseSession and there's nothing in there that I can see that CoreWCF would interfere with. Are you calling `app.UseSession()` before you're calling `app.UseServiceModel(...);`? If you don't call UseSession first, then the middleware won't get called as WCF is a terminating middleware (doesn't call any subsequent middleware) if it's a request for WCF.
