### ISSUE TITLE
Make DispatchOperation Invoker public

### ISSUE THREAD

**Issue by aramacciotti** [CoreWCF/CoreWCF#106]
I need to "customize" the Invoker process for a DispatcherOperation but it's internal in CoreWCF implementation.
I'm asking to make it "public"

**Comment by mconnew** [comment]
I want to make sure I understand your request. Are you wanting to have [DispatchOperation.Invoker](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.dispatcher.dispatchoperation.invoker?view=netframework-4.8) made public so you can modify the IOperationInvoker behavior?

**Comment by aramacciotti** [comment]
Yes. Thanks and sorry if I was not clear

Scarica Outlook per Android<https://aka.ms/ghei36>
________________________________

**Comment by mconnew** [comment]
I've created a PR with the changes. There are a few differences with IOperationInvoker. In my quest to rid CoreWCF of APM, there are two differences in the api. First, IsSynchronous property is gone. Second, Invoke, BeingInvoke and EndInvoke have been replaced with a single InvokeAsync. As you can't return an out parameter from an async method, the outputs array is being returned using a tuple. I suspect you won't need to worry about this as most people use do soemthing before and/or after calling the original invoker. In which case you can implement your method like this:
```c#
public async ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
{
    // Do something before
    var result = await _innerInvoker.InvokeAsync(instance, inputs);
    // Do something after
    return result;
}
```
Let me know if you have any problems with this.

**Comment by aramacciotti** [comment]
I have a previously developed .NET Framework WCF service in which Invoke method was replaced (as it was “public”) by a custom implementation.
In order to have the same result, do you mean that I have to set InvokeAsync property (if existing, but it seems to me not)?

Da: Matt Connew <notifications@github.com>
Inviato: mercoledì 18 marzo 2020 18:54
A: CoreWCF/CoreWCF <CoreWCF@noreply.github.com>
Cc: aramacciotti <aramacciotti@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [CoreWCF/CoreWCF] Make DispatchOperation Invoker public (#106)


I've created a PR with the changes. There are a few differences with IOperationInvoker. In my quest to rid CoreWCF of APM, there are two differences in the api. First, IsSynchronous property is gone. Second, Invoke, BeingInvoke and EndInvoke have been replaced with a single InvokeAsync. As you can't return an out parameter from an async method, the outputs array is being returned using a tuple. I suspect you won't need to worry about this as most people use do soemthing before and/or after calling the original invoker. In which case you can implement your method like this:

public async ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)

{

    // Do something before

    var result = await _innerInvoker.InvokeAsync(instance, inputs);

    // Do something after

    return result;

}

Let me know if you have any problems with this.

**Comment by mconnew** [comment]
Your existing implementation will derive from System.ServiceModel.Dispatcher.IOperationInvoker. That had two sets of Invoke methods, Invoke for a synchronous implementation, and the paired InvokeBegin/InvokeEnd for APM asynchronous implementation. It also had an IsSynchronous property to direct WCF whether to call Invoke of the InvokeBegin/InvokeEnd pair. To move to CoreWCF, you will need to implement CoreWCF.Dispatcher.IOperationInvoker instead. This has removed the IsSynchronous property, and replaced the two different sets of api's with the single InvokeAsync api. You will need to do a refactor/partial rewrite but it should be minimal changes.  
So the interface you need to implement has changed from:
```c#
    public interface IOperationInvoker
    {
        bool IsSynchronous { get; }
        object[] AllocateInputs();
        object Invoke(object instance, object[] inputs, out object[] outputs);
        IAsyncResult InvokeBegin(object instance, object[] inputs, AsyncCallback callback, object state);
        object InvokeEnd(object instance, out object[] outputs, IAsyncResult result);
    }
```
To this:
```c#
    public interface IOperationInvoker
    {
        object[] AllocateInputs();
        ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs);
    }
```
It simplifies things a lot. It hasn't been merged yet so you won't see the new api until it it.

**Comment by aramacciotti** [comment]
Which is the plan about merging such changes and make it available so I can arrange code accordingly?

**Comment by mconnew** [comment]
This has now been merged. New packages should be available within 30 minutes.

**Comment by aramacciotti** [comment]
As such I still see the alpha.68 version: is this the new package?

**Comment by mconnew** [comment]
It should be alpha.71
