### ISSUE TITLE
`UsePathBase` is ignored by CoreWCF

### ISSUE THREAD

**Issue by mgaffigan** [CoreWCF/CoreWCF#1063]
When operating ASP.Net API's behind a reverse proxy, calling `UsePathBase` is sufficient to allow the service to be prefixed by the proxy. 

With CoreWCF, the path to `AddServiceEndpoint` must be modified to include the part passed to `UsePathBase`.

Example:

    app.UsePathBase("/service1/");
    app.UseRouting();
    app.UseServiceModel(sb => 
    {
        sb.AddService(typeof(TService))
            .AddServiceEndpoint(typeof(TService), typeof(TEndpoint), new BasicHttpBinding(), new Uri("/endpoint", UriKind.Relative), null);
        // Uncomment for prefix to succeed
        //sb.AddService(typeof(TService))
        //    .AddServiceEndpoint(typeof(TService), typeof(TEndpoint), new BasicHttpBinding(), new Uri("/service1/endpoint", UriKind.Relative), null);
    });

**Comment by g7ed6e** [comment]
hi @mgaffigan a workaround is described here #707

**Comment by mgaffigan** [comment]
@g7ed6e, I agree that this seems to be a duplicate.  I'll close.
