### ISSUE TITLE
Accessing request.headers

### ISSUE THREAD

**Issue by tskong** [CoreWCF/CoreWCF#1066]
Hi,

With system.servicemodel, I could access the header of a request using 

System.ServiceModel.Web.WebOperationContext.Current;

And then using the IncomingRequest.Headers to pick up any headers in there.

Is there something equivalent for coreWCF?

Thanks,

**Comment by g7ed6e** [comment]
Hi @tskong if you are trying to access the http headers from within an operation contract implementation you should be able to inject HttpContext directly by using the source generator feature.
```c#
public partial class EchoService : IEchoService
{
    public string Echo(string message, [Injected]HttpContext httpContext)
    {
        var headers = httpContext.Request.Headers;
        // do somethong with http headers
        return message;
    }
}
```
The DI feature is described here https://corewcf.github.io/blog/2021/12/15/corewcf-0_4_0_released

**Comment by tskong** [comment]
Fantastic, I'll give that a go.
