### ISSUE TITLE
Working with SamlSecurityToken and SamlAuthenticationStatement

### ISSUE THREAD

**Issue by venknar** [CoreWCF/CoreWCF#1072]
Hi

We have this piece of code in .NET Framework.
```

private SymmetricSecurityKey FindToken(SecurityToken securityToken)
{
            SamlSecurityToken samlSecurityToken = securityToken as SamlSecurityToken;
            if (samlSecurityToken != null)
            {
                foreach (SamlStatement statement in samlSecurityToken.Assertion.Statements)
                {
                    SamlAuthenticationStatement authenticationStatement = statement as SamlAuthenticationStatement;
                    if (authenticationStatement != null)
                    {
                        SymmetricSecurityKey symmetricSecurityKey = authenticationStatement.SamlSubject.Crypto as SymmetricSecurityKey;
                        if (symmetricSecurityKey != null)
                        {
                            return symmetricSecurityKey;
                        }
                    }
                }
          }
}

```
While trying to convert the above code to WCF.Net Core, tried including the 

using MSIdentitySAML = Microsoft.IdentityModel.Tokens.Saml;

But then the conversion from the SecurityToken to SamlSecurityToken is failing with this compilation error  

  MSIdentitySAML.SamlSecurityToken samlSecurityToken = (MSIdentitySAML.SamlSecurityToken)securityToken;
 if (samlSecurityToken != null)
 {
 }
3>d:\substrate\src\sources\dev\common\src\net\server\wstrust\tokenvalidator.cs(733,66) : error CS0030: Cannot convert type 'CoreWCF.IdentityModel.Tokens.SecurityToken' to 'Microsoft.IdentityModel.Tokens.Saml.SamlSecurityToken'

The conversion fails due to the above error. 
To get the SecurityToken compiled including CoreWCF.IdentityModel.Tokens. 

How to handle the above with WCF.NET Core ? Please share any guidance.

**Comment by birojnayak** [comment]
@venknar you can't convert the IdentityToken to MSIdentitySAML.SamlSecurityToken directly (by design we decided to do that). But I have exposed an API to get Assertion part of #1074 . Once that's merged you can directly get Assertion.Statements to inspect AuthenticationStatements. Hope this helps.

**Comment by venknar** [comment]
Thank you. Any ETA when this would be available for me to try out. Thanks

**Comment by birojnayak** [comment]
@venknar we have added an explicit cast to get you the Microsoft.IdentityModel.Tokens.Saml.SamlSecurityToken via the https://github.com/CoreWCF/CoreWCF/pull/1074 . You can get the code from mainline and check things are working or you can wait for the release. Closing this issue as fix is applied. Feel free to re-open if this doesn't resolve.
