### ISSUE TITLE
Support for SamlNameIdentifierClaimResource

### ISSUE THREAD

**Issue by venknar** [CoreWCF/CoreWCF#1075]
Hi

We used to have support for SamlNameIdentifierClaimResource in the .NET Framework. I see that it is internal class in WCF.NET Core.

```
      private static string FindClaim(AuthorizationContext authorizationContext)
        {
            foreach (ClaimSet claimSet in authorizationContext.ClaimSets)
            {
                foreach (Claim claim in claimSet.FindClaims(ClaimTypes.NameIdentifier, Rights.Identity))
                {
                    SamlNameIdentifierClaimResource resource = claim.Resource as SamlNameIdentifierClaimResource;
                    if (resource != null)
                    {
                        return resource.Name;
                    }
                }
            }

            return null;
        }
```

Above is a piece of code that we used to depend on. How to do this in WCF.NET Core. 

Please provide inputs.

**Comment by venknar** [comment]
@birojnayak Can you please help with the above query. Will this SamlNameIdentifierClaimResource also be made public ?

**Comment by birojnayak** [comment]
yes if it's public in [reference code](https://referencesource.microsoft.com/#System.IdentityModel/System/IdentityModel/Tokens/SamlNameIdentifierClaimResource.cs,a42bc760bc87fb85,references) we should make it public... I will add to previous PR... let me know if there are other findings w.r.t SAML... thank you for pointing them.

**Comment by venknar** [comment]
@birojnayak Thank you for the help. Can you please help with making these classes as well public - RsaSecurityTokenAuthenticator which is internal only currently.

**Comment by venknar** [comment]
@birojnayak Can you please share me the build version where the SAML related changes are available for consumption ? Thank you

**Comment by birojnayak** [comment]
https://github.com/CoreWCF/CoreWCF/issues/1072 => has details... marking duplicate and closing. @venknar if it's not working, feel free to re-open it.
