### ISSUE TITLE
Background service hosting CoreWCF

### ISSUE THREAD

**Issue by tskong** [CoreWCF/CoreWCF#1091]
Hi,

I'm looking at hosting CoreWCF in a background service.  It's a console app so I don't have access to the usual WebApplication I have been using with CoreWCF so far.

Before I embark on an investigation, is this technically possible?

Thanks

**Comment by tskong** [comment]
I've worked it out, here it is for reference:

This takes advantage of the GenericHost in asp.net you, set up your background service as normal, and then add the web host to it.

I had to manually add this line to the .csproj, but it works. I know have a background service as well as a WCF endpoint

```
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />		
</ItemGroup>
```

Source code:

```
     public static void Main(string[] args)
        {
            IHost host = Host.CreateDefaultBuilder(args)
                .UseWindowsService()
                .UseSystemd()
                .ConfigureServices(services =>
                {
                    services.AddHostedService<Worker>();
                })
                .ConfigureWebHostDefaults(builder=>
                {
                    builder.ConfigureServices(services =>
                    {
                        services.AddServiceModelServices()
                            .AddServiceModelMetadata();
                    })
                    .Configure(app => 
                    {
                            app.UseServiceModel(b =>
                            {
                                b.AddService<MathsService>()
                                .AddServiceEndpoint<MathsService, IMathsService>(new BasicHttpBinding(), "/MathService/http")
                                .AddServiceEndpoint<MathsService, IMathsService>(new BasicHttpBinding(BasicHttpSecurityMode.Transport), "/MathService/https");

                                var serviceMetadataBehavior = app.ApplicationServices.GetRequiredService<CoreWCF.Description.ServiceMetadataBehavior>();
                                serviceMetadataBehavior.HttpGetEnabled = true;
                            });
                    })
                ;
                })
                .Build();

            host.Run();
        }
```

**Comment by NGOHIL01** [comment]
Hello,
trying to host CoreWcf as selfhosted windows service.
for your approach would you please provide more details?

**Comment by tskong** [comment]
What details would you like? The example above has everything I thought of interest?

**Comment by NGOHIL01** [comment]
AddServiceModelServices  and UseServiceModel is not resolving for me.   here is my project info

<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WorkerService1-8f6007a8-3cd6-4f45-94e4-27bd6ffc03c3</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CoreWCF.Http" Version="1.5.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
  </ItemGroup>
</Project>


using WorkerService1;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using CoreWCF;

    IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .ConfigureWebHostDefaults(builder =>
    {
        builder.ConfigureServices(services =>
        {
            services.**AddServiceModelServices**()
                .AddServiceModelMetadata();
        })
        .Configure(app =>
        {
            app.**UseServiceModel**(b =>
            {
                b.AddService<MathsService>()
                            .AddServiceEndpoint<MyWcfService, IMyWcfService>(new BasicHttpBinding(), "/MyWcfService/http")
                            .AddServiceEndpoint<MyWcfService, IMyWcfService>(new BasicHttpBinding(BasicHttpSecurityMode.Transport), "/MyWcfService/https");

                var serviceMetadataBehavior = app.ApplicationServices.GetRequiredService<CoreWCF.Description.ServiceMetadataBehavior>();
                serviceMetadataBehavior.HttpGetEnabled = true;
            });
        })
    ;
    })
    .Build();

await host.RunAsync();

**Comment by tskong** [comment]
AddServiceModelServices and UseSeviceModel are from CoreWCF.Primitives package, and is in the CoreWCF.Configuration namespace.
 
You need 

using CoreWCF.Configuration;

At the top of your file, as well as adding the nuget package

**Comment by NGOHIL01** [comment]
tried to host on service controller. which create under services but it fails to start.

command: 
**sc create** mycorewcfservcie binPath=c:\ggfdghfgh
