### ISSUE TITLE
CoreWCF needs an official logo

### ISSUE THREAD

**Issue by mconnew** [CoreWCF/CoreWCF#1092]
We'd like to invite submissions for a logo for CoreWCF. It will be used as the logo for the nuget packages, as well as being featured on web pages such as the blog website, or as a twitter account profile picture. Each unique submission should be in its own comment so that people can vote on their favorite.  

The CoreWCF maintainers will pick one which has a large number of votes, but reserve the right to not choose the highest voted (we don't want a [Mister Splashy Pants](https://en.wikipedia.org/wiki/Mister_Splashy_Pants) situation),  

The creator of the winning image will be expected to submit a pull request with the image to ensure the copyright is transferred to the .NET Foundation the same way any submitted code is. We will credit the author in a way that's mutually agreeable to them and the CoreWCF maintainers.  

The ideal format to commit to the repo would be a rasterized format such as SVG, although a sufficiently high resolution bitmap such as PNG is likely to be accepted as long as it can scale well.  

Avoid any inspiration from existing company logos. For example, including a window because WCF had it's origin in Microsoft Windows isn't acceptable.  

### Inspiration for the design
These are just suggestions, nothing is required to be a part of the logo.  
The original project codename for WCF in .NET Framework was Indigo. A lighter shade of Indigo is Capri. I used the [Bing AI image creator](https://bing.com/create) to generate a logo using these colors to see what kinds of things it could come up with and am submitting them as possibilities to consider. I used combinations of the following words and phrases as input to Bing.
* The colors Indigo and Capri
* Geometric shapes
* Idea of flow
* Connectedness
* Logo

I've submitted some of my favorite generated logos. Feel free to go for a completely different theme, the logo doesn't need to be an abstract shape. For example, an original animal, or anthropomorphic shape (e.g. the .dotnet bot) would be reasonable submissions.

**Comment by mconnew** [comment]
![image](https://github.com/CoreWCF/CoreWCF/assets/8648390/1a85e9b6-6ae5-4d6e-af63-c45bf916fde8)

**Comment by mconnew** [comment]
![image](https://github.com/CoreWCF/CoreWCF/assets/8648390/0ee9d696-2637-4554-a0f7-2e6353889a8a)

**Comment by mconnew** [comment]
![image](https://github.com/CoreWCF/CoreWCF/assets/8648390/cf26649f-e5b0-4c84-a754-a256b85d0328)

**Comment by anthonywww** [comment]
![image](https://github.com/CoreWCF/CoreWCF/assets/31651690/65ab3ca1-212b-45fa-95a3-d8fb6bd3b365)

Created with *AI* using the following phases as input to Bong Botnet Search:
- Micro$oft Winblows Botnet 10 / 11
- Azure Botnet (Cloud Edition)
- C-SHART
- .NOT

**Comment by g7ed6e** [comment]
![_c6f26d5c-58ed-4795-ad87-31ede575f047](https://github.com/CoreWCF/CoreWCF/assets/681739/31a53202-ad2c-449b-ba79-2ce372ff5b9b)

**Comment by g7ed6e** [comment]
![_9e065737-5e7d-4506-8199-c03d1aca069b](https://github.com/CoreWCF/CoreWCF/assets/681739/feab3fc7-c761-42c2-9ada-74e1d409ac7a)

**Comment by g7ed6e** [comment]
![_7977ec0f-802b-4ecf-9445-049ca1118727](https://github.com/CoreWCF/CoreWCF/assets/681739/2c23f035-d246-4e43-b0c2-9131443a20be)

**Comment by g7ed6e** [comment]
![_0cb38d1d-a846-4515-b6f8-6382688fd438](https://github.com/CoreWCF/CoreWCF/assets/681739/a7526930-f701-4d6b-8efe-72231eb5a014)

**Comment by g7ed6e** [comment]
![_3e518d62-9f67-4bec-bc35-e1cee85f2149](https://github.com/CoreWCF/CoreWCF/assets/681739/0c8051f1-d5a8-48da-b6ae-7e0f52073b19)

**Comment by mconnew** [comment]
The following 3 logos were created with the prompt:
> a simple software logo with an indigo flower and abstract representation of data flow, suitable for low resolution and without small details
![_35ea3dfb-8575-46d8-aaaf-3f40492fec3d](https://github.com/CoreWCF/CoreWCF/assets/8648390/2b5a091d-1076-4909-8c85-835fa7f126b9)

**Comment by mconnew** [comment]
![_b606d9d2-49b0-4737-a891-440e72801e59](https://github.com/CoreWCF/CoreWCF/assets/8648390/bf56cd5b-63e2-4eb8-89d7-2b0d9b327ebf)

**Comment by mconnew** [comment]
![_66367bc2-af45-44ea-a111-0172498cd543](https://github.com/CoreWCF/CoreWCF/assets/8648390/e29a30c1-6600-454b-b0ff-8d623e890cfa)

**Comment by ChrisMcKee** [comment]
Made in Photoshop so colours etc are totally adjustable; considered that it would be mostly avatar usage / package icon.

![Hex](https://github.com/user-attachments/assets/b547bf90-59b8-463a-be76-f72761e1d9b0)

**Comment by ChrisMcKee** [comment]
`HexC`
![HexC](https://github.com/user-attachments/assets/5ab9a566-5274-43b9-bd84-149a5b2a5adc)

**Comment by ChrisMcKee** [comment]
`round`
![Round](https://github.com/user-attachments/assets/77dbc6ac-5c80-46bf-a6e8-64794ec6b884)

**Comment by ChrisMcKee** [comment]
And for the hell of it one using the capri RAG colour as a base 
`hex-capri`
![hex capri](https://github.com/user-attachments/assets/c247a9ff-c38d-44e8-80ea-359928944d47)

**Comment by ChrisMcKee** [comment]
Brighter scheme
![abstract-gradient](https://github.com/user-attachments/assets/ac24d10d-00f5-45fd-b5f5-1149eefe29c1)

**Comment by mconnew** [comment]
@ChrisMcKee I like the last one a lot, but the order of WCF and CORE are backwards as it reads as WCF Core when it's Core WCF.

**Comment by ChrisMcKee** [comment]
> @ChrisMcKee I like the last one a lot, but the order of WCF and CORE are backwards as it reads as WCF Core when it's Core WCF.

I'll amend that 😅

**Comment by ChrisMcKee** [comment]
@mconnew 
![image](https://github.com/user-attachments/assets/590bf81d-caf6-4abc-a463-d1bff88e120f)
Scaled the WCF into the space and compressed the line spacing (ignore the blue lines its just the rulers)

**Comment by ChrisMcKee** [comment]
`horizontal`
![hex_abstract_gradient_horizontal](https://github.com/user-attachments/assets/0ed8c140-b0ba-4d0f-a1a6-57f1638de0ea)
`standalone`
![hex_abstract_gradient_standalone](https://github.com/user-attachments/assets/4d0deaf9-5b98-4f18-9dbf-d2d425387f9f)
`logo`
![hex_abstract_gradient](https://github.com/user-attachments/assets/d7efed3a-d34d-4e77-884e-5e7144cba62f)

**Comment by mconnew** [comment]
@ChrisMcKee, I had a quick chat with @g7ed6e my fellow maintainer on the project and we both love the logo, but the text needs a little work. The projects formal name is a single word, "CoreWCF", so it shouldn't be split across 2 lines. With the text being all uppercase, it makes it harder to read the word if you put it together, ie "COREWCF". Could you try and find a text variation which keeps the name branding accurate? I'm not super picky on fonts, I do like the sans serif style you've gone with, and you seem to have a great eye for design so I don't think it's going to be a lot of back and forth on this. Once the name is right, a PR would be great. I was thinking of placing it under Documentation/Branding but if you have a better idea, e.g. some convention that's normally used, feel free to suggest that.  

Thanks again for coming up with a great logo for us.

**Comment by ChrisMcKee** [comment]
@mconnew Few different treatments.

`basic`
![hex_abstract_gradient_txt1](https://github.com/user-attachments/assets/b57a923d-dc88-4985-99ac-17b260be0a04)
`deemphasised`
![hex_abstract_gradient_txt2](https://github.com/user-attachments/assets/9b47f4fc-7969-4ec4-87bc-00615251c010)
`nested`
![hex_abstract_gradient_txt2](https://github.com/user-attachments/assets/fc47f0e7-2f6d-4863-b73c-648da5717fd0)

**Comment by mconnew** [comment]
I prefer the deemphasised version as it clearly shows Core and WCF as separate components, and is still easy to read. I like the concept of nested, but in practice it's just slightly too much cognitive load to quickly read it.  

Please create a PR with the deemphasised version. What set of images do you think are appropriate to submit? I think there's value to having the text and image each as separate images as well as combined, with it to the right as well as underneath. Once we have the images committed, I'll adopt them where I can immediately such as the the GitHub organization account and/or the individual repos, and I think the nuget account. Also the blog website.

**Comment by g7ed6e** [comment]
Thanks for the work @ChrisMcKee !
