### ISSUE TITLE
ServiceAuthenticationBehavior throws NullReferenceException in GetAuthorizationService if new:ed up to be applied to one specific service only

### ISSUE THREAD

**Issue by ksjoberg** [CoreWCF/CoreWCF#1114]
I'm trying to apply a ServiceAuthenticationBehavior on a specific `ServiceHostBase` only. I do this by:

```c#
serviceBuilder.ConfigureAllServiceHostBase(serviceHost =>
{
    if (serviceHost.Description.ServiceType == typeof(MyCustomService))
    {
        serviceHost.Description.Behaviors.Remove<ServiceAuthorizationBehavior>(); // The shared Singleton instance
        serviceHost.Description.Behaviors.Add(new ServiceAuthorizationBehavior
        {
            ExternalAuthorizationPolicies = new ReadOnlyCollection<IAuthorizationPolicy>(new List<IAuthorizationPolicy> { new MyCustomAuthorizationPolicy() }),
            PrincipalPermissionMode = PrincipalPermissionMode.Custom,
        });
    }
}
```

However, when I do so, a NullReferenceException is thrown:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CoreWCF.Primitives
  StackTrace:
   at CoreWCF.Description.ServiceAuthorizationBehavior.CoreWCF.Description.IServiceBehavior.ApplyDispatchBehavior(ServiceDescription description, ServiceHostBase serviceHostBase) in /_/src/CoreWCF.Primitives/src/CoreWCF/Description/ServiceAuthorizationBehavior.cs:line 216
```

This code is called from `DispatchBuilder.InitializeServiceHost`.

It appears to be because the internal setter property `ServiceScopeFactory` is never assigned a value, so it remains `null`.

Only workaround I've found is to set it through reflection, i.e:
```c#
typeof(ServiceAuthorizationBehavior)
    .GetProperty("ServiceScopeFactory", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
    .SetValue(tempServiceAuthorizationBehavior, app.ApplicationServices.GetService<IServiceScopeFactory>());
```

But this can't be right. Is there a better way of doing this or have I stumbled upon a bug or unsupported scenario?

**Comment by mconnew** [comment]
It's kind of a bug. You can work around it though by not removing the existing ServiceAuthorizationBehavior and instead retrieve it and setting those properties on the existing one.

**Comment by mconnew** [comment]
I just realized that won't work. We added the type to DI as a singleton, which means every service will use the same one, which is what you are trying to work around. A workaround would be to find the ServiceDescriptor in the IServiceCollection and replace it with one which is a Transient, keeping the same factory delegate. Then you can just modify it.

**Comment by ksjoberg** [comment]
Thanks for a new approach to workaround the issue. I'll look further into it. Meanwhile, you think there's a change for this problem that will be done in CoreWCF?

**Comment by g7ed6e** [comment]
@ksjoberg @allderidge please have a look to the test of the linked PR to get the expected behavior.
