### ISSUE TITLE
Calling OperationContext.Current before the host started causes later exceptions and bugs

### ISSUE THREAD

**Issue by DxCK** [CoreWCF/CoreWCF#1126]
### Background
Each time the application in question write to log, it accesses `OperationContext.Current` to try and gather some details when available.
This fact causes the `OperationContext.Current` to be accessed as early as before the service host even created.
As I'm migrating the said application into CoreWCF, I have encountered very weird bugs and exceptions, which I traced back to the above early `OperationContext.Current` access.

### Outcomes
The most disturbing outcome is that `OperationContext.Current` may be replaced in mid-operation if there is more than 1 client that invokes operations at a given time. Meaning:

```
        // this is an [OperationContract] implementation
        public void DoSomething()
        {
            if (OperationContext.Current != OperationContext.Current)
            {
                // sometimes it gets here...
            }
        }
```

Some other outcomes I have observed are:
- ObjectDisposedException when accessing OperationContext.Current.IncomingMessageHeaders.
- NullReferenceException sent as a fault back to the client (Visible only when `IncludeExceptionDetailInFaults = true`)
- Some other exceptions thrown internally within CoreWCF infra.

### How to Reproduce
To reproduce, just add the following line before the aspnetcore host creation:
`var context = CoreWCF.OperationContext.Current;`
And the executable project must target .NET Framework.

I wrote a simple project to reproduce it:
[CoreWcfOperationContextBugRepro.zip](https://github.com/CoreWCF/CoreWCF/files/11892471/CoreWcfOperationContextBugRepro.zip)

I have verified the bug to exist in versions: 1.3.1, 1.3.2, and 1.4.0-preview1 .
It's possible more versions are affected, but I didn't test others.

### Probable Cause
There is a `class Holder` which actually points to the `OperationContext`, and there is an `AsyncLocal<Holder> s_currentContext` which is carrying a different reference of `Holder` for each asynchronous control flow.
Accessing `OperationContext.Current` for the first time causes the instantiation of `Holder` class for the current asynchronous control flow, and it sets it into `AsyncLocal`. Once a `Holder` reference is set into `AsyncLocal`, it will be reused forever to point to a given `OperationContext` including future ones that relevant to the current asynchronous control flow.
`AsyncLocal` data is actually gets copied each time a new `Task` created. Meaning if one sets a value into `AsyncLocal` on the Main Thread before any other `Task` exists, then the value will be copied to all the `Task`s in the application. In our case, this value is a reference to a `Holder` instance, and thus all Tasks will carry the exact same `Holder` reference, and as a consequence will override each-other `OperationContext` reference, which is the probable cause of all the above observed outcomes.

### Solution Proposal
Changing `AsyncLocal<Holder>` to `AsyncLocal<OperationContext>`, and adjust the setters and getters correspondingly, eliminated the said bug and exceptions in my tests.

**Comment by mconnew** [comment]
Would you be able to submit a unit test based on your repro and submit a fix in a PR? I will note this will introduce a tiny performance regression as the Holder is there to make the lookup cheaper. This was more of an issue in .NET Framework as that used thread local storage which is a lot more expensive. Correctness is more important than performance so this minor performance regression is acceptable.

**Comment by dannykQuali** [comment]
Sure! I have implemented a fix and a test. How do I become a collaborator?
