### ISSUE TITLE
Cannot specify AuthenticationScheme when using the new [Authorize] support.

### ISSUE THREAD

**Issue by gulbanana** [CoreWCF/CoreWCF#1143]
It's great to be able to integrate with ASP.NET Core's auth system, but I need to use HTTP Basic and output `<http:BasicAuthentication/>` in my WSDL. In order to use [Authorize], you currently have to have ClientCredentialType.InheritedFromHost instead of ClientCredentialType.Basic; this doesn't use a policy-provided AuthenticationScheme, only the DefaultScheme, so it doesn't call ChallengeAsync() on my custom basic auth handler. 

It also doesn't provide any authentication scheme in the service metadata. This can be done with a CustomBinding, but then there's no way to trigger the [Authorize] support - it does a type check for BasicHttpBinding, WebHttpBinding and WSHttpBinding specifically.

**Comment by mconnew** [comment]
I'm going to address your questions in reverse order.  

If you set the client credential type to Basic, we call HttpContext.ChallengeAsync("Basic"). As long as you have an authentication scheme registered for `Basic` in the asp.net core authentication setup, then it should work correctly. Then your WSDL should have the correct authentication policy listed.  

For whether the `[Authorize]` attribute is honored, there's a convoluted but extensible way to achieve this. The way this is decided is by the code here:  
https://github.com/CoreWCF/CoreWCF/blob/bbc1a9f3c97efad629598926e11852e6d2dfefb2/src/CoreWCF.Primitives/src/CoreWCF/Description/EndpointAuthorizationBehavior.cs#L24

We ask the binding if it has a property of type IAuthorizationCapabilities:
https://github.com/CoreWCF/CoreWCF/blob/bbc1a9f3c97efad629598926e11852e6d2dfefb2/src/CoreWCF.Primitives/src/CoreWCF/Channels/IAuthorizationCapabilities.cs#L6-L9

You will need to write a custom BindingElement which in the GetProperty method does something similar to this code:
https://github.com/CoreWCF/CoreWCF/blob/bbc1a9f3c97efad629598926e11852e6d2dfefb2/src/CoreWCF.Http/src/CoreWCF/Channels/HttpTransportBindingElement.cs#L256-L264

You will need to redefine your own implementation of AuthorizationCapabilities as that is an internal implementation, but it's super simple. Add your custom BindingElement to the end of your CustomBinding. I.e. instantiate a CustomBinding from your existing binding, then call CustomBinding.Elements.Add. When starting up, CoreWCF will query the binding for an `IAuthorizationCapabilities` instance. Your custom binding being on top will answer first and return your class which will return true for `SupportsAuthorizationData` which activates all the code to use the `[Authorize]` attribute.  

@g7ed6e, what do you think about coming up with an easy public api to turn this on and override the default decision?

**Comment by gulbanana** [comment]
Sounds like the design does support this case after all! I knew about IAuthorizationCapabilities, but I didn't realise that setting AuthenticationScheme.Basic would result in a ChallengeAsync. It would be nice if the authorizationschemes defined by a policy were applied, but this is already better than the previous quo where you had to use a pipeline fork and inspect the HttpRequest before CoreWCF looks at it.

**Comment by g7ed6e** [comment]
@gulbanana I'm working on exposing a public API that ease the plumbing but for the time being have a look to the unit tests introduced in #1148
