### ISSUE TITLE
How to create Custom ServiceHostFactory in CoreWCF

### ISSUE THREAD

**Issue by pascalrebello** [CoreWCF/CoreWCF#1151]
How to create Custom ServiceHostFactory in CoreWCF

In the case of WCF we can extend it by using ServiceHostFactory and SeviceHost.

And finally mentioning the Factory in the .SVC file like this (<% @ ServiceHost Language="C#" Service="WcfService1.Service1"
Factory="WcfService1.MyWebServiceHostFactory" %>

So similar way how we can implement this in CoreWCF? Kindly share your valuable suggestions.

**Comment by mconnew** [comment]
The hosting model is different in CoreWCF. The easiest way to solve you query is to ask what's the underlying problem you are trying to solve by having a custom ServiceHostFactory?

**Comment by pascalrebello** [comment]
How we can retrieve WSDL and overrides the default WCF behavior by embedding XSD documents that are referenced by the WSDL documents?

I'm trying to achieve this by implementing: IWsdlExportExtension, IEndpointBehavior, and by adding logic to manipulate the WSDL in the ExportEndpoint method.

public void ExportEndpoint(WsdlExporter exporter, WsdlEndpointConversionContext context)

Question: How we can invoke this custom class which implements the IWsdlExportExtension, IEndpointBehavior in core WCF?
