### ISSUE TITLE
Unable to access CoreWCF service on IIS with HttpClientCredentialType.Windows 

### ISSUE THREAD

**Issue by drpdrp** [CoreWCF/CoreWCF#1165]
### Duplicate ?

- [ ] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.3.0

### Describe expected behavior

Using the default CoreWCF server template **MyService**, we are trying to enable Windows/Kerberos authentication in IIS. Adding windows authentication works as expected in debug mode in Visual Studio with WCF Test Client (WcfTestClient.exe from Visual Studio).

### Describe actual behavior

When we host the service in IIS, using WCF Test Client as client, we get error:

**The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'Negotiate,NTLM'.**

We tried changing IIS Windows Authentication providers to no results. What are we not seeing here? How should this be set up? Thanks

Commented out code in Program.cs was tried to resolve the issue.

### Which binding

BasicHttp

### security

Transport

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
using Microsoft.AspNetCore.Authentication.Negotiate;

var builder = WebApplication.CreateBuilder();
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();
//builder.Services.AddAuthorization(options =>
//{
//    options.DefaultPolicy = new AuthorizationPolicyBuilder()
//        .RequireAuthenticatedUser()
//        .Build();
//    options.FallbackPolicy = options.DefaultPolicy;
//});

builder.Services.AddServiceModelServices();
builder.Services.AddServiceModelMetadata();
builder.Services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();

var app = builder.Build();

//app.UseAuthentication();
//app.UseAuthorization();

app.UseServiceModel(serviceBuilder =>
{
    var binding = new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.Windows // should be InheritedFromHost? But how to set it up?
            }
        }
    };

    serviceBuilder.AddService<Service>();
    serviceBuilder.AddServiceEndpoint<Service, IService>(binding, "/Service.svc");
    var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    serviceMetadataBehavior.HttpsGetEnabled = true;
});

app.Run();
```

**Comment by drpdrp** [comment]
I have found a workaround for this bug in this issue: https://github.com/CoreWCF/CoreWCF/issues/757

We need to use AllowedImpersonationLevel = TokenImpersonationLevel.None or Delegation, so in client config use something like this endpoint behavior:

`
        <behaviors>
            <endpointBehaviors>
                <behavior name="TokenImpersonationLevelNone">
                    <clientCredentials>
                        <windows allowedImpersonationLevel="None" />
                    </clientCredentials>
                </behavior>
            </endpointBehaviors>
        </behaviors>
`

in the endpoint, state the behavior:

`
        <client>
            <endpoint address="https://localhost/Service.svc" behaviorConfiguration="TokenImpersonationLevelNone" binding="basicHttpBinding" bindingConfiguration="BasicHttpBinding_IService" contract="IService" name="BasicHttpBinding_IService" />
        </client>
`

**Comment by mconnew** [comment]
Closing as you have a workaround and the underlying problem is being tracked in the other issue.
