### ISSUE TITLE
[Bug]: DI Source Generator throws when contract or service implementation are in global namespace

### ISSUE THREAD

**Issue by mgaffigan** [CoreWCF/CoreWCF#1176]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.3.2 (also reproducible in 1.4.0-preview1)

### Describe expected behavior

No exception is thrown

### Describe actual behavior

An exception is thrown in the source generator.

>CSC : warning CS8785: Generator 'OperationParameterInjectionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName '&lt;global namespace&gt;_IService_Operation.g.cs' contains an invalid character '&lt;' at position 0.

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 7.0.306

### Which os platform

Windows

### Code snippet used to reproduce the issue
Full repro at https://github.com/mgaffigan/CoreWcfCodeGenIssue/tree/global-namespace

```c#
using Microsoft.AspNetCore.Mvc;
using System.ServiceModel;

[ServiceContract]
public interface IService
{
    [OperationContract]
    void Operation();
}

public partial class Service : IService
{
    public void Operation([FromServices] HttpContext hc)
    {
    }
}
```

**Comment by mconnew** [comment]
@g7ed6e, can you take a look please.
