### ISSUE TITLE
[Bug]: DI Source Generator produces invalid code when attribute applied to operation contains array

### ISSUE THREAD

**Issue by mgaffigan** [CoreWCF/CoreWCF#1177]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.3.2 (also reproducible in 1.4.0-preview1)

### Describe expected behavior

Source generator generates correct code for attributes containing arrays:

        [Demo.ExampleAttribute(new[] {"A"})]
        public void Operation()
        // ...

### Describe actual behavior

Source generator generates incorrect code for attributes containing arrays:

        [Demo.ExampleAttribute({"A"})]
        public void Operation()
        // ...

Compilation errors occur:

>C:\dev\source\repos\CoreWcfCodeGenIssue\CoreWCF.BuildTools.Roslyn4.0\CoreWCF.BuildTools.OperationParameterInjectionGenerator\Demo_IService_Operation.g.cs(9,21,9,30): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
>C:\dev\source\repos\CoreWcfCodeGenIssue\Program.cs(24,36,24,44): error CS0535: 'Service' does not implement interface member 'IService.Operation()'

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 7.0.306

### Which os platform

Windows

### Code snippet used to reproduce the issue
Full sample at https://github.com/mgaffigan/CoreWcfCodeGenIssue/tree/bad-arrays

```c#
using Microsoft.AspNetCore.Mvc;
using System.ServiceModel;

// Provide main
Console.WriteLine();

namespace Demo
{
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = true)]
    sealed class ExampleAttribute : Attribute
    {
        public ExampleAttribute(params string[] args)
        {
        }
    }

    [ServiceContract]
    public interface IService
    {
        [OperationContract]
        void Operation();
    }

    public partial class Service : IService
    {
        [Example("A")]
        public void Operation([FromServices] HttpContext hc)
        {
        }
    }
}
```

**Comment by mconnew** [comment]
@g7ed6e, can you take a look?

**Comment by g7ed6e** [comment]
Thank you for reporting issue @mgaffigan. 
Can you clarify which LangVersion csproj property and tfm you are using ?
FYI, the source generator is using https://github.com/dotnet/roslyn/blob/b91897c8ad5cea55a9d91c5b5b7b1f2a37ce7ead/src/Compilers/CSharp/Portable/Symbols/TypedConstantExtensions.cs#L27 to output the attribute.

**Comment by mgaffigan** [comment]
csproj from [the repro](https://github.com/mgaffigan/CoreWcfCodeGenIssue/blob/bad-arrays/CoreWcfCodeGenIssue.csproj) is:

```
﻿<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CoreWCF.Http" Version="1.3.2" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
  </ItemGroup>

</Project>
```

(csc 4.6.8.25908 / [`LangVersion = 11.0`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults) / `TargetFrameworkMoniker = .NETCoreApp,Version=v7.0`)

Looking at the commit history for `ToCSharpString`, it looks like it was [originally added and used](https://github.dev/dotnet/roslyn/tree/3611ed35610793e814c8aa25715aa582ec08a8b6) only in methods labelled "for testing and debugging only".  Array initializers only [appear to be valid](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/arrays#177-array-initializers) in field declarations and local variable declarations.  I cannot find any language version which permits them in [`attribute_argument_expression`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#223-attribute-specification:~:text=An%20expression%20E%20is%20an%20attribute_argument_expression%20if%20all%20of%20the%20following%20statements%20are%20true%3A) (which defers to [`expression`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#128165-array-creation-expressions)).

**Comment by g7ed6e** [comment]
> Thank you for jumping on it! It's been great to have WCF in .Net 5+.
> 
> csproj from [the repro](https://github.com/mgaffigan/CoreWcfCodeGenIssue/blob/bad-arrays/CoreWcfCodeGenIssue.csproj) is:
> 
> ```
> ﻿<Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net7.0</TargetFramework>
>     <ImplicitUsings>enable</ImplicitUsings>
>     <Nullable>enable</Nullable>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="CoreWCF.Http" Version="1.3.2" />
>     <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> (csc 4.6.8.25908 / [`LangVersion = 11.0`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults) / `TargetFrameworkMoniker = .NETCoreApp,Version=v7.0`)
> 
> Looking at the commit history for `ToCSharpString`, it looks like it was [originally added and used](https://github.dev/dotnet/roslyn/tree/3611ed35610793e814c8aa25715aa582ec08a8b6) only in methods labelled "for testing and debugging only". Array initializers only [appear to be valid](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/arrays#177-array-initializers) in field declarations and local variable declarations. I cannot find any language version which permits them in [`attribute_argument_expression`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#223-attribute-specification:~:text=An%20expression%20E%20is%20an%20attribute_argument_expression%20if%20all%20of%20the%20following%20statements%20are%20true%3A) (which defers to [`expression`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#128165-array-creation-expressions)).
> 
> Presumably a bug in `ToCSSharpString`, then.

Thank you for the investigation. I will fix it then.
