### ISSUE TITLE
[Bug]: Incompatible with Apache CXF client, becouse in SOAP header `Security` added `role` attribute

### ISSUE THREAD

**Issue by gekiss** [CoreWCF/CoreWCF#1182]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.3.2

### Describe expected behavior

In SOAP header `Security` remove `role` attribute with value `http://www.w3.org/2003/05/soap-envelope/role/ultimateReceive`

According [SOAP12 specification](https://www.w3.org/TR/soap12-part1/#soaprole) 

> Omitting the SOAP role attribute information item is equivalent to supplying that attribute with a value of "http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver".

Expected response sample:
``` XML
<o:Security s:mustUnderstand="1" ...
````

### Describe actual behavior

Actual response:
``` XML
<o:Security s:role="http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver" s:mustUnderstand="1" ...
````

Just set actor to string.Empty 
https://github.com/CoreWCF/CoreWCF/blame/98434d02ade6f5c17e7db954b74370a34fbad2c3/src/CoreWCF.Primitives/src/CoreWCF/Security/TransportSecurityProtocol.cs#L31C53-L31C77

as done in .NET Framework source

https://referencesource.microsoft.com/#system.servicemodel/System/ServiceModel/Security/TransportSecurityProtocol.cs,31 

what is remarkable in line 105 is already commented out

https://github.com/CoreWCF/CoreWCF/blame/98434d02ade6f5c17e7db954b74370a34fbad2c3/src/CoreWCF.Primitives/src/CoreWCF/Security/TransportSecurityProtocol.cs#L105
https://referencesource.microsoft.com/#system.servicemodel/System/ServiceModel/Security/TransportSecurityProtocol.cs,209

Thanks for your work.

### Which binding

WsHttp

### security

TransportWithMessageCredential

### Which .NET version

.NET 6

### Which os platform

Windows

**Comment by birojnayak** [comment]
@gekiss are you open to post a PR ? I ported the WSHttp, would be happy to review your PR ? If you don't have time, let me know.

**Comment by mconnew** [comment]
@birojnayak, @gekiss, I'm working on the final prep for the next release. To make sure this gets in, I'll pick this up and make the fix as it's a trivial change.

@gekiss, I really appreciate you finding the root cause of this, it makes releasing a fix a lot quicker and easier.

**Comment by mconnew** [comment]
@gekiss, I've created a fix for a couple of reasons:
1. The WCF .NET Framework implementation didn't add the role header
2. While including or excluding the attribute are both valid, interop is important.

Have you considered opening an issue with Apache CFX? From a purely technical standpoint, they are actually the ones with the bug as the presence of the attribute is still correct and should be accepted by the Apache CFX client.
