### ISSUE TITLE
[Question]: 1.4.0 release date

### ISSUE THREAD

**Issue by Belorus** [CoreWCF/CoreWCF#1187]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.3.2

### Describe expected behavior

Hi guys,

Do you have an idea when 1.4.0 can reach nuget?

I want to start migration of my ball-of-legacy to .net6 and want to tie it to 1.4.0 release of CoreWCF. I see there are lots of great commits since March.

Thanks!

### Describe actual behavior

:)

### Which binding

NetTcp

### security

None

### Which .NET version

.NET 6

### Which os platform

Linux

**Comment by birojnayak** [comment]
@Belorus yes... we have been discussing and @mconnew can give tentative date... (I assume 2/3 weeks).  Does your app works with [pre version](https://github.com/CoreWCF/CoreWCF/releases/tag/v1.4.0-preview1)  (if you are experimenting) ?
