### ISSUE TITLE
Changing the environment not working

### ISSUE THREAD

**Issue by hamidnoahdi** [CoreWCF/CoreWCF#1236]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.4.0

### Describe expected behavior

When I change the environment is IntegrationTests using WebApplicationFactory, I expect that the environment be changed but is not.

### Describe actual behavior

The environment is always "Production"

### Which binding

WsHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
public class MyWebApplicationFactory : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseEnvironment("Test");
        base.ConfigureWebHost(builder);
    }
}
```

**Comment by mconnew** [comment]
This isn't anything that CoreWCF gets involved with. I suggest opening the issue in https://github.com/dotnet/aspnetcore
Closing as not a CoreWCF issue.

**Comment by hamidnoahdi** [comment]
Thanks mconnew, but this happens with project that contains CoreWCF, in a project like WebApi, the environment changes as expected.
