### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by TonyValenti** [CoreWCF/CoreWCF#125]
Hi All,
Does anyone have an idea on when this library will be production ready?  Also, will it work on .NET 4.x or just .NET core?  I am hopeful .NET 4.x that way we can make a gradual transition to .NET Core / 5.x.

**Comment by mamift** [comment]
Can't speak to when it will be production ready, but the CoreWCF libraries target .NET Standard 2, so it can be used from .NET Standard 2 compatible implementations, which includes .NET Framework 4.6.2 and higher.

**Comment by mconnew** [comment]
We will be doing our initial GA release in the new year, currently planned for late January
