### ISSUE TITLE
[Bug]: Complex types are not sent correctly from NetCoreClient to server, in CoreWCF samples 

### ISSUE THREAD

**Issue by louvasilev** [CoreWCF/CoreWCF#1253]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.0.0

### Describe expected behavior

In the sample NetCoreClient [(https://github.com/CoreWCF/samples)](https://github.com/CoreWCF/samples) there is a method ComplexEcho, in the interface IEchoService, which takes a complex type EchoMessage as a parameter.

```csharp
[ServiceContract]
public interface IEchoService
{
    // Note: The contract on the client has been changed to make the methods async.
    [OperationContract]
    Task<string> Echo(string text);
   
    [OperationContract]
    Task<string> ComplexEcho(EchoMessage text);
}
```

Trying to call this method, against the sample MinimalAPIServer should result in the value for EchoMessage.Text property being "Test Message".

```csharp
var result = await client.ComplexEcho(new Contract.EchoMessage() { Text = "Test Message" });
```

### Describe actual behavior

In the sample NetCoreClient [(https://github.com/CoreWCF/samples)](https://github.com/CoreWCF/samples) there is a method ComplexEcho, in the interface IEchoService, which takes a complex type EchoMessage as a parameter.

```csharp
[ServiceContract]
public interface IEchoService
{
    // Note: The contract on the client has been changed to make the methods async.
    [OperationContract]
    Task<string> Echo(string text);
   
    [OperationContract]
    Task<string> ComplexEcho(EchoMessage text);
}
```

Trying to call this method, against the sample MinimalAPIServer, results in the value for EchoMessage.Text property being null. Making a call to the Echo method works fine. In summary, sending complex types to a CoreWCF server from the NetCoreClient sample does not work.  

```csharp
var result = await client.ComplexEcho(new Contract.EchoMessage() { Text = "Test Message" });
```

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
using System;
using System.ServiceModel;
using System.Threading.Tasks;
using Contract;

namespace NetCoreClient
{
    public class Program
    {
        public const int HTTP_PORT = 8088;
        public const int HTTPS_PORT = 8443;
        public const int NETTCP_PORT = 8089;

        static async Task Main(string[] args)
        {
            Console.Title = "WCF .Net Core Client";

            await CallBasicHttpBinding($"http://localhost:{HTTP_PORT}");
        }

        private static async Task CallBasicHttpBinding(string hostAddr)
        {
            IClientChannel channel = null;

            var binding = new BasicHttpBinding(IsHttps(hostAddr) ? BasicHttpSecurityMode.Transport : BasicHttpSecurityMode.None);

            var factory = new ChannelFactory<IEchoService>(binding,
                new EndpointAddress($"{hostAddr}/EchoService/basicHttp"));
            factory.Open();
            try
            {
                IEchoService client = factory.CreateChannel();
                channel = client as IClientChannel;
                channel.Open();
                //var result = await client.Echo("Hello World!");

                var result = await client.ComplexEcho(new Contract.EchoMessage() { Text = "Test Message" });

                channel.Close();
                Console.WriteLine(result);
            }
            finally
            {
                factory.Close();
            }
        }

        private static bool IsHttps(string url)
        {
            return url.ToLower().StartsWith("https://");
        }
    }
}
```

**Comment by mconnew** [comment]
Is the .NET namespace the same for the contract interface on the client and server?

**Comment by louvasilev** [comment]
Nope, they are different. On the client the namespace is `Contract` and on the server it is `MyContracts`. Once I made them the same it started working fine. Wow, such a simple fix and I spent so much time on it.

Thanks!
