### ISSUE TITLE
[Bug]: Mixing CoreWCF with traditional API controllers

### ISSUE THREAD

**Issue by ssteiner** [CoreWCF/CoreWCF#1268]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.4.1

### Describe expected behavior

I'd like to register a bunch of modern style web API controllers along with my WCF controllers. the WCF part works fine (using the netTCP binding). But, trying to access any method on any of my two Web API controllers gets me a 404.

### Describe actual behavior

Trying to access any method on any of my two Web API controllers gets me a 404, as if the controllers were not registered.

When I enable debug logging on all categories, all I see is 

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:8091/SmartAppMobile/GetVersionNumber - -
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[9]
      Connection id "0HMUQOKULLAC0" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:8091/SmartAppMobile/GetVersionNumber - - - 404 0 - 17.9136ms

it's as if the controller were not registered.

### Which binding

NetTcp

### security

None

### Which .NET version

.NET 7

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
var builder = WebApplication.CreateBuilder();
builder.WebHost.UseNetTcp(8088);
builder.WebHost.ConfigureKestrel(options => 
{
    options.ListenAnyIP(8091);
});
builder.Services.AddServiceModelServices()
  .AddControllers()
  .AddControllersAsServices()
.AddJsonOptions(options => options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
var clientApp = builder.Build()
clientApp.Start()

Any an abbreviated version of my controller (living controllers:

[ApiController]
[Route("[controller]")]
public class SmartAppNgController:ControllerBase
{
  [HttpGet, Route("GetVersionNumber")]
  public BooleanResult<string> IsAlive()
  {
    EndpointAddress addr = GetEndpointAddress();
    Log($"Received an isAlive request from {addr.Address}", 5);
    return new BooleanResult<string> { Code = BooleanOperationResultCode.Success, Result = "1.0.0" };
  }

}
```

**Comment by mconnew** [comment]
I don't know anything about how the Mvc controllers get wired up. I had a quick look into how the code works and it looks like it should add your SmartAppNgController type to DI. I wouldn't expect anything CoreWCF is doing would interfere, especially as you haven't actually configured any CoreWCF services or endpoints.  

Have you validated that it works if you remove the UseNetTcp and AddServiceModelServices calls? If it works with both of them removed, try adding just one back and see if just one of them breaks things, or if it needs both.  

Before you call Start(), try calling `clientApp.ApplicationServices.GetService<SmartAppNgController>()` to see if it got discovered and added to the Mvc controllers as it adds it to DI at the same time as it adds it to the list of controllers.  

The dotnet/aspnetcore repo would be a better place to ask as I didn't find any code in the Mvc implementation which we could clash with.

**Comment by ssteiner** [comment]
Turns it this has nothing to do with CoreWCF indeed. I'm hosting the entire WebApp in a class library and it appears controller registration is different versus hosting the WebApp directly in the app itself. I had to register the assembly containing the controllers manually using

```var asm = typeof(Class-in-assembly-containing-controllers).Aassembly
builder.Services.AddControllers().AddApplicationParts(asm);````

it didn't even need `AddControllersAsServices`. Using that, things worked fine in my basic repro sample as well as my actual application. As a sidenote, the following also works in some of my apps

````services.AddControllers.AddNewtonsoftJson(options => { // json serialization  config here});```
