### ISSUE TITLE
Any upgrade plan for .net core 3.1

### ISSUE THREAD

**Issue by KamranShahid** [CoreWCF/CoreWCF#127]
Any upgrade plan for .net core 3.1
Trying sample for server side but it isn't even compiling

**Comment by birojnayak** [comment]
you should be able to compile locally for .net core 3.1, if you have the latest SDK, change the global.json and update package references to support above version

**Comment by KamranShahid** [comment]
Thanks Biroj Nayak
I have used soapcore instead.
