### ISSUE TITLE
[Bug]: 1.5.0 no longer compiles against ASP.NET 2.2  due to type which does not exist in compiled extensions code. 

### ISSUE THREAD

**Issue by gougeman** [CoreWCF/CoreWCF#1279]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.0

### Describe expected behavior

Upgrading to CoreWCF 1.5.0 no longer compiles against ASP.NET Core 2.2 and .NET Framework (My understanding is that this would be supported until 2.0). 

The error is a missing type in the extensions file. The type does not exist in this version of ASP.NET. This comes from PR #1235. 

There is a workaround described in issue #1276 which (once fixed to use the right syntax) removes the file, but if ASP.NET Core 2.2 is going to continue to be supported until 2.0 then it should work natively. 

### Describe actual behavior

Severity	Code	Description	Project	File	Line	Suppression State	Priority
Error	CS0234	The type or namespace name 'WebApplication' does not exist in the namespace 'Microsoft.AspNetCore.Builder' (are you missing an assembly reference?)	Windows.Services.DeliveryCatalog.Service.Common.CoreWCF	

corewcf.primitives\1.5.0\contentFiles\CoreWCFWebApplicationExtensions.cs	10	N/A	Normal

### Which binding

CustomBinding

### security

None

### Which .NET version

.NET 4.7.2

### Which os platform

Windows

**Comment by mconnew** [comment]
ASP.NET Core 2.2 is NOT supported. It wasn't an LTS release so support was dropped a few years back. This isn't a CoreWCF policy, this is a Microsoft .NET support policy. For .NET Framework, the supported version is ASP.NET Core 2.1.  
See the section headed "ASP.NET Core 2.1 on .NET Framework" on [its support lifecycle policy page](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).  

Whether you are using ASP.NET Core 2.1 or 2.2 should be irrelevant for this issue though. The new file is conditionally included based on the target framework. It trims any digits off the end of the target framework and compares it to "net". So if you target net6.0, it compares "net6." with "net" and as they are different, includes in. For .NET Framework, something like "net472" should trim to "net" so exclude it.  

I just realized if you are targeting netstandard2.0, that would trim to "netstandard2." and be treated the same as .NET 6.0. Is this your scenario?

Also I'm curious how you used 1.5.0? It's unlisted on nuget as we're not quite ready to release it. There's a WCF Client component that needs to be released at the same time which isn't quite ready.

**Comment by mconnew** [comment]
Also could you please provide the corrected syntax for the Compile Exclude so that I can fix the comment?

**Comment by gougeman** [comment]
Syntax for the exclude seems to be using "Remove" instead of "Exclude" in the directive. Exclude only works for an item group inside a task. 

MSB4232	Items that are outside Target elements must have one of the following operations: Include, Update, or Remove.	

Also (of course) the path may need to be updated depending on the dir layout of the project, but that's neither here nor there).

**Comment by bjornen77** [comment]
> Also I'm curious how you used 1.5.0?

The 1.5.0 version can already be installed using Visual Studio 2022(Manage NuGet Packages)

**Comment by gougeman** [comment]
To immortalize offline conversation - yes we are targeting .NET Standard 2.0

**Comment by gougeman** [comment]
Appears Fixed in 1.5.1,
