### ISSUE TITLE
[Bug]: Testint CoreWcf.Http project with XUnit and UseTestServer()

### ISSUE THREAD

**Issue by benzmarkus** [CoreWCF/CoreWCF#1312]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.1

### Describe expected behavior

I would expect to write integration tests like in the documentation from microsoft
[https://learn.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-8.0](https://learn.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-8.0)

### Describe actual behavior

With UseTestServer() i can create a fully functional webapi and call all the methods by creating a test with GetTestClient(), as described here: [https://learn.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-8.0](https://learn.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-8.0)

I tried to start the same way the server for CoreWcf but we just get the log entry:
[14:59:59 INF] User profile is available. Using '' as key repository and Windows DPAPI to encrypt keys at rest.

... then the startup does not continue.

After starting the service i tried to call the methods but i get a server does not response message.

Would be cool to des all coreWcf method with integration tests.

### Which binding

BasicHttp

### security

Transport

### Which .NET version

.NET 6

### Which os platform

Windows

**Comment by mconnew** [comment]
Closing as I believe it's been answered and there are no more follow ups.
