### ISSUE TITLE
[Bug]: Visual Basic vbproj project file referencing CoreWCF packages fails to build

### ISSUE THREAD

**Issue by LucDD** [CoreWCF/CoreWCF#1316]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.1

### Describe expected behavior

When referencing the CoreWCF.Primitives package from a vbproj project file the project should build successfully.

### Describe actual behavior

The project fails to build with numerous syntax errors from the file CoreWCFWebApplicationExtensions.cs

Workaround is to put this in the vbproj file:
<_CoreWCFSuppressWebApplicationExtensions>true</_CoreWCFSuppressWebApplicationExtensions>

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

**Comment by mconnew** [comment]
We're going to suppress the extension class being added if the project isn't C# as the intention of this change was to not break existing projects and this is the first time this problem has been raised. The solution to what this is fixing is to cast WebApplication to an interface in your own code so its absence for VB isn't a blocker.
