### ISSUE TITLE
[Bug]: Can not use MessageCredentialType.IssuedToken for WSHttpBinding

### ISSUE THREAD

**Issue by emre-toraman** [CoreWCF/CoreWCF#1317]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.1

### Describe expected behavior

We are using MessageCredentialType.IssuedToken for WSHttpBinding in WCF hosted on .Net Framework 4.8. We would like to be able to do the same in CoreWCF.

### Describe actual behavior

System.NotSupportedException is thrown on CoreWCF.Configuration.WebApplicationExtensions.UseServiceModel. It seems this is caused by commented out code in https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Primitives/src/CoreWCF/Security/MessageSecurityOverHttp.cs
```
                    //case MessageCredentialType.IssuedToken:
                    //    oneShotSecurity = SecurityBindingElement.CreateIssuedTokenOverTransportBindingElement(IssuedSecurityTokenParameters.CreateInfoCardParameters(new SecurityStandardsManager(new WSSecurityTokenSerializer(emitBspAttributes: true)), this.algorithmSuite));
                    //    break;
```

Does this mean it is not supported yet and if so, is the support expected in any feature roadmap? If not, can I try to enable the support and contribute?

On a side note, we don't see any issue if we use WSFederationHttpBinding, or WSHttpBinding with MessageCredentialType.Certificate as a workaround. I believe this is because we have our own custom ServiceCredentials and ServiceAuthorizationManager overrides. But even though the workaround seems working, it's not desired for us to have misleading configuration.

**Simple app to reproduce**
[CoreWcf.IssuedToken.zip](https://github.com/CoreWCF/CoreWCF/files/13833697/CoreWcf.IssuedToken.zip)

### Which binding

WsHttp

### security

TransportWithMessageCredential

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
var builder = WebApplication.CreateBuilder();

builder.Services.AddServiceModelServices();
builder.Services.AddServiceModelMetadata();
builder.Services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();

var app = builder.Build();

app.UseServiceModel(serviceBuilder =>
{
    var httpBinding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);

    httpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;

    httpBinding.Security.Message.EstablishSecurityContext = false;
    httpBinding.Security.Message.NegotiateServiceCredential = false;
    httpBinding.Security.Message.ClientCredentialType = MessageCredentialType.IssuedToken;

    serviceBuilder.AddService<Service>();
    serviceBuilder.AddServiceEndpoint<Service, IService>(httpBinding, "/Service.svc");

    var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    serviceMetadataBehavior.HttpsGetEnabled = true;
});

app.Run();
```

### Stacktrace if any

```shell
System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=CoreWCF.Primitives
  StackTrace:
   at CoreWCF.MessageSecurityOverHttp.CreateSecurityBindingElement(Boolean isSecureTransportMode, Boolean isReliableSession, MessageSecurityVersion version) in CoreWCF\MessageSecurityOverHttp.cs:line 80
   at CoreWCF.WSHttpBindingBase.CreateBindingElements() in CoreWCF\WSHttpBindingBase.cs:line 120
   at CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder app) in CoreWCF.Configuration\ServiceModelApplicationBuilderExtensions.cs:line 50
   at CoreWCF.Configuration.WebApplicationExtensions.UseServiceModel(WebApplication app, Action`1 configureServices) in C:\Users\etoraman\.nuget\packages\corewcf.primitives\1.5.1\contentFiles\CoreWCFWebApplicationExtensions.cs:line 21
   at Program.<Main>$(String[] args) in C:\dev\CoreWcf.IssuedToken\CoreWcf.IssuedToken\Program.cs:line 11
```

**Comment by emre-toraman** [comment]
I tested locally to uncomment the lines I mentioned in the original post (https://github.com/emre-toraman/CoreWCF/commit/d66dc9dc27aa3859206d111f1bc3062d93f8b51d). It worked for our use case which is reading a JWT, using extended ServiceCredentials, from a header like this:
```
<s:Header>
	<a:Action s:mustUnderstand="1">http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy/IPolicy/GetPolicies</a:Action>
	<a:MessageID>urn:uuid:GUID</a:MessageID>
	<a:ReplyTo>
		<a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
	</a:ReplyTo>
	<a:To s:mustUnderstand="1">https://sample.com/service</a:To>
	<wsse:Security s:mustUnderstand="1">
		<wsse:BinarySecurityToken ValueType="urn:ietf:params:oauth:token-type:jwt" EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd#base64binary">Base64EncodedJWT</wsse:BinarySecurityToken>
	</wsse:Security>
	<a:RelatesTo>urn:uuid:GUID</a:RelatesTo>
</s:Header>
```

Can you please let us know if this code change is sufficient or provide guidance what else needs to be checked?

**Comment by emre-toraman** [comment]
@birojnayak Have you had a chance to take a look? Do you think this is something we can have in the near future?

**Comment by birojnayak** [comment]
@emre-toraman as you see it's not supported yet.. if you know the fix, feel free to submit a PR (Would really appreciate that). Otherwise you can wait for few months, I can take care during End/End WSHttpBInding Message encryption.
