### ISSUE TITLE
[Bug]: CoreWCF.WebHttp 1.5.2 nuget missing

### ISSUE THREAD

**Issue by MaceWindu** [CoreWCF/CoreWCF#1354]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.2

### Describe expected behavior

Release https://github.com/CoreWCF/CoreWCF/releases/tag/v1.5.2 contains reference to non-existing https://www.nuget.org/packages/CoreWCF.WebHttp/1.5.2 package

### Describe actual behavior

nope

### Which binding

WebHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
1
```

**Comment by mconnew** [comment]
I don't know how that happened. I checked the folder I uploaded everything from and it was in that folder, and I uploaded using the wildcard *.nupkg. I've uploaded it now, along with UnixDomainSocket which also didn't get uploaded. I've checked every package manually and there are packages with versions v1.5.2 and v1.4.2 uploaded for all GA released packages. It might take a few minutes for it to finish indexing, but you'll see it soon.
