### ISSUE TITLE
NetTcpBinding don't work on Linux

### ISSUE THREAD

**Issue by Alex-MT-Denexy** [CoreWCF/CoreWCF#136]
I have client application that connects to CoreWCF service using NetTcpBinding.
When service is run as console application on Windows it works fine.
But when I tried to run CoreWCF service in Docker on Linux, then client gets an Exception:
`System.ServiceModel.Security.MessageSecurityException: "The server rejected the upgrade request."`

> System.ServiceModel.Security.MessageSecurityException
>   HResult=0x80131500
>   Сообщение = The server rejected the upgrade request.
>   Источник = System.Private.ServiceModel
>   Трассировка стека:
>    at System.ServiceModel.Channels.ConnectionUpgradeHelper.ValidateUpgradeResponse(Byte[] buffer, Int32 count, ClientFramingDecoder decoder)
>    at System.ServiceModel.Channels.ConnectionUpgradeHelper.<InitiateUpgradeAsync>d__3.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<SendPreambleAsync>d__10.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.ServiceModel.Channels.ConnectionPoolHelper.<EstablishConnectionAsync>d__15.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<OnOpenAsync>d__12.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.CommunicationObject.<OnOpenAsyncInternal>d__85.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__84.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__83.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
>    at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
>    at System.Runtime.TaskHelpers.<CallActionAsync>d__21`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.CommunicationObject.<OpenOtherAsync>d__114.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.ServiceChannel.<OnOpenAsync>d__152.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.CommunicationObject.<OnOpenAsyncInternal>d__85.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__84.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__83.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
>    at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.Open()
>    at System.ServiceModel.Channels.ServiceChannelProxy.System.ServiceModel.ICommunicationObject.Open()
>    at TestMail.Program.Main(String[] args) in D:\Denexy\TestMail\Program.cs:line 18
> 
> Внутреннее исключение 1:
> ProtocolException: Error while reading message framing format at position 0 of stream (state: ReadingUpgradeRecord)
> 
> Внутреннее исключение 2:
> InvalidDataException: More data was expected, but EOF was reached.

The client code is:
```
NetTcpBinding binding = new NetTcpBinding();
EndpointAddress endpoint = new EndpointAddress("net.tcp://localhost:8737");

using var factory = new ChannelFactory<IMailService>(binding, endpoint);
factory.Open();
IMailService channel = factory.CreateChannel();
((IClientChannel)channel).Open(); //fails here
```

I'm using **CoreWCF.NetTcp** version **0.1.0-alpha.74**

**Comment by Alex-MT-Denexy** [comment]
I tried to run both programs on Linux without Docker on same VM. Client channel opens successfully, but other Exception raises when calling WCF-method.

On the server:

> fail: Microsoft.AspNetCore.Server.Kestrel[0]
>       Unhandled exception while processing 0HM06QSOPCEVJ.
> CoreWCF.Security.SecurityNegotiationException: Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
>  ---> System.Security.Authentication.AuthenticationException: Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
>  ---> System.ComponentModel.Win32Exception (0x80004005): Unknown error
>    --- End of inner exception stack trace ---
>    at System.Net.Security.NegoState.ThrowCredentialException(Int64 error)
>    at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)
>    at System.Net.Security.NegoState.ReadCallback(IAsyncResult transportResult)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
>    at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
>    at System.Net.Security.NegotiateStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at CoreWCF.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeAcceptor.OnAcceptUpgradeAsync(Stream stream)
>    --- End of inner exception stack trace ---
>    at CoreWCF.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeAcceptor.OnAcceptUpgradeAsync(Stream stream)
>    at CoreWCF.Channels.StreamSecurityUpgradeAcceptorBase.AcceptUpgradeAsync(Stream stream)
>    at CoreWCF.Channels.Framing.ServerFramingDuplexSessionMiddleware.UpgradeConnectionAsync(FramingConnection connection)
>    at CoreWCF.Channels.Framing.ServerFramingDuplexSessionMiddleware.OnConnectedAsync(FramingConnection connection)
>    at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.<>c__DisplayClass4_1.<<BuildHandshake>b__5>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at CoreWCF.Channels.Framing.DuplexFramingMiddleware.OnConnectedAsync(FramingConnection connection)
>    at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection)
>    at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()

On the client app:

> Unhandled exception. System.ServiceModel.Security.SecurityNegotiationException: Authentication failed, see inner exception.
>  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
>  ---> System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database).
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
>    at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)
>    at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
>    at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.NegotiateStream.BeginAuthenticateAsClient(NetworkCredential credential, ChannelBinding binding, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel, AsyncCallback asyncCallback, Object asyncState)
>    at System.Net.Security.NegotiateStream.BeginAuthenticateAsClient(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel, AsyncCallback asyncCallback, Object asyncState)
>    at System.Net.Security.NegotiateStream.<>c__DisplayClass27_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
>    at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
>    at System.Net.Security.NegotiateStream.AuthenticateAsClientAsync(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel)
>    at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream, OutWrapper`1 remoteSecurity)
>    --- End of inner exception stack trace ---
>    at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream, OutWrapper`1 remoteSecurity)
>    at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgradeAsync(Stream stream)
>    at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgradeAsync(StreamUpgradeInitiator upgradeInitiator, OutWrapper`1 connectionWrapper, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeSpan timeout)
>    at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreambleAsync(IConnection connection, ArraySegment`1 preamble, TimeSpan timeout)
>    at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnectionAsync(TimeSpan timeout)
>    at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpenAsync(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
>    at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
>    at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
>    at System.Runtime.TaskHelpers.CallActionAsync[TArg](Action`1 action, TArg argument)
>    at System.ServiceModel.Channels.CommunicationObject.OpenOtherAsync(ICommunicationObject other, TimeSpan timeout)
>    at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
>    at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
>    at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
>    at System.ServiceModel.Channels.CommunicationObject.Open()
>    at System.ServiceModel.Channels.ServiceChannelProxy.System.ServiceModel.ICommunicationObject.Open()
>    at TestMail.Program.Main(String[] args) in D:\Denexy.LogExpert\TestMail\Program.cs:line 20
>

**Comment by mconnew** [comment]
Have you configured your Linux system to be joined to the Windows domain?

**Comment by Alex-MT-Denexy** [comment]
No, I don't need to join Windows domain, and also don't need authentication.

**Comment by ludwhe** [comment]
I've had success dealing with that by seeing SecurityMode.None explicitly on client and server when instantiating NetTcpBinding, maybe that could work for you too?

**Comment by Alex-MT-Denexy** [comment]
Oh yes, it works! I tried to set SecurityMode.None on server, but forgot do it on client )
Thank you, ludwhe!

**Comment by sinistram** [comment]
@Alex-MT-Denexy can you please provide your code with usages. 
As I can see CoreWCF has no public ChannelFactory class. So how can you create the object?

**Comment by Alex-MT-Denexy** [comment]
@sinistram, sorry, I have deleted this code, because we decided not to use CoreWCF in our project at this time

**Comment by mconnew** [comment]
@sinistram, the client classes can be found in the System.ServiceModel.XXXX packages. For NetTcp you will need System.ServiceModel.Primitives and System.ServiceModel.NetTcp. The project for that can be found at https://github.com/dotnet/wcf
