### ISSUE TITLE
[Bug]: NullReferenceException when excluding primitive type parameters from SOAP request, starting in v1.5.1

### ISSUE THREAD

**Issue by wallis** [CoreWCF/CoreWCF#1382]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.1

### Summary
In a SOAP request, when not providing a parameter of a primitive, non nullable type (int, bool, etc), the service should receive the default value for that type (0, false, etc). This is how it worked up to, and including version 1.4.2.

### Repro steps:
1. Set up the template project, with the latest version of CoreWCF:
`dotnet new --install CoreWCF.Templates `
`dotnet new corewcf --name MyService`
2. Include exception details by adding attribute to the `Service` class: `[ServiceBehavior(IncludeExceptionDetailInFaults = true)]`
3. Run the service, and add the wsdl to SoapUI or a similar client
4. Call GetData, but remove the element for the value parameter

### Expected result: 
The service should receive `0` for the `value` parameter that was not provided:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <GetDataResponse xmlns="http://tempuri.org/">
         <GetDataResult>You entered: 0</GetDataResult>
      </GetDataResponse>
   </s:Body>
</s:Envelope>
```

### Additional information:
Changing the CoreWCF Version to 1.4.2 shows the previous behaviour:
```
  <ItemGroup>
    <PackageReference Include="CoreWCF.Primitives" Version="1.4.2" />
    <PackageReference Include="CoreWCF.Http" Version="1.4.2" />
  </ItemGroup>
  ```

### Describe actual behavior

From v1.5.1, this results in a 500 Internal Server Error because of a NullReferenceException in CoreWCF. See stack trace below.

### Which binding

BasicHttp

### security

Transport

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
var builder = WebApplication.CreateBuilder();

builder.Services.AddServiceModelServices();
builder.Services.AddServiceModelMetadata();
builder.Services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();

var app = builder.Build();

app.UseServiceModel(serviceBuilder =>
{
    serviceBuilder.AddService<Service>();
    serviceBuilder.AddServiceEndpoint<Service, IService>(new BasicHttpBinding(BasicHttpSecurityMode.Transport), "/Service.svc");
    var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    serviceMetadataBehavior.HttpsGetEnabled = true;
});

app.Run();

// Then call GetData from a SOAP client without providing an xml element for the `value` parameter.
```

### Stacktrace if any

```shell
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <s:Fault>
         <faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:InternalServiceFault</faultcode>
         <faultstring xml:lang="en-AU">Object reference not set to an instance of an object.</faultstring>
         <detail>
            <ExceptionDetail xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
               <HelpLink i:nil="true"/>
               <InnerException i:nil="true"/>
               <Message>Object reference not set to an instance of an object.</Message>
               <StackTrace>at lambda_method13(Closure , Object , Object[] , Object[] )
   at CoreWCF.Dispatcher.SyncMethodInvoker.InvokeAsync(Object instance, Object[] inputs)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.&lt;>c__DisplayClass71_0.&lt;&lt;InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.ImmutableDispatchRuntime.ProcessMessageAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.MessageRpc.ProcessAsync(Boolean isOperationContextSet)</StackTrace>
               <Type>System.NullReferenceException</Type>
            </ExceptionDetail>
         </detail>
      </s:Fault>
   </s:Body>
</s:Envelope>
```

**Comment by g7ed6e** [comment]
@wallis Thanks for reporting issue. The issue seems related to the new ˋIOperationInvoker`. To unblock you, you can set the app context switch ˋ CoreWCF.Dispatcher.UseLegacyInvokeDelegate` to true to switch back to the previous implementation.
cc @mconnew

**Comment by wallis** [comment]
Thank you for the quick reply, @g7ed6e! The app context switch workaround works fine for now. Looking forward to the permanent fix!

**Comment by g7ed6e** [comment]
@mconnew is this really a bug ? Should we support this ?

**Comment by mconnew** [comment]
@g7ed6e , we should match whatever the behavior of .NET framework is. I suspect it is a bug as if we expect the value to be there and it isn't, we would return a fault message earlier than get,  It would be in the formatter code where we deserialize values.

**Comment by mconnew** [comment]
I'm the blocker on this. I have a few more changes to review before releasing the next version which contains the fix.
