### ISSUE TITLE
[Bug]: WCF server throws error when receives request

### ISSUE THREAD

**Issue by SealySealy** [CoreWCF/CoreWCF#1446]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.2

### Describe expected behavior

I expected for the wcf function to work.

### Describe actual behavior

i got an error on the wcf server. see stack trace.

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 7

### Which os platform

Windows

### Stacktrace if any

```shell
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'System.String CoreWCF.Channels.RemoteEndpointMessageProperty.get_Name()'.
         at CoreWCF.Channels.HttpRequestContext.AspNetCoreHttpContext.AspNetCoreHttpInput.AddProperties(Message message)         at CoreWCF.Channels.HttpInput.ProcessHttpAddressing(Message message)
         at CoreWCF.Channels.HttpInput.ParseIncomingMessageAsync()
         at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context)
         at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
         at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
         at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by SealySealy** [comment]
I figured what the issue was. 
CoreWCF.Http version was 1.5.2
but
CoreWCF.Primitives was 1.6 so when i downgraded this to 1.5.2 it worked after.

**Comment by couperyork** [comment]
Hi @SealySealy, 

I also experienced this issue, the `CoreWCF.Templates` adds 1.* to the package references and a package in a project was subsequently updated to 1.6 from 1.5.2, although, I cannot see this 1.6 version now in Nuget.
![image](https://github.com/user-attachments/assets/904f9806-0a5e-4402-966e-3cc770975c2f)

Hey @g7ed6e
Was the change that possibly introduced this issue in the following [commit](https://github.com/CoreWCF/CoreWCF/commit/8f91599c47b94213307046519a400d6f5393a46b) of yours?

specifically in the `src/CoreWCF.Primitives/src/CoreWCF/Channels/RemoteEndpointMessageProperty.cs` ?

Would this cause an incompatibility if some of the solution was using 1.5.* and others using 1.6 ? It might pay to get the CoreWCF.Templates updated to not insert 1.* if that is the case.

I also have some client code running `System.ServiceModel.Primitives` 4.10.3 in a .NET Standard 2.0 project, assuming this isn't relevant to the error at hand though.

**Comment by mconnew** [comment]
This is mentioned in the release notes for 1.6.0. We changed the Name properties of the Message Property classes to `public const string Name` from `public static string Name { get; }` so they can be used in attribute property values. This isn't binary compatible, but won't break compilation. The compatibility bar between releases is that we might break binary compatibility (but avoid as much as possible), but your app should recompile with the latest version without code changes.
