### ISSUE TITLE
Is there any window available for the release of CoreWcf

### ISSUE THREAD

**Issue by dgxhubbard** [CoreWCF/CoreWCF#154]
I have not been able to find if there is any window on the release of CoreWcf.
I know this is a volunteer project. Any information provided would be helpful.
Sorry for posting here could not find information anywhere.

**Comment by mconnew** [comment]
We're nearly at the point of releasing a pre-release to github. I need to wire up the public signing certificate through Azure DevOps and create a build pipeline to publish to nuget. We've also got a heap of new tests that have been ported from the internal Microsoft WCF test suite that I need to go through and resolve any issue from. I would hope to have a pre-release available in the next month or so.  
I will say that there is more than one internal team inside of Microsoft already using CoreWCF in production so the stability is pretty good. The gap to get to a v1 release is feature completeness and not stability. Having said that, you should do your own load testing to check for stability and performance.  
Once we have a pre-release package available, I'll be switching to stress and performance testing comparing it with WCF on .NET Framework.

**Comment by dgxhubbard** [comment]
Thank you @mconnew. I am especially glad CoreWCF is being used internally also.
You guys have done a great job and its appreciated.

**Comment by mconnew** [comment]
GA release will be in new year, currently planned for late January.

**Comment by dgxhubbard** [comment]
Thank you that is much appreciated!
