### ISSUE TITLE
Update dependencies to latest

### ISSUE THREAD

**Issue by mconnew** [CoreWCF/CoreWCF#178]
Package dependencies need to be updated to the latest versions supported on .NET Standard 2.0.
Any ASP.NET Core packages must NOT be updated beyond 2.1.x but should be the latest within the 2.1.x versions.

**Comment by danielcrenna** [comment]
@mconnew Just curious what the rationale is for pinning to .NET Core 2.1.x, vs. multi-targeting on later releases?

**Comment by mconnew** [comment]
It's not pinned to .NET Core 2.1.x, only ASP.NET Core 2.1.x. You can run ASP.NET Core 2.1.x on .NET Core 3.1 just fine. The reason is that ASP.NET Core 2.1.x is still supported on .NET Framework. When I first started this port as an internal prototype in Microsoft, I had strong feedback from multiple teams that being able to run a CoreWCF service on .NET Framework was really important. It's not a good idea to do a big bang port of a large service to .NET Core where you are making changes blind and hope you haven't introduced any bugs along the way. So by targeting the first release on ASP.NET Core 2.1.x, you can leave your service implementation and dependencies mostly the same (might need a namespace change in a using). So you can switch over to CoreWCF and keep running on .NET Framework as a first step. As this is mostly an issue for large apps, you are going to generally have multiple assemblies making up your app. So then you start working on making each app assembly work on netstandard2.0. You can keep running the service in production as you progressively make everything compatible with netstandard2.0. Once you have everything compatible so it will run on .NET Core you can just flip the switch. After the first RTM release, the next version will move to the latest LTS ASP.NET Core.
