### ISSUE TITLE
Performance for NetTcpBinding?

### ISSUE THREAD

**Issue by OhSoGood** [CoreWCF/CoreWCF#183]
In a [recent discussion](https://github.com/CoreWCF/CoreWCF/issues/154), @mconnew was writing that "Once we have a pre-release package available, I'll be switching to stress and performance testing comparing it with WCF on .NET Framework.".

I'm using WCF server with Security= none (but that may change), InstanceContextMode.Single, ConcurrencyMode.Multiple, platform will be both Linux (Debian) and Windows 10. I'm going of course to test CoreWCF but I wonder what I can expect from it.

Has anybody some tips about the performance of CoreWCF versus WCF for NetTcpinding?  In my context, shall I expect performance to be more or less close to WCF globally ?

Thank you for any feedback, and thanks a lot to the dev team for their time and effort.

**Comment by mconnew** [comment]
We've done some preliminary perf testing. I can't remember which was faster but they were the same order of magnitude. There wasn't much difference between them.

**Comment by OhSoGood** [comment]
Thanks!
