### ISSUE TITLE
TCP sockets

### ISSUE THREAD

**Issue by nicostubi** [CoreWCF/CoreWCF#184]
Hello,

any plans to support XML over TCP, sent via sockets (and not web sockets)?

BR
Nico

**Comment by mconnew** [comment]
Are you talking about NetTcp? SOAP requires some kind of message framing. With HTTP, the SOAP message is framed by the HTTP request. With WebSockets, it's framed by a WebSocket message. WCF supports the proprietary (but documented and open) NetTcp standard which has a compact framing mechanism to separate each SOAP message.  
If this isn't what you were thinking of, can you elaborate further?

**Comment by nicostubi** [comment]
I am talking about TCP. Not Http :-) no SOAP.

I have to implement an old protocol based on socket connections.

**Comment by davidfowl** [comment]
If you're just trying to implement a custom TCP protocol you don't need WCF for that.
