### ISSUE TITLE
Address in "To" attribute of CoreWCF request header is inaccurate

### ISSUE THREAD

**Issue by zjrobinzj** [CoreWCF/CoreWCF#201]
We are calling the CoreWCF service via address “https://abc.trafficmanager.net:3089/xxx/yyy”. But I noticed that the address in “To” attribute of CoreWCF request header is inaccurate, which is always showing “http://localhost/xxx/yyy” without port. 

The ideall correct address should be like below, which is also what legacy WCF does:
1.	Start with “https”
2.	Domain name should be the same with incoming request  like ”abc.trafficmanager.net”
3.	Port should be 3089 like what client calls

**Comment by birojnayak** [comment]
working on it
