### ISSUE TITLE
Issue in ServiceKnownTypes with inheritance

### ISSUE THREAD

**Issue by madhurigambhir** [CoreWCF/CoreWCF#203]
A WCF operation is configured to return a base object and it is marked it to know the derived object with ServiceKnownType attribute. If we returned the derived object from the implementation of the operation, the response is aborted prematurely in Core WCF, while it works fine in Net framework. 
To make it work I put the KnownType attribute on the base object.

**Comment by birojnayak** [comment]
Can you re-try using the latest package from https://www.nuget.org/profiles/corewcf and see if this is fixed ?

**Comment by mconnew** [comment]
@madhurigambhir, can you verify and reopen if this is still an issue.
