### ISSUE TITLE
AddService and AddServiceEndpoint without generic parameters

### ISSUE THREAD

**Issue by FreeAndNil** [CoreWCF/CoreWCF#204]
For porting my WCF-Service I need new overloads for AddService & AddServiceEndpoint:

`public void AddService(Type service)`
`public void AddServiceEndpoint(Type service, Type implementedContract, Binding binding, Uri address, Uri listenUri)`

The service application is a generic host and depending on the configuration (in a database) different endpoints must be created (the types are loaded by name via reflection).
I can add the method and create a pull request, just want to confirm that this would be the right way.

**Comment by mconnew** [comment]
Thank you. This just makes sense, I think I got too generic happy by not including them to begin with 🤣
