### ISSUE TITLE
Net TCP Windows Group test experiences intermittent failure on build server

### ISSUE THREAD

**Issue by danielcrenna** [CoreWCF/CoreWCF#217]
Builds fail tests intermittently when running test `CoreWCF.NetTcp.Tests.ServiceAuthBehaviorTest.SimpleNetTcpClientConnectionUseWindowsGroups`:

`System.IO.IOException : Received an unexpected EOF or 0 bytes from the transport stream.`

Details available at this pipeline run log: https://dev.azure.com/dotnet/CoreWCF/_build/results?buildId=37963&view=logs&j=553e699c-c90d-524e-494d-c063e6fbd5aa&t=0762c354-6297-5fb7-c841-4fc5040f272b

**Comment by danielcrenna** [comment]
This is fixed in PR #215

**Comment by mconnew** [comment]
I think this was fixed but I need to double check before closing.

**Comment by mconnew** [comment]
This failing test was fixed in an earlier commit. It was a race condition on connection reuse.
