### ISSUE TITLE
Intermittent `AddressInUseException` for nettcp false test failure on during CI/CD process

### ISSUE THREAD

**Issue by danielcrenna** [CoreWCF/CoreWCF#218]
Builds often fail intermittently due to an `AddressInUseException` preventing Kestrel from starting.

Example log: https://dev.azure.com/dotnet/CoreWCF/_build/results?buildId=37970&view=logs&j=df77fcc7-169b-539a-4b1a-0702f867ecad&t=5eb216d8-81f4-5458-f745-21d97554dbca

**Comment by mconnew** [comment]
This is fixed now
