### ISSUE TITLE
CoreWCF.XmlSerializerFormat Is Not Accessible

### ISSUE THREAD

**Issue by ashkanparsa** [CoreWCF/CoreWCF#237]
I'm trying to use **CoreWCF.XmlSerializerFormat** but seems it's not accessible form the package. I can see it's in **CoreWCF.Primitives**. Do you know if it's a conflict on **CoreWCF.Http** and **CoreWCF.Primitives**?

![image](https://user-images.githubusercontent.com/16793642/95506410-b7cd5980-0964-11eb-8904-3ac0b305d5da.png)

**Comment by birojnayak** [comment]
I could use though as below. XmlSerializerFormat is only exposed from CoreWCF.Primitives as far as I see in the code.
Are you getting CoreWCF from NUGET https://www.nuget.org/packages/CoreWCF.Http , https://www.nuget.org/packages/CoreWCF.Primitives ? See if this helps, else let us know

using CoreWCF;
using System.Runtime.Serialization;

namespace Contract
{
    [XmlSerializerFormat]
    [ServiceContract]
    public interface IEchoService
    {
.......

**Comment by ashkanparsa** [comment]
By using version 0.1.0-alpha.209 the issue is resolved.
