### ISSUE TITLE
Support for HTML page from .svc path

### ISSUE THREAD

**Issue by Treit** [CoreWCF/CoreWCF#247]
Somewhat related to the lack of WSDL support (see https://github.com/CoreWCF/CoreWCF/issues/95).

In traditional WCF services, at least those hosted in IIS, performing an HTTP GET of the ".svc" path by itself would return an HTML page with some information about the service, such as an example of passing the WSDL path to svcutil.exe to generate a client, and some code snippets showing how to instantiate the client.

Here is an example for a publicly documented service from Microsoft:
https://bulk.api.sandbox.bingads.microsoft.com/Api/Advertiser/CampaignManagement/v13/BulkService.svc

We have existing customers who rely on this page being available; tooling they use to generate a client apparently uses this .svc path as a starting point. Moving to CoreWCF, we don't have a good way to generate this HTML response.

It would be very helpful if CoreWCF had a way to generate these pages as well.

**Comment by mconnew** [comment]
Do you need the same content? Or would you prefer some health check info there instead? It would be good to port[ this functionality](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.description.servicehealthbehavior?view=netframework-4.8) across as well so having some configurable subset of that data might be worth putting on the default service page as a health status page that customer can use to verify that the service is live and healthy. That feature enable changing the HTTP status code based on service health.

**Comment by Treit** [comment]
@mconnew For compatibility with existing tools, we would need the content to be identical. We have tools (like our Java SDK) that take the .svc URL as input and produce a client that can then be used to call the service based on the content that is returned.

**Comment by mconnew** [comment]
Closing in preference of #270 which tracks multiple features that have been asked for which are provided by ServiceMetadataBehavior.
