### ISSUE TITLE
Add StrongName 

### ISSUE THREAD

**Issue by Danielku15** [CoreWCF/CoreWCF#264]
Many applications and other libraries in the market still use Strong Names, so do we for our products (historically). All CoreWCF packages currently are not signed with any solution key and therefore do not have a strong name. 

In order to support smooth migration for any products still requiring strong names, it would be great if also CoreWCF would add it. 

Please note I am requesting this purely for compatibility with products/libraries which cannot simply remove the SNK due to again transitive dependencies expecting it. So basically the first point of ["Why strong-name your assemblies"](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named) 

> You want to enable your assemblies to be referenced by strong-named assemblies, or you want to give friend access to your assemblies from other strong-named assemblies.

**Comment by mconnew** [comment]
That constraint is only enforced when running on .NET Framework. In .NET Core/.NET 5, an assembly can be strong names and reference a non-strong named assembly. With this in mind, is this still something you need?

**Comment by Danielku15** [comment]
Yes. Unfortunately we are forced to stick still to .net 4.8. We have a rather long product roadmap to finally hop to .net core / .net 5 where we need to adapt a lot of changes (ASP.net -> ASP.net core, EF -> EF core, WCF -> CoreWCF/Rest/gRPC). This migration needs to be done for multiple services, libraries and products. 

Having a strong name on CoreWCF would allow as a more step-wise transition/migration of our products.

**Comment by mconnew** [comment]
Do you need a full strong-name signed assembly or is public signed an option? Public signed assemblies basically have the public key in the assembly to use as part of their identity but the assembly is missing the actual signature. So the assembly load binding process can validate the identity of the assembly, but there's no actual signature. It makes creating a private build and dropping it in place to test something locally easier and it's the method used by .NET Core OOB packages. There are 3 scenarios it doesn't work for, you can read more info [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md#:~:text=NET%20Core%20projects%20build%20using%20public%20signing.%20Public,context%20that%20doesn%27t%20require%20validating%20the%20strong-name%20signature.).

**Comment by Daniel-Svensson** [comment]
Just a quick question: are there any drawbacks with using normal strong singing and publishing the snk in the repo so anyone can use it?

I think that was the recommendation a while back and it should have the mentioned advantages of public signed.

**Comment by mconnew** [comment]
I miss-read the article I linked to. I thought .NET Core was public signing, but it looks like they strong name sign and suggest public signing as a way to create privately built assemblies when the private key isn't available. I'll make sure they are strong name signed before the the stable GA release.

**Comment by mconnew** [comment]
I just realized I didn't answer your question. no problem with publishing the snk file in the repo as it doesn't provide any security, only identification.

**Comment by Danielku15** [comment]
It's hard to tell if public signing would be sufficient from the explaination in the article. My main requirement is that I am able to use CoreWCF from other libraries and applications (.net48) which are fully strong signed without getting any errors on build or runtime. If public signing is sufficient I would need to try out with some test assemblies. 

As you already wrote I also noticed that .net core is fully strong named.  Same applies for the asp.net core and ef core libs.

**Comment by mconnew** [comment]
@Danielku15, I've made it strong name signed. Do you need the packages in nuget or is the azure devops feed okay?
