### ISSUE TITLE
InstanceContext's Host property is internal

### ISSUE THREAD

**Issue by schovan** [CoreWCF/CoreWCF#271]
`System.ServiceModel.InstanceContext` class has a _public_ property `Host`.
`CoreWCF.InstanceContext` has also a `Host` property, but it is _internal_.
Why? How do I access information about host?
I can use reflection to access this property, but it doesn't look good.

**Comment by mconnew** [comment]
This is in the latest build so closing. Feel free to reopen if there's any problems with this property.
