### ISSUE TITLE
When will the  release packages come out?

### ISSUE THREAD

**Issue by china-lu** [CoreWCF/CoreWCF#274]
When will the  release packages come out? we want to use WCF in a production environment.

**Comment by mconnew** [comment]
The first release should hopefully be by the end of this month. It won't have a 1.0 version number as there's some fundamental features still missing such as WSDL support.

**Comment by g7ed6e** [comment]
I've read the release note and undestood that some features like wsdl generation are not implemented yet.

Is the 0.1.0 production ready for BasicHttpBinding simple scenario hosted in IIS with .NET Core 3.1 runtime (assuming the fix described here #313 is implemented in the application) ?

**Comment by mconnew** [comment]
Closing this issue as the v1.0 release packages are available on nuget.org
