### ISSUE TITLE
When is first release CoreWCF?

### ISSUE THREAD

**Issue by rchalco** [CoreWCF/CoreWCF#275]
Hi, it's a great job you are doing rebuilding wcf for .Net Foundation 5; I would like know if the first release will be only like Nuget, or will a new template be added to Visual Studio to carry out WCF library-type projects?
Thanks.

**Comment by mconnew** [comment]
The current plan is to release the first GA version by the end of this month.  

This isn't a Microsoft owned project so it won't be getting built in to VS. It would be great to create some dotnet new style templates which can then be used from within VS. [Here's the docs ](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates)on creating a template pack, and here's how you [enable using them in VS](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/).

**Comment by china-lu** [comment]
> the first release will be only like Nuget

> The current plan is to release the first GA version by the end of this month.
> 
> This isn't a Microsoft owned project so it won't be getting built in to VS. It would be great to create some dotnet new style templates which can then be used from within VS. [Here's the docs ](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates)on creating a template pack, and here's how you [enable using them in VS](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/).

ok,thank you for your reply.

**Comment by mconnew** [comment]
Closing as first release is now available.
