### ISSUE TITLE
Question : .Net core migration of windows service wrapping a WCF service

### ISSUE THREAD

**Issue by vvijayalakshmi21** [CoreWCF/CoreWCF#316]
I've a WCF service wrapped by a windows service. It has been hosted in IIS. We are currently looking to migrate to .Net core from .net framework 4.6

Please can someone let me know if this is possible through core WCF?
If yes, is the code production ready? 
If not, is there an alternative to achieve what we currently have?

Still trying to learn .net core migration. Would be really helpful if you could help.

**Comment by john-e-lewis** [comment]
I'm doing something similar. Migrating  from WCF console app hosted in a windows service (4.6.2) to Dot net core aspnetcore and kestel on windows and linux.

It depends on what features from WCF your current product is is using.  For me its come down to finding out which Bindings are supported in CoreWCF and what transport is supported. I've got very close to completion but currently stumped by netccp not supporting TransportWithMessageCredentials in GA 0.1.0.

Also CoreWCF doesnt yet support WCF xml configuration so you need to use aspnetcore settings or something similar to configure your service.

Apart from that the core migration and transition to CoreWCF went very smoothly. 

Migrating from 4.6.2 to Core for server side libraries isnt too bad.  There is a bit of learning curve, I followed the best practice guidelines in https://docs.microsoft.com/en-us/dotnet/core/porting/

**Comment by mconnew** [comment]
@john-e-lewis answered this pretty well. I'm closing the issue. If there's any followup questions, please feel free to reopen.
