### ISSUE TITLE
NetTcp and Duplex Channel

### ISSUE THREAD

**Issue by MemoTrap** [CoreWCF/CoreWCF#318]
CoreWCF 0.1.0

I tried a little example with NetTcp binding and a callback channel, based on:
https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/duplex-services.

It crashes in the CoreWCF based server, throwing InvalidCast, but works fine in classic .Net Framework.
```
    ICalculatorDuplexCallback Callback {
      get {
        return OperationContext.Current.GetCallbackChannel<ICalculatorDuplexCallback> ();
      }
    }
```
`System.InvalidCastException: 'Unable to cast object of type 'CoreWCF.Channels.ServiceChannel' to type 'CalculatorCommon.ICalculatorDuplexCallback'.'`

Same effect with both clients, Core or Framework.

Is there anything I have to do differently for CoreWCF?

The entire sample is here:
[CalculatorDuplex.zip](https://github.com/CoreWCF/CoreWCF/files/6048651/CalculatorDuplex.zip)

_On a sideline:_
All operation contracts are one way, as in the original example. The client first calls the "add" method, then "subtract". 
```
      var factory = new
                    DuplexChannelFactory<ICalculatorDuplex> (context, binding, address);
      ICalculatorDuplex channel = factory.CreateChannel ();

      channel.AddTo (1234);
      channel.SubtractFrom (123);
```
However, on the CoreWCF server, "subtract" is invoked first.

**Comment by mconnew** [comment]
This has been merged and will be released as part of 0.3.0

**Comment by jaubin333** [comment]
> I would be happy to contribute a duplex channel example once working.

Were you ever able to get a working duplex example? I'd love to grab it and take a look.

**Comment by jaubin333** [comment]
> Never mind. The problem was invoking the GetCurrentCallbackChannel with the service interface rather than the callback interface.

@CloudwatcherGit  Can you show what, exactly, you fixed? I am new to this and looking to use this CalculatorDuplex project as a sample and I am seeing the same invalid cast exception but unsure where you made the tweak to fix it. Thanks!
