### ISSUE TITLE
TimeoutException making call to net.tcp duplex service

### ISSUE THREAD

**Issue by bjornhellander** [CoreWCF/CoreWCF#323]
Hi!

I modified your samples to have a duplex service using net.tcp in https://github.com/bjornhellander/CoreWCF/commit/3e15852a3b77011c7566f1dad367a016336a6e4f.

Running desktop or core client together with desktop server:
Works.

Running desktop or core client together with core server:
Fails with a timeout exception on the call to Echo() in the clients. Never reaches the service implementation.

Have a made any mistakes here or should this work?

**Comment by MemoTrap** [comment]
Make the outgoing OperationContract "one way", too, and you may arrive at #318, like me.

**Comment by mconnew** [comment]
Duplex support isn't working yet.

**Comment by mconnew** [comment]
This will be tracked in #318 so closing this issue
