### ISSUE TITLE
CoreWCF.ClientBase<T> error

### ISSUE THREAD

**Issue by AndreasEike** [CoreWCF/CoreWCF#327]
Hello,

I've generated a .cs class from a wcf service using svcutil, and I am trying to get it to work in .NET 5.0. I am using CoreWCF because the generated app.config file is not supported in .NET 5.0, so I found CoreWCF through googling and it seemed like the solution. I have replaced instances of "System.ServiceModel" with "CoreWCF" in the .cs file, like so:

Before:
![image](https://user-images.githubusercontent.com/46325452/111373288-00b7d580-869c-11eb-9a1a-774b840790a0.png)

After:
![image](https://user-images.githubusercontent.com/46325452/111373469-2fce4700-869c-11eb-80e0-8bae9606b9e4.png)

The last errors seems to come from CoreWCF.ClientBase, which does not seem to be included in the CoreWCF namespace.
![image](https://user-images.githubusercontent.com/46325452/111373579-5ab89b00-869c-11eb-8659-182fbdd2b4b1.png)

From what I've read, changing System.ServiceModel to CoreWCF was the only requirement, but is there something else I'm missing here? Could anyone help with this.

**Comment by ssa3512** [comment]
I think you are looking for https://github.com/dotnet/wcf - the client level packages for .NET Core/.NET 5 still live in the System.ServiceModel namespace. These need to be installed via nuget as they aren't part of the core framework anymore.

HTTP: https://www.nuget.org/packages/System.ServiceModel.Http/
net.tcp: https://www.nuget.org/packages/System.ServiceModel.NetTcp/

**Comment by AndreasEike** [comment]
Okay, I forgot to add I have also tried this with dotnet-svcutil, but I am getting an error when generating the .cs file. I've posted an issue over there: https://github.com/dotnet/wcf/issues/4566 

Because this didn't work, I came to CoreWCF to look for a solution.

**Comment by mconnew** [comment]
CoreWCF is only the server side of things. It doesn't contain a client implementation. Closing this issue as the dotnet/wcf repo is the correct place to get help.
