### ISSUE TITLE
When using app.UsePathBase(pathbase) endpoint address does not match

### ISSUE THREAD

**Issue by shaofing** [CoreWCF/CoreWCF#328]
```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            string PathBase = "/SCM.Cloud.WCFService";
            app.UsePathBase(PathBase);
            app.UseServiceModel(builder =>
            {
                builder
                    .AddService<SystemInfoService>()
                    .AddServiceEndpoint<SystemInfoService, ISystemInfoService>(new BasicHttpBinding(), "/basichttp3") ;// Can not mattch http://localhost:30005/SCM.Cloud.WCFService/basichttp3
            });
        }
```

I know that the VirtualDirectory of IIS used ”app.UsePathBase“

I used https://github.com/CoreWCF/CoreWCF/issues/313#issuecomment-782387998    hotst in IIS under ASP.NET Core 3.1

I used  v0.1.0

**Comment by mconnew** [comment]
Can you try with the latest development release that's available from the nuget feed listed in the main readme? I made some changes to better support base paths and I believe that should fix it. If that doesn't fix this, let me know and I'll take another look.

**Comment by mconnew** [comment]
@shaofing, closing as I believe this is fixed. If this is still a problem, please reopen the issue.
