### ISSUE TITLE
Contract attributes that are defined in both CoreWCF and System.ServiceModel namespaces

### ISSUE THREAD

**Issue by WenningQiu** [CoreWCF/CoreWCF#332]
The fact that attributes (ServiceContractAttribute, OperationAttribute, MessageContractAttribute etc.) that are used to define contracts are defined in both CoreWCF and System.ServiceModel namespaces makes it hard to define service contracts that can be referenced by both the service side code (implementation service) and the client side code - the client side code must reference the SystemServiceModel namespace while the service side code must reference the CoreWCF namespace. The inconvenience is reflected by the example programs provided in CoreWCFWithSamples.sln having to define the service contract separately for the client and the service programs.

Would it be possible for CoreWCF to just use the attributes defined in System.ServiceModel namespace?

**Comment by WenningQiu** [comment]
It appears to be a duplicate of https://github.com/CoreWCF/CoreWCF/issues/31

**Comment by mconnew** [comment]
@WenningQiu, I added support to recognize System.ServiceModel contract attributes a while ago. I added support via reflection so there's no requirement to pull in the client System.ServiceModel.* packages. The CoreWCF ones still exist so you don't need to add a reference to the client packages to get the attributes and can have a minimal set of dependencies if that's what's best for your application. Closing this issue as I think your problem has already been solved. Feel free to reopen if you have any further questions.
