### ISSUE TITLE
Adding custom MessageEncoder

### ISSUE THREAD

**Issue by WenningQiu** [CoreWCF/CoreWCF#344]
We have legacy applications that use custom message encoder which is added through BindingContext.BindingParameters. The code below shows the gist of the approach.

```
internal sealed class CountingMessageEncodingBindingElement : System.ServiceModel.Channels.MessageEncodingBindingElement
{
        public override IChannelListener<TChannel> BuildChannelListener<TChannel>(BindingContext context)
        {
            context.ThrowIfNull(nameof(context));

            context.BindingParameters.Add(this);
            return context.BuildInnerChannelListener<TChannel>();
        }
}
```

We found that the custom message encoder is not invoked when porting the applications to CoreWCF. CoreWCF BindingContext has removed BuildChannelListener() virtual method. Modifying BindingContext.BindingParameters in the overridden MessageEncodingBindingElement.GetProperty<T>(BindingContext) method does not help, perhaps due to timing.

I am looking for advice/suggestion about how to properly customize MessageEncoder with CoreWCF.

**Comment by mconnew** [comment]
The concept of a ChannelListener is gone and it's not IServiceDispatcher and IServiceChannelDispatcher. You probably want to do this:
```
internal sealed class CountingMessageEncodingBindingElement : System.ServiceModel.Channels.MessageEncodingBindingElement
{
        public override IServiceDispatcher BuildServiceDispatcher<TChannel>(BindingContext context, IServiceDispatcher innerDispatcher)
        {
            context.ThrowIfNull(nameof(context));

            context.BindingParameters.Add(this);
            return context.BuildNextServiceDispatcher<TChannel>(innerDispatcher);
        }
}
```
I'm not sure of your use case, but you might not need to do that now. On .NET Framework, TransportChannelListener would get the [MessageEncodingBindingElement from the BindingParameters](https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/Channels/TransportChannelListener.cs#L72). In CoreWCF, there isn't a base TransportChannelListener for all the transports to derive from so there isn't common code for handling this. Each transport has to do this work itself. I just checked and I don't pull the MessageEncodingBindingElement from the binding parameters. Both HTTP and NetTcp both do something along these lines:
```c#
            BindingElementCollection be = dispatcher.Binding.CreateBindingElements();
            MessageEncodingBindingElement mebe = be.Find<MessageEncodingBindingElement>();
            MessageEncoderFactory mefact = mebe.CreateMessageEncoderFactory();
```
So just having the MessageEncodingBindingElement in your Binding should be sufficient. This is a regression in behavior compared with .NET Framework. Personally I think the requirement to add the MessageEncodingBindingElement to the binding parameters is a bit odd. The only use case I can see is where a custom binding element wants to override the message encoder, but if someone is doing that, then I think providing a full Binding class which adds the correct message encoding binding element in the first place is a less obscure approach, or even a helper method which returns a CustomBinding which replaces the MessageEncodingBindingElement and adds anything else needed would be better.  

I couldn't find any code which actually called GetProperty to try and retrieve this, so I don't believe CoreWCF depends on this behavior. If you find there's a scenario where providing it this way is needed, let me know and I can make it do the original behavior.

**Comment by mconnew** [comment]
If you have any follow up questions, please reopen the issue.
