### ISSUE TITLE
Add support for MessageParameterAttribute

### ISSUE THREAD

**Issue by mconnew** [CoreWCF/CoreWCF#345]
This is currently internal. We have support for understanding System.ServiceModel.MessageXXXXXXXAttribute attributes in CoreWCF, but this one was missed. The actions needed are:
- [x] Make MessageParameterAttribute public
- [x] Add tests for MessageParameterAttribute
- [x] Add compat code to support S.SM namespaced version of attribute
- [x] Add tests for S.SM namespaced version of attribute

This issue was opened based on #339

**Comment by g7ed6e** [comment]
@mconnew could you provide links for the 2 latter tasks ?
