### ISSUE TITLE
System.ServiceModel.Security.SecurityNegotiationException: 'Could not establish trust relationship for the SSL/TLS secure 

### ISSUE THREAD

**Issue by padhumailin** [CoreWCF/CoreWCF#370]
I have tried creating sample application from 
https://github.com/CoreWCF/CoreWCF/tree/main/src/Samples/NetCoreServer
https://github.com/CoreWCF/CoreWCF/tree/main/src/Samples/NetCoreClient

in client application, im getting this error. how to fix this
System.ServiceModel.Security.SecurityNegotiationException: 'Could not establish trust relationship for the SSL/TLS secure channel with authority '127.0.0.1:8443'.'

**Comment by JohnLeyva** [comment]
@padhumailin, please review if the  script can help you to setup SSL for the samples

https://github.com/CoreWCF/CoreWCF/blob/main/src/Samples/gencert.ps1

**Comment by padhumailin** [comment]
Thanks! It worked
