### ISSUE TITLE
Dose CoreWCF support to use svcutil.exe to generate proxy?

### ISSUE THREAD

**Issue by yuqi1207** [CoreWCF/CoreWCF#373]
Dose CoreWCF support to use svcutil.exe to generate proxy? We try to use this way to generate proxy but failed. If not supported, any alternatives?

**Comment by mconnew** [comment]
svcutil requires the service to be publishing a WSDL. The issue to track this work is #270 so I'm closing this issue as a duplicate. If you have any more questions, please add them to the other issue.
