### ISSUE TITLE
Add compatibility code for System.ServiceModel.XmlSerializerFormatAttribute

### ISSUE THREAD

**Issue by mconnew** [CoreWCF/CoreWCF#378]
The reason we don't directly support this attribute is to avoid referencing the System.ServiceModel.Primitives buget package and pulling in the entire WCF client code. We currently have compatibility code using reflection to convert some attributes in the System.ServiceModel namespace to the equivalent ones in the CoreWCF namespace.

_Originally posted by @mconnew in https://github.com/CoreWCF/CoreWCF/discussions/372#discussioncomment-980582_

**Comment by mconnew** [comment]
If anyone wants to work on this, let me know and I can point you to the existing compatibility code for other attributes and give guidance on the best place to add equivalent code.

**Comment by JohnLeyva** [comment]
@mconnew, I can give it a try

**Comment by JohnLeyva** [comment]
@mconnew, please let me know what code is good to start looking at and any other guidance you consider convenient

**Comment by g7ed6e** [comment]
Hi i wrote compat code and unit/integration tests that check behavior is identical whereas SSM or CoreWCF XmlSerializerFormatAttribute is used either at ServiceContract or OperationContract level. It looks good to me.
