### ISSUE TITLE
ChannelFactory

### ISSUE THREAD

**Issue by D0ctorWh0** [CoreWCF/CoreWCF#379]
I am trying to migrate my wcf client from nrt framework. I used ChannelFactory to build channel. But i cant find ChannelFactory in CoreWCF and cant use Channel factory from System.ServiceModel,because it needs System.ServiceModel.EndpointAddress, not CoreWCF.EndpointAddress.

**Comment by g7ed6e** [comment]
Hi AFAIK CoreWCF aims to offer a migration path towards dotnet core to WCF server side code. For client side code SSM is already netstandard2.0.

**Comment by mconnew** [comment]
@D0ctorWh0, as @g7ed6e mentioned, everything you need should be available in the System.ServiceModel.* packages in nuget. If there's any features missing, the repro to report that is https://github.com/dotnet/wcf
