### ISSUE TITLE
Http and Tcp samples have different behavior

### ISSUE THREAD

**Issue by Treit** [CoreWCF/CoreWCF#39]
### Problem
When running the provided sample projects, there is a difference in behavior between the service running over TCP and the service running over HTTP. The HTTP service is constructed on every call whereas the TCP instance is re-used after being constructed for the first time.

### Steps to repro:
1. Clone the following branch which has a minimal repro of the issue: https://github.com/Treit/CoreWCF/tree/dev/mtreit/HttpVsTcpRepro
2. Run `dotnet build` from the src folder
3. Run `start dotnet ..\bin\NetCoreServer\netcoreapp2.2\NetCoreServer.dll`
4. Run `start dotnet ..\bin\NetCoreClient\netcoreapp2.2\NetCoreClient.dll`
5. In the client window that opens, type some text and press enter. Repeat several times.

### Expected Result:
The behavior of the TCP and HTTP versions of the service is the same.

### Actual Result:
You will see that the behavior is different. The TCP version of the service increments it's member variable `receivedCount` on each call, whereas the value remains stuck forever at 1 for the HTTP version of the service. 

### Notes:
The difference in behavior is because the HTTP version of the service is re-constructed anew on each call, whereas with the TCP version the instance is re-used after the first call.

The output from the service if you send the string 'abc' to it twice is as follows:

> EchoService constructed.
Received abc from client! Received so far: 1
EchoService constructed.
Received abc from client! Received so far: 1
Received abc from client! Received so far: 2
EchoService constructed.
Received abc from client! Received so far: 1

Debugging shows that the HTTP version is constructed anew on each call, as indicated by the 'EchoService constructed' output: on the first call both the TCP and HTTP instances were constructed (as expected) but after that the TCP instance was re-used and the HTTP instance was constructed again.

It's not clear if this is just an issue with how the sample services is coded or a more fundamental bug, but I would think that the transport protocol used in the samples should not cause such a difference in behavior (i.e., the HTTP instance is essentially stateless and the TCP instance is stateful.)

**Comment by mconnew** [comment]
The default InstanceContextMode is PerSession. As TCP has a transport session, you get a service instance per client. As HTTP doesn't have any session, each call is like a new session so you get a new instance for every call. This is the same behavior as .NET Framework and is by design.
