### ISSUE TITLE
RemoteEndpointMessageProperty broken for NetTcp @ net5.0

### ISSUE THREAD

**Issue by Danielku15** [CoreWCF/CoreWCF#409]
It seems there were some changes in the ASP.net core connection handling and Kestrel as part of net5.0 which break the access to the remote address of requests. 

**Situation Before**
In v2.x the `Microsoft.AspNetCore.Connections.ConnectionContext` did not expose any local or remote endpoints. The feature collection contained always an `IHttpConnectionFeature` which could be used for accessing the endpoint. The CoreWCF FramingConnection goes with this assumption an decodes the endpoint accordingly: 
https://github.com/CoreWCF/CoreWCF/blob/e16e5e5e8763c9d04f9de943b12a4804a27c0d86/src/CoreWCF.NetTcp/src/CoreWCF/Channels/Framing/FramingConnection.cs#L70-L80

**Situation in net5.0**
In net5.0 the ConnectionContext does **not** have an `IHttpConnectionFeature` anymore. Instead the `ConnectionContext` inherits from `BaseConnectionContext` and this base class exposes the endpoints accordingly: 

The property is defined here: 
https://github.com/dotnet/aspnetcore/blob/c663adee8e64ba5d379fa0edfb8201984a7df7d0/src/Servers/Connections.Abstractions/src/BaseConnectionContext.cs#L43
And filled here by Kestrel (`SocketConnection` extends `TransportConnection` extends `ConnectionContext`): 
https://github.com/dotnet/aspnetcore/blob/952ccb4532cc6287ca49b91992b2912144d4d752/src/Servers/Kestrel/Transport.Sockets/src/Internal/SocketConnection.cs#L57

This is currently blocking us of using CoreWCF because we are transitioning to net5.0.

**Comment by BradBarnich** [comment]
yeah, that is exactly what we had to do for our fork. 

https://github.com/BradBarnich/CoreWCF/commit/84beb95d27d1ddd2446134d2aabed2fdf98f3c73#diff-eb51e6bd23bdf452be456eb85805a2a7fa60a61518708d91ba56d7b213d39c7aL53-R53

**Comment by mconnew** [comment]
We can't do what @BradBarnich did as we still reference the 2.1 api's. The solution is to make the property an auto property then call a remote endpoint init method in the constructor. In that constructor, attempt to create the IPEndpoint the current way, and if that doesn't work, use reflection to get the RemoteEndPoint property to populate the auto property.  
Would either @Danielku15 or @BradBarnich be able to submit a PR with this change?  

As an aside, @BradBarnich, in an ideal world you would be able to use the official release. If there are problems or limitations you are facing which you can write a work around, it would be great to incorporate them into the main project. We're moving to a faster release cycle now, we got slowed down by a really big feature being developed which touched a lot of areas, but that should be the last one of that size.

@birojnayak, can you review any potential PR's?

**Comment by BradBarnich** [comment]
@mconnew would you be open to multitargeting net5.0?
