### ISSUE TITLE
ServiceEndpoint Address

### ISSUE THREAD

**Issue by tapizquent** [CoreWCF/CoreWCF#414]
I had a doubt regarding the base address for an endpoint when setting with `builder.AddServiceEndpoint`.

Usually, in most examples, the endpoint is added as:
`builder.AddServiceEndpoint<MyService, IMyService>(new BasicHttpBinding(), "/basic");`

My question is, how is the address inferred? Is it from the host or is there any place where it should be specified?
What will be the final endpoint? `http://hostname:port/basic`?

**Comment by birojnayak** [comment]
refer here https://github.com/CoreWCF/CoreWCF/blob/main/src/Samples/NetCoreServer/Program.cs#L19 ... yes you are right... http://localhost:port/basic .... if you have a domain you could use urls like UseUrls("http://yourmachine.domain.name:8080", "https://yourmachine.domain.name:8000") .... feel free to open if you need more clarifications
