### ISSUE TITLE
Set up multiple services with IServiceBuilder

### ISSUE THREAD

**Issue by tapizquent** [CoreWCF/CoreWCF#428]
Is it possible to add multiple services with the IServiceBuilder?

That is, implement something like the following

`builder.AddService<Service1>();`
`builder.AddServiceEndpoint<Service1, IService1>(new BasicHttpBinding(), "/service1");`
`builder.AddService<Service2>();`
`builder.AddServiceEndpoint<Service2, IService2>(new BasicHttpBinding(), "/service2");`

**Comment by mconnew** [comment]
I designed it to do so, but haven't actually tested it. The implementation does a foreach over the service type to initialize it. There's a few rough edges around doing that, such as dependency injection of IServiceBehavior implementations has no way to configure a behavior to only be for a particular service. I have some ideas how to do that, but as nobody has asked, I haven't implemented them yet.  

So give it a try and let me know if you have any problems with doing so. If it doesn't work, I'll do my best to get it working as soon as possible.

**Comment by mconnew** [comment]
Keeping open as we need to add tests for this scenario and fix any problems that arise. Marking as help wanted for the test writing aspect. You wouldn't be required to fix any problems discovered if not comfortable with that.

**Comment by BradBarnich** [comment]
this is what we are doing, and it seems to work well?
```
sb.AddService<ApplicationManager>();
sb.AddServiceEndpoint<ApplicationManager, IApplicationManager>(
    HttpEndpointFactory.CreateCoreWCFBinding( SecurityMode.Transport, HttpClientCredentialType.None ),
    "/ApplicationManagerService" );
sb.ConfigureServiceHostBase<ApplicationManager>( serviceHost =>
{
    new StandardServiceHostConfiguration().Configure( serviceHost );
} );

sb.AddService<Adapter.LocalDataService.LocalDataService>();
sb.AddServiceEndpoint<Adapter.LocalDataService.LocalDataService, ILocalData>(
    HttpEndpointFactory.CreateCoreWCFBinding( SecurityMode.Transport, HttpClientCredentialType.Certificate ),
    "/LocalDataService" );
sb.ConfigureServiceHostBase<Adapter.LocalDataService.LocalDataService>( serviceHost =>
{
    new StandardServiceHostConfiguration().Configure( serviceHost );
    new SecureServiceHostConfiguration().Configure( serviceHost );
    new UserContextServiceHostConfiguration().Configure( serviceHost );
} );
```

**Comment by mconnew** [comment]
I'm glad that's working. I wrote everything for it to work that way, just hadn't written any validating tests. BTW, you can simplify your code a little by doing this:
```c#
sb.AddService<ApplicationManager>();
sb.AddServiceEndpoint<ApplicationManager, IApplicationManager>(
    HttpEndpointFactory.CreateCoreWCFBinding( SecurityMode.Transport, HttpClientCredentialType.None ),
    "/ApplicationManagerService" );
sb.ConfigureServiceHostBase<ApplicationManager>(new StandardServiceHostConfiguration().Configure);

sb.AddService<Adapter.LocalDataService.LocalDataService>();
sb.AddServiceEndpoint<Adapter.LocalDataService.LocalDataService, ILocalData>(
    HttpEndpointFactory.CreateCoreWCFBinding( SecurityMode.Transport, HttpClientCredentialType.Certificate ),
    "/LocalDataService" );
sb.ConfigureServiceHostBase<Adapter.LocalDataService.LocalDataService>(new StandardServiceHostConfiguration().Configure);
sb.ConfigureServiceHostBase<Adapter.LocalDataService.LocalDataService>(new SecureServiceHostConfiguration().Configure);
sb.ConfigureServiceHostBase<Adapter.LocalDataService.LocalDataService>(new UserContextServiceHostConfiguration().Configure);
```

If it's possible to make the Configure methods static, you don't need to instantiate an instance. You can just provide the method directly as a parameter as long as the signature matches.

**Comment by BradBarnich** [comment]
Thanks, I feel like I've been burned by other `.ConfigureXX`-like apis (not CoreWCF) that overwrite configuration instead of combine.

**Comment by jonlouie** [comment]
@mconnew Is this issue still available? Based on the conversation above, I have some ideas for testing this that I could contribute today or tomorrow.

**Comment by mconnew** [comment]
@jonlouie, contributing unit tests is a great way to help. I'm really busy working on the final pieces for a preview release so I won't be able to look at any PR's until maybe the end of the week, but probably not until next week. Feel free to mention me on your PR if it's ready around Tuesday of next week if I haven't got to it yet.

**Comment by jonlouie** [comment]
No problem- thank you for the quick reply and setting expectations. I'll publish the PR soon and follow up accordingly, thanks again!

**Comment by DarioSalcedo** [comment]
> esto es lo que estamos haciendo, ¿y parece funcionar bien?
> 
> ```
> sb.AddService<ApplicationManager>();
> sb.AddServiceEndpoint<ApplicationManager, IApplicationManager>(
>     HttpEndpointFactory.CreateCoreWCFBinding( SecurityMode.Transport, HttpClientCredentialType.None ),
>     "/ApplicationManagerService" );
> sb.ConfigureServiceHostBase<ApplicationManager>( serviceHost =>
> {
>     new StandardServiceHostConfiguration().Configure( serviceHost );
> } );
> 
> sb.AddService<Adapter.LocalDataService.LocalDataService>();
> sb.AddServiceEndpoint<Adapter.LocalDataService.LocalDataService, ILocalData>(
>     HttpEndpointFactory.CreateCoreWCFBinding( SecurityMode.Transport, HttpClientCredentialType.Certificate ),
>     "/LocalDataService" );
> sb.ConfigureServiceHostBase<Adapter.LocalDataService.LocalDataService>( serviceHost =>
> {
>     new StandardServiceHostConfiguration().Configure( serviceHost );
>     new SecureServiceHostConfiguration().Configure( serviceHost );
>     new UserContextServiceHostConfiguration().Configure( serviceHost );
> } );
> ```

Hi @BradBarnich, @mconnew, please, what would be wrong, in the Startup class two contracts are used. In Program Main, I put the following:
``` C#
     public void ConfigureServices(IServiceCollection services)
        {
            services.AddServiceModelServices();
        }
        public void Configure(IApplicationBuilder app)
        {
            NetTcpBinding netTcpBinding = new NetTcpBinding
            {
                TransferMode = TransferMode.Streamed
            };
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                netTcpBinding.Security.Mode = SecurityMode.None;
            else
            {
                netTcpBinding.Security.Mode = SecurityMode.Transport;
                netTcpBinding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Windows;
            }

            app.UseServiceModel(builder =>
            {
                builder.AddService<ServiceCaja>();
                builder.AddServiceEndpoint<ServiceCaja, Contracts.IServiceCaja>(netTcpBinding, "/ServiceCaja");

                builder.AddService<ServiceCategoria>();
                builder.AddServiceEndpoint<ServiceCategoria, Contracts.IServiceCategoria>(netTcpBinding, "/ServiceCategoria");
            });
        }
```
In Program:

``` C#
 static void Main(string[] args)
        {
            int port = 11808;
            IWebHost host = CreateWebHostBuilder<Startup>(IPAddress.Loopback, port).Build();
            host.Run();
        }
        
         public static IWebHostBuilder CreateWebHostBuilder<TStartup>(IPAddress? ipAddress = null, int port = 0) where TStartup : class
        {
            if (ipAddress == null)
                ipAddress = IPAddress.Loopback;

            IWebHostBuilder builder = WebHost.CreateDefaultBuilder(Array.Empty<string>())
                .UseNetTcp(ipAddress, port)
                .UseStartup<TStartup>();   
        }
```
In the Client solution, only the first call is recognized. Please, I humbly request your support :)

``` C#
 static void Main(string[] args)
        {
NetTcpBinding netTcpBinding = new NetTcpBinding
            {
                TransferMode = TransferMode.Streamed
            };

            int port = 11808;
            string expectedBaseAddress = $"net.tcp://{IPAddress.Loopback}:{port}";

            var factory = new System.ServiceModel.ChannelFactory<Horacio.Service.Contracts.IServiceCaja>(netTcpBinding,
                new System.ServiceModel.EndpointAddress(new Uri($"{expectedBaseAddress}/ServiceCaja")));
            var channel = factory.CreateChannel();
            var result = channel.ListarCajas(1);

ERROR HERE:

            var factory1 = new System.ServiceModel.ChannelFactory<Horacio.Service.Contracts.IServiceCategoria>(netTcpBinding,
                new System.ServiceModel.EndpointAddress(new Uri($"{expectedBaseAddress}/ServiceCategoria")));
            var channel1 = factory1.CreateChannel();
            var result1 = channel1.ListarCategorias(1);
```

System.ServiceModel.ProtocolException
  HResult=0x80131500
  Mensaje = Error al leer el formato de tramas de mensajes en la posición 411 de la secuencia (estado: EnvelopeEnd)
  Origen = System.Private.ServiceModel
  Seguimiento de la pila:
   en System.ServiceModel.Channels.SingletonConnectionReader.SingletonInputConnectionStream.ProcessEof()
   en System.ServiceModel.Channels.SingletonConnectionReader.SingletonInputConnectionStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   en System.ServiceModel.Channels.SingletonConnectionReader.SingletonInputConnectionStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   en System.IO.Stream.ReadByte()
   en System.ServiceModel.Channels.DelegatingStream.ReadByte()
   en System.ServiceModel.Channels.MaxMessageSizeStream.ReadByte()
   en System.Xml.XmlBufferReader.TryEnsureByte()
   en System.Xml.XmlBufferReader.get_EndOfFile()
   en System.Xml.XmlBinaryReader.ReadNode()
   en System.Xml.XmlBinaryReader.Read()
   en System.Xml.XmlBaseReader.ReadEndElement()
   en System.ServiceModel.Channels.Message.ReadFromBodyContentsToEnd(XmlDictionaryReader reader, EnvelopeVersion envelopeVersion)
   en System.ServiceModel.Channels.Message.ReadFromBodyContentsToEnd(XmlDictionaryReader reader)
   en System.ServiceModel.Channels.MessageFault.CreateFault(Message message, Int32 maxBufferSize)
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   en generatedProxy_2.ListarCategorias(Int16 )
   en Client.Program.Main(String[] args) en C:\Users\César\Desktop\Core WCF\CoreWCF\Client\Program.cs: línea 33

Excepción interna 1:
InvalidDataException: Se esperaban más datos pero se llegó al final del archivo.
