### ISSUE TITLE
Why is XmlSerializerFormatAttribute internal?

### ISSUE THREAD

**Issue by comburo** [CoreWCF/CoreWCF#43]
I have an existing WCF application that I have been looking to port to .NET Core for a while now. I am currently evaluating of this is feasible with this library, however the first thing I run into is the fact that XmlSerializerFormatAttribute is not supported?

The application I have needs to have this attribute in order to serialize the XML to conform to the existing standard. I already tried using the XmlSerializerFormatAttribute from System.ServiceModel.Primitives, but that does not work.
If I change the XmlSerializerFormatAttribute from internal to public (together with some enums to satisfy the compiler) it does exactly what I need, but I'm sure there is a reason why this attribute is not public.

**Comment by comburo** [comment]
I have a PR ready, but I need to sign the contribution waiver and I need to go through a whole process with my employer. I'm working on it.... :-(

**Comment by ashkanparsa** [comment]
@mconnew is there any release for this change?
