### ISSUE TITLE
What is the replacement of servicehost and GetAccessControl in CoreWCF and also .NET5.

### ISSUE THREAD

**Issue by isofttechnz** [CoreWCF/CoreWCF#432]
I am migration old WCF application  to .NET5. It is complaining about `servicehost` and `GetAccessControl` not supporting in .NET5. Could someone please provide some sample solution.

**Comment by mconnew** [comment]
WCF doesn't have any implementation of GetAccessControl, so I presume this is calling some other code in the framework. The only GetAccessControl I could find is related to CodeAccessSecurity (or CAS for short), which has been deprecated in .NET Core. You need to remove that code.  

There are multiple samples on how to use CoreWCF available [here.](https://github.com/CoreWCF/CoreWCF/tree/main/src/Samples/NetCoreServer) CoreWCF is built on top of ASP.NET Core so you need to create an ASP.NET Core service and add CoreWCF to it.

**Comment by mconnew** [comment]
Closed as I believe the linked samples will help you get started. Feel free to reopen if you need more help, or open a new issue if you have a specific issue.
