### ISSUE TITLE
Does .Net framework WCF server compatible to CoreWcf client? 

### ISSUE THREAD

**Issue by amarendra-k** [CoreWCF/CoreWCF#454]
Following is the configuration,
Server    -WCF  (.Net framework) 
Client     -  Core WCF

If not how to make it work?

**Comment by g7ed6e** [comment]
Hello @amarendra-k CoreWCF aims to migrate the server WCF code to .net core. Regarding client side WCF code in dotnet core app you should be able to use `System.ServiceModel.*` nuget packages that actually are netstandard2.0.

**Comment by mconnew** [comment]
@amarendra-k, the client project is https://github.com/dotnet/wcf so if you have any problems with the client, that's the correct place to open issues. 

Closing as this isn't about CoreWCF.
