### ISSUE TITLE
Introduce dependency injection of services from a custom parameter attribute in Service implementation

### ISSUE THREAD

**Issue by g7ed6e** [CoreWCF/CoreWCF#480]
Introduce a parameter attribute allowing to inject services from DI directly in Service implementation similar to  ASP.NET Core `[FromServices]` attribute.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fromservicesattribute?view=aspnetcore-5.0

```c#
[ServiceContract]
public interface IService
{
    [OperationContract]
    Task<Customer> GetCustomerAsync(int customerId, [Injected]DbContext dbContext);
}
```

This would mean the customer ID comes in as part of the service call, and CoreWCF will fetch from the InstanceContext scoped ServiceProvider the dbContext and add it as a parameter. What are your thoughts?

_Originally posted by @mconnew in https://github.com/CoreWCF/CoreWCF/issues/473#issuecomment-949130495_

**Comment by g7ed6e** [comment]
I'm starting to work on the source generator / analyzer option. It should be interesting.
@mconnew How would you want to distribute the source generator and the analyzer. Should both of them be distributed with `CoreWCF.Primitives` nuget package ?

**Comment by mconnew** [comment]
Yes, they should be distributed in the CoreWCF.Primitives package. As it's a build time tool, it won't increase the application footprint at runtime. It will need to be a separate project which is referenced by the Primitives build but won't produce its own package.
