### ISSUE TITLE
ImpersonationOption.Required does not work in wsHttpBinding

### ISSUE THREAD

**Issue by vladascibulskis** [CoreWCF/CoreWCF#486]
I'm trying to set   ` [CoreWCF.OperationBehavior(Impersonation = CoreWCF.ImpersonationOption.Required)]` attribute on one of the WCF service method.
I'm using wsHttpBinding set up as follows:
```
            var binding = new WSHttpBinding();
            binding.Security.Mode = SecurityMode.Transport;
            binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
```

Getting following error:

> 10:46:21 ERR] First chance exception occured
> System.InvalidOperationException: SecurityContextProperty is missing from the request Message, this may indicate security is configured incorrectly.
>    at CoreWCF.Dispatcher.SecurityImpersonationBehavior.RunImpersonated2[T](MessageRpc rpc, ServiceSecurityContext securityContext, Boolean isSecurityContextImpersonationOn, Func`1 func) in D:\Odesk\Eddie\Radian_TFS\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Dispatcher\SecurityImpersonationBehavior.cs:line 226
> 

I might be doing something wrong, but client works with other service created on .Net Framework, but does not work with CoreWCF (.Net Core 5).

Attached is a patch with unit test that reproduces same issue.

[0001-486-Unit-test.zip](https://github.com/CoreWCF/CoreWCF/files/7441929/0001-486-Unit-test.zip)

**Comment by mconnew** [comment]
Notes for when this is addressed. The fix is to retrieve the WindowsIdentity from ASP.NET Core and create a ServiceSecurityContext to add to the incoming message which holds the WindowsIdentity. So we need code in the HTTP middleware which does this when security mode is transport and the credential type is Windows.

**Comment by jonlouie** [comment]
@birojnayak I'm interested in helping with this

**Comment by birojnayak** [comment]
@jonlouie assigning to you

**Comment by birojnayak** [comment]
@mconnew can you assign.. I can't assign to @jonlouie

**Comment by mconnew** [comment]
@birojnayak, it looks like you assigning it to Jon was successful.
