### ISSUE TITLE
nettcp sample missing

### ISSUE THREAD

**Issue by kasajian** [CoreWCF/CoreWCF#491]
Looks like the included samples are only for HTTP.  Are there any examples for nettcp

**Comment by FreeAndNil** [comment]
see
https://github.com/CoreWCF/CoreWCF/blob/main/src/Samples/StandardClient/ClientLogic.cs
https://github.com/CoreWCF/CoreWCF/blob/main/src/Samples/DesktopServer/Program.cs

**Comment by mconnew** [comment]
@kasajian, as @FreeAndNil has linked to the samples for NetTcp, it looks like your question has been answered so I'm going to close this issue. If you have more questions, feel free to reopen.
