### ISSUE TITLE
Improve DI validation using IServiceProviderIsService

### ISSUE THREAD

**Issue by mconnew** [CoreWCF/CoreWCF#505]
There's a new interface in .NET 6 platform extensions called [IServiceProviderIsService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.iserviceproviderisservice?view=dotnet-plat-ext-6.0) that is able to interrogate DI and tell you whether a type is available via DI. This would greatly simplify the logic at startup to see if the type is in DI or if the legacy WCF instance creation code should be used instead. This does require the nuget package Microsoft.Extensions.DependencyInjection version 6.0.0+, but that won't add a requirement on .NET 6 as it has assets for netstandard2.0. The risk of adding this is promoting dependencies in an application for this package or one of its dependencies. There's a reasonable chance that this package is already directly referenced in an app at a lower version which would then cause a runtime break in CoreWCF as direct dependency versions override transitive dependencies. I'm conflicted whether we should do this before the v2.0 timeframe when we move dependency to require .NET 6 as it doesn't enable new scenarios, but improves the developer experience when making a mistake in DI and it seems counter to the intention to introduce a potential bad developer experience in the case of accidental package downgrade.  

For InstanceContextMode.Single, we currently attempt to get an instance from DI, and if we get an instance, need to pass it around as we can't guarantee that the type was registered as a Singleton in DI and we need to avoid allocating an extra instance. For PerCall and PerSession, we have to defer checking DI until the first service call. The reason being that the type might have dependencies which are scope registered, or might need access to the HttpContext on instantiation. This leads us to have an implementation of an instance provider where we have an initial delegate which tries to get the instance from DI, and if it can, replaces the delegate with another delegate which gets the instance from DI in the future, otherwise it replaces the delegate with one which uses the legacy WCF approach for instantiating new instances.  

The end result of this is that if the type doesn't have a default constructor and isn't in DI, there's an exception thrown in a call stack which isn't easily discoverable by developers and makes things difficult to debug.  

The solution is to use IServiceProviderIsService.IsService to check if type is in DI at service start time. This allows simplifying the instance context provider and we can go back to 2 separate implementations, DI only, and legacy WCF only. It also makes the exception thrown at startup instead of on first request. This still has one failure case which would only be discovered at first request which is where a type is in DI but it's dependencies can't be satisfied, but it's still an improvement from where things are.  

This also will help improve validation when using CoreWCF without specifying a concrete implementation as was implemented in PR #468.

**Comment by g7ed6e** [comment]
@mconnew  what do you think about adding a roslyn analyzer that probe the existence of the new API in referenced assemblies 
using the semantic model and then report an appropriate diagnostic, either a build break or just a warning.

**Comment by mconnew** [comment]
@g7ed6e, I think that's overkill for what's needed. Nuget allows you to inject a props and a targets file into a project. If we want to trigger a build time failure, we can add a target which checks for the Microsoft.Extensions.DependencyInjection package in the resolved package references and fails the build if it isn't at least 6.0.  
Although that seems like a lot of work for a potential point in time problem. I'm tending to agree with @Kralizek that this is just deferred until we introduce a .NET 6 dependency which should hopefully be in the first few months of 2022.

**Comment by himanshuz2** [comment]
I am looking forward to easier validation and debugging.
