### ISSUE TITLE
Dataset Serialization with column type GUID

### ISSUE THREAD

**Issue by absinghal** [CoreWCF/CoreWCF#519]
When serializing a dataset that has table with column type GUID, xml like following is generated

```
<xs:element name="RLSId" msdata:DataType="System.Guid, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" type="xs:string" minOccurs="0"/>
```

This fails to deserialize on the NETFX 472 client side, probably because there is no System.Private.CoreLib, Version=6.0.0.0 over there.

Any workarounds ?

**Comment by mconnew** [comment]
Unfortunately there's nothing that can be done in CoreWCF. You could potentially write a data contract surrogate, but I'm not sure how much work that would be for you. Ultimately it's down to an individual class to ensure it's serializable in a backwards compatible way if the class is intended to be serialized. This is an issue with how Dataset is serialized, it embeds the fully qualified assembly name into the output. Beyond the suggestions of using a surrogate, there's not anything else we can do. I suggest opening an issue in the dotnet/runtime repo about this.
