### ISSUE TITLE
ServiceContract inheritance results in ArgumentException (Duplicate dictionay key)

### ISSUE THREAD

**Issue by marlon-tucker** [CoreWCF/CoreWCF#537]
Hello,

Our existing WCF codebase has an external API and an internal API. The internal API inherits from the external API to provide some additional operational contracts.

Converting this architecture to CoreWCF has resulted in an ArgumentException being raised from the following code block when adding to the dictionary. 

https://github.com/CoreWCF/CoreWCF/blob/c370e8661bb25018e7631bb33a47ee7bf465a4a6/src/CoreWCF.Primitives/src/CoreWCF/ServiceHostObjectModel.cs#L151-L164

This appears to be because the reflection code is finding both `CoreWCF.ServiceContract` attributes in the inheritance chain, when it aught to be only selecting one defined on the given contract type. 

I've checked and the contract it has for the correct type has all the operations it should have, including the ones from the inheritance chain, so that bit is working correctly. 

It's strange as the `Inherited` flag for the `CoreWCF.ServiceContract` `AttributeUsage` is set to false, so it shouldn't be visible when reflecting over the given contract type.

**Comment by mconnew** [comment]
Can you give an example of how your contracts look? It doesn't need to be your real contract, just have similar properties. For example, if both contracts have a method with the same name, or same name and parameters, do the same in the example. Basically, I'm looking for a trivial contract which fails in the same way. There's too many ambiguities in your description for me to narrow down the scenario. I don't need a full app, just two interfaces which when used exhibit the same problem.

**Comment by marlon-tucker** [comment]
Sure no problem.

```
    public class Test : IDiscoveryServiceChild
    {
        public Task<string> GetEnvironmentAsync()
        {
            throw new NotImplementedException();
        }

        public Task<DateTime> GetUtcSystemTimeAsync()
        {
            throw new NotImplementedException();
        }
    }

    [CoreWCF.ServiceContract(ConfigurationName = "IDiscoveryService")]
    public interface IDiscoveryServiceParent
    {
        /// <summary>
        /// Gets the name of the environment that the discovery service is running in.
        /// </summary>
        /// <returns>The name of the environment.</returns>
        [CoreWCF.OperationContract(Action = "http://tempuri.org/IDiscoveryService/GetEnvironment", ReplyAction = "http://tempuri.org/IDiscoveryService/GetEnvironmentResponse")]
        Task<string> GetEnvironmentAsync();
    }

    [CoreWCF.ServiceContract(ConfigurationName = "IDiscoveryService")]
    public interface IDiscoveryServiceChild : IDiscoveryServiceParent
    {
        /// <summary>
        /// Gets the system time.
        /// </summary>
        /// <returns></returns>
        [CoreWCF.OperationContract(Action = "http://tempuri.org/IDiscoveryService/GetSystemTime", ReplyAction = "http://tempuri.org/IDiscoveryService/GetSystemTimeResponse")]
        Task<DateTime> GetUtcSystemTimeAsync();
    }
```

```
app.UseServiceModel(smb =>
{
    smb.AddService<Test>().AddServiceEndpoint<Test, IDiscoveryServiceChild>(new BasicHttpBinding(), "/Test.svc");
});
```

Exception occurs when `app.Run()` is executed.

**Comment by marlon-tucker** [comment]
Upon more digging it seems (as usually is the case) I am incorrect. The issue stems from using `ConfigurationName` instead of `Name` in the `ServiceContract` attributes. Swapping those over fixed the duplicate key error so I'm going to close this issue.

IIRC the old .NET Service Client generator created the interfaces I was working from, hence the confusion.
