### ISSUE TITLE
[Visual Studio] Project Templates for CoreWCF

### ISSUE THREAD

**Issue by samsp-msft** [CoreWCF/CoreWCF#541]
There is a bit of a chicken and egg issue with templates, but the net story as of this moment is that templates installed via `dotnet new install <package.id>` will show up in VS once they are installed. Instructions for creating templates are at https://github.com/sayedihashimi/template-sample.

* CoreWCF should have a nuget package with project & item templates in it.
* Those templates can then have references to the other CoreWCF nuget packages as required.
* Users will be able to install then using something like `dotnet new install CoreWCF.Templates`
* Those templates will then show up in Visual Studio for the Project New dialog, and will be usable from cmd line and VS code.

**Comment by birojnayak** [comment]
this is something we have been discussing since last year, will be a great addition

**Comment by g7ed6e** [comment]
@mconnew please assign to me

**Comment by samsp-msft** [comment]
@g7ed6e - I'm not sure if the issue need to be assigned to stake a claim - submit a PR to get the ball rolling.
 
It would be good to have both classic and minimal API style templates - the latter are much simpler but require .NET 6.
