### ISSUE TITLE
Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by absinghal** [CoreWCF/CoreWCF#549]
Getting the following error when hosting on IIS
```
Connection ID "17942340938529506164", Request ID "80000375-0005-f900-b63f-84710c7967bb": An unhandled exception was thrown by the application.

Exception: 
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at CoreWCF.ServiceHostObjectModel`1.FixUri(String address)
   at CoreWCF.ServiceHostObjectModel`1.ApplyConfiguration()
   at CoreWCF.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection baseAddresses)
   at CoreWCF.ServiceHostObjectModel`1..ctor(IServiceProvider serviceProvider, ServiceBuilder serviceBuilder, ILogger`1 logger)
```

I am using a IIS site binding with hostname as follows
`*.edu.qa.appsnirvana.com`

I believe error is coming from [this](https://github.com/CoreWCF/CoreWCF/blob/c370e8661bb25018e7631bb33a47ee7bf465a4a6/src/CoreWCF.Primitives/src/CoreWCF/ServiceHostObjectModel.cs#L259) line of code 

Uri constructor does not recognize *.

As a workaround, we can skip addresses with wildcard.

**Comment by absinghal** [comment]
This [place](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Description/ConfigLoader.cs,864076fde0291b1d,references) looks like the relevant piece of code for WCF on .NET

**Comment by mconnew** [comment]
@absinghal, thanks, that saved me some work to find the relevant code. It looks like it just replaces the * with your local machine hostname. So if your server has the hostname of foo, it will use `foo.edu.qa.appsnirvana.com`. The reality is we don't support specifying the `HostnameComparisonMode` on the binding which is where this would have much effect. The default behavior in WCF (and the only behavior in CoreWCF) is that we only care about the path. If the request gets routed to CoreWCF we presume the request is meant for us (path still must match though) and we don't really care what the hostname is. If you do care about the hostname, then you can add middleware before CoreWCF to reject requests with the wrong hostname. The hostname becomes slightly more important for things like WSDL support when we populate the hostname in the address part of the endpoint, or on the help page. But that can all be overridden anyway if things aren't matching up correctly. Let me know if putting the hostname in place of the asterisk is a solution which works for you. This should be easy enough to apply.

**Comment by absinghal** [comment]
@mconnew I dont care about the hostname, I just want no exception to be thrown up if IIS has a binding with * in hostname.

Yes I agree that sometimes there could be a situation when the wildcard binding is the only binding on IIS (I had other bindings as well so ignoring the * binding worked for me), so the .NET/WCF approach is more generic.

I can amend the FixUri method to handle this case in line with the .NET/WCF code - Pl confirm. 
(Yes can pick up dev build for some time).

**Comment by mconnew** [comment]
@absinghal, would you be able to push a PR to implement this fix? If not, that's okay and I'll get to it before the 1.0 release.

**Comment by absinghal** [comment]
Created PR https://github.com/CoreWCF/CoreWCF/pull/570

**Comment by mconnew** [comment]
Closing as PR has been merged
