### ISSUE TITLE
`attributeType` checked twice against `MessageBodyMemberAttribute`

### ISSUE THREAD

**Issue by jnyrup** [CoreWCF/CoreWCF#558]
`attributeType` is checked against `MessageBodyMemberAttribute` on both line 60 and 68.
https://github.com/CoreWCF/CoreWCF/blob/73ac30239b8f8eaea5af23d09c8e8d4405ee86b7/src/CoreWCF.Primitives/src/CoreWCF/Description/CustomAttributeProvider.cs#L60-L75

As the second branch uses `ServiceReflector.SMMessagePropertyAttributeFullName` I guess the second statement should have used `MessagePropertyAttribute` instead.

**Comment by jnyrup** [comment]
Sure, but I'm unsure how test it since `MessagePropertyAttribute` is `internal`.

**Comment by mconnew** [comment]
@jnyrup, could you take a look at my PR and sanity check my code to make sure I didn't mess anything up? I added tests so I've got high confidence in my fix.
