### ISSUE TITLE
Use Dependency injection to provide instance for all InstanceContextMode's

### ISSUE THREAD

**Issue by schovan** [CoreWCF/CoreWCF#56]
I need to inject a depency to a service. How do I do that? The service only supports parameterless constructor.

**Comment by Kralizek** [comment]
Not sure how it's translated into CoreWCF, but by default WCF supports only parameterless constructors. You can use an `InstanceProvider` to hook into the pipeline and provide your own service factory.

[Here](https://github.com/emgdev/dotnet-utils/tree/master/src/ServiceModel/ServiceModel/DependencyInjection) you can see how we use `IServiceProvider` to support dependency injection in our WCF services.

**Comment by mconnew** [comment]
@schovan, CoreWCF supports obtaining a singleton instance via dependency injection. I think there might still be code to ensure that there's a default constructor on the service class left over from the code being ported from .NET Framework but if there is I can remove that. For now you will need to temporarily add a dummy default constructor to satisfy the existing code. But that should stop you from using DI. This means the normal DI mechanism isn't going to work as it will pick the default constructor to create the instance. But you can use the factory DI pattern. Something like this:
```
    services.AddSingleton(typeof(MessageService), (serviceProvider) =>
    {
        var arg1 = serviceProvider.GetService(typeof(Foo));
        var arg2 = serviceProvider.GetService(typeof(Bar));
        return new MessageService(arg1, arg2);
    }
```
If you need to a new instance for each channel/call, then you will need to use something similar to what @Kralizek linked to for now wrapping the DI capability inside an implementation of IInstanceContextProvider. It would definitely be nice to make CoreWCF use DI for PerXXXX instance context mode too. It's not something I had thought of beyond Singleton. I'll definitely add that.  
I'm editing the title of this bug to describe using DI for all InstanceContextMode variations. And this bug will be used to track that.

**Comment by schovan** [comment]
@mconnew It works and my service doesn't need a default constructor. I didn't know that CoreWCF takes service instances from the _service provider_, I thought service instances are created by the _new_ operator.

**Comment by mconnew** [comment]
WCF on .NET Framework does use the new operator. I'm trying to modernize CoreWCF to take advantage of the new things in ASP.NET Core. I'll still leave this open as I think it only works for singleton services and I need to get it working for all instance context modes, with tests.

**Comment by schovan** [comment]
@mconnew How do make a service that has ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession)? I can't implement my DependencyInjection ServiceHost and InstanceProvider, because I can't use ServiceHost as a base class from this library. ServiceHost doesn't exist.

**Comment by mconnew** [comment]
You don't need to derive ServiceHost to use ServiceBehavior. Can you describe how you are doing things today and I'll tell you how to do that now with CoreWCF.

**Comment by schovan** [comment]
now I have got this
`            app.UseServiceModel(
                builder =>
                {
                    builder.AddService<MessageService>();
                    builder.AddServiceEndpoint<MessageService, IMessageService>(new BasicHttpBinding(), "MessageService");
                });`
and this
`             services.AddSingleton<IMessageService, MessageService>();`
`MessageService` is `InstanceContextMode.Single`

I wanna change `MessageService `to Scoped and `InstanceContextMode `to `PerCall `or `PerSession`

**Comment by mconnew** [comment]
You don't add an implementation of the service contract to DI, CoreWCF is looking for the concrete type for the service. Conceptually the service maps to the concrete type and the endpoint maps to the interface type as you can have multiple interfaces/endpoints on a single service type. So you need the following code for the injection:  
```c#
  services.AddTransient<MessageService>();
```
Or you could use a factory pattern if you want to customize it:
```c#
  services.AddTransient<MessageService>((provider) => 
      { 
          var service = new MessageService();
          // Modify MessageService instance however you like, maybe add logging etc.
          return service;
      });
```
Using AddTransient means a new instance is created every time one is created. Using AddScoped means when a new scope is created, a new instance will be created for that scope, but any more instances requested for the same scope will provide the same instance. It's like a scope level singleton.
 
To configure the instance context mode, the easiest way is to add the `ServiceBehavior` attribute to you class. So you would modify your service implementation like this:
```c#
  [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall)]
  public class MessageService : IMessageService
  {
      public MessageService() { } // Default constructor
      // All your implementation methods for IMessageService
  }
```
The default value for InstanceContextMode is PerSession so if you need PerSession, you don't need to specify it at all. Also, if you are okay with MessageService being instantiated by newing it using the default constructor, you don't need to inject it at all. I misspoke earlier about CoreWCF not newing and instance, if you don't inject your service instance, CoreWCF will new up an instance for you. You only need to inject it if you don't have a default constructor and require the constructor parameters to be filled in using DI.

So basically I suspect you could get away with skipping using DI at all and simply remove the InstanceContextMode from the ServiceBehavior attribute.

It would be really nice to get rid of the InstanceContextMode enum and property at some future point as you could easily map the concept of AddSingleton to InstanceContextMode.Single, AddScoped to InstanceContextMode.PerSession (creating a new scope for each session), and AddTransient to InstanceContextMode.PerCall. But I don't want to introduce too many paradigm changes all at once and cause confusion. Also I'm unsure about the performance costs of creating a new scope as technically HTTP based transports (except WSHttpBinding) effectively establish a new session for every request. That's cheap right now, but I suspect will become expensive if I use the scoped DI mechanism. I would need to prototype it and compare performance.

**Comment by schovan** [comment]
@mconnew Nice explanation! I thought I messed it up adding interface to service registration:
services.AddSingleton<`IMessageService`, MessageService>();
But your solution doesn't work. Transient works. But Scoped doesn't.
When I use this:
`services.AddScoped<MessageService>();` (this or factory pattern)
I get:
_System.InvalidOperationException: 'Cannot resolve scoped service 'ServerLayer.Infrastructure.MessageService' from root provider.'_
I also noticed that the Scoped MessageService is resolved after application starts (too early), not on WCF call.

**Comment by mconnew** [comment]
Maybe I didn't make it clear. The simple answer is don't use ever use Scoped with CoreWCF. You can use Transient for all modes, including Single and it will do the right thing. You can also use Singleton when using Single mode as they are compatible but you don't need to. As CoreWCF only requests the one instance for Single, adding it as a Singleton works fine too but Transient will work fine for Single too.  

You can use Transient for all modes as CoreWCF manages the lifetime/reuse of objects provided by DI. When you use PerSession, even though you add it as Transient, CoreWCF will only request one instance per session. To make it work with Scoped, CoreWCF would need to ask for it every time and depend on DI controlling the reuse. That's quite a lot of change required, and it would cause confusing behavior if DI and InstanceContextMode were configured in conflicting ways. You can still have some confusion today if you add it to DI as Singleton and use PerSession or PerCall as you will effectively get Single as CoreWCF is unaware of how it was added to DI. When it requests an instance each time, a Singleton would respond with the same object every time and you would effectively force it to be Single.

**Comment by schovan** [comment]
@mconnew Are there any plans to support custom instance provider?
There are two methods in the current WCF implementation, which can be implemented (`IInstanceProvider` interface):
```cs
object GetInstance(InstanceContext instanceContext);
void ReleaseInstance(InstanceContext instanceContext, object instance);
```
For me is important `ReleaseInstance `method where I can do some additional actions when transient service is disposed (and I can do them outside WCF service).

**Comment by mconnew** [comment]
@schovan, IInstanceProvider should work. It's possible there's some interfaces or properties which haven't been made public. If that's the case, let me know and I'll expose them but from memory I think they are already public. But I don't think you need to do that (one of my goals is make CoreWCF require less boiler plate code than WCF when extending it). Dispose will get called by WCF on a transient class if it implements IDisposable. I actually wrote unit tests to validate this so I know that is working.

**Comment by schovan** [comment]
@mconnew I was browsing you code and found a class `DependencyInjectionInstanceProvider`, this is exactly I was looking for. It would be nice to set a custom implementation of this, for example `builder.SetInstanceProvider(customImplementation)`.

BTW how do you use this library in a console application when you have no Microsoft dependency injection container?

**Comment by mconnew** [comment]
The DependencyInjectionInstanceProvider is an internal class, there's no need for it to be external. If you've added your service implementation type to DI, CoreWCF will use DependencyInjectionInstanceProvider as the IInstanceProvider implementation. If you don't use DI, it will use the same mechanism that's used on .NET Framework. That is it will instantiate your service type specified using a default constructor.  
CoreWCF can't be used without ASP.NET Core and that can't be used without a DI container so you will always have a DI container available. What's the scenario you are trying to target?

**Comment by mconnew** [comment]
@schovan, I wrote some unit tests to validate adding a custom IInstanceProvider. You can find them [here](https://github.com/CoreWCF/CoreWCF/blob/master/src/CoreWCF.Primitives/tests/Extensibility/InstanceProviderTests.cs). Basically create a service behavior which sets the instance provider on the dispatcher. Then add that behavior to DI.  

I do like the idea of having a helper extension method to make this easier, but the simplicity of builder.SetInstanceProvider isn't going to work. I have a few ideas, and as the consumer of any potential API, I would appreciate your feedback. If you don't care to understand the problem, skip to the text below the header "Options".

The first issue is I don't want to have 1,000 api's all doing slightly different things. I think the best balance is to allow you to provide a delegate which is passed either an `EndpointDispatcher` or `DispatchRuntime` instance. But even then a single builder.ConfigureDispatcher method is too coarse. Basically here's why. If you look at the example behavior for setting the instance provider [here](https://github.com/CoreWCF/CoreWCF/blob/master/src/CoreWCF.Primitives/tests/Extensibility/TestServiceBehavior.cs#L18) there is a hierarchy of objects to get to the InsanceProvider on the DispatchRuntime, and not every instance is appropriate to set it on.  
The first thing done is to iterate over the instances of `ChannelDispatcher` from `ServiceHostBase.ChannelDispatchers`. There's a `ChannelDispatcher` for every binding being used. Each binding can have multiple endpoints. A simple example of this (although not supported in CoreWCF yet, it will be at some point) is an endpoint for metadata (what serves the WSDL) and one for your actual service. You don't want to modify the DispatchRuntime for the metadata endpoint, only your actual service. And although you probably wouldn't have a different `IInstanceProvider` for different bindings, you might use a different `IDispatchMessageInspector` to do different logging. So basically we need something which allows a more fine grained approach.  

**Options**  
Add an overload to the AddServiceEndpoint method as it maps to an EndpointDispatcher. The overload would take a delegate which is passed an `EndpointDispatcher` instance. So something like this:
```c#
    app.UseServiceModel(builder => {
        builder.AddService<MessageService>();
        IInstanceProvider myInstanceProvider = new MyInstanceProvider();
        builder.AddServiceEndpoint<MessageService, IMessageService>(
            new BasicHttpBinding(),
            "/MessageService"
            (endpointDispatcher) =>
            {
                endpointDispatcher.DispatchRuntime.InstanceProvider = myInstanceProvider;
            });
    });
```

Another option is to provide the same delegate to the service collection and it will get called for every EndpointDispatcher instance. An extension helper method would be supplied to make this easier and cleaner and would look like this:
```c#
    IInstanceProvider myInstanceProvider = new MyInstanceProvider();
    services.AddEndpointDispatcherConfig((endpointDispatcher) =>
        {
            if (!endpointDispatcher.IsSystemEndpoint)
            {
                endpointDispatcher.DispatchRuntime.InstanceProvider = myInstanceProvider;
            }
        });
```
Under the hood that would be using `services.AddSingleton<Action<EndpointDispatcher>>(yourdelegate)`. I don;t like this approach from an architectural standpoint is it's more about building your service and the service collection is really mean for adding services. A behavior is a service, but a configuring delegate really isn't.

A variant on the previous version is to add an extension method to serviceBuilder. So the code would look like this:
```c#
    app.UseServiceModel(builder => {
        builder.AddService<MessageService>();
        IInstanceProvider myInstanceProvider = new MyInstanceProvider();
        builder.UseEndpointDispatcherConfig((endpointDispatcher) =>
        {
            if (!endpointDispatcher.IsSystemEndpoint)
            {
                endpointDispatcher.DispatchRuntime.InstanceProvider = myInstanceProvider;
            }
        });
        builder.AddServiceEndpoint<MessageService, IMessageService>(
            new BasicHttpBinding(),
            "/MessageService");
    });
```

Another option would be to create an extension method on ServiceEndpoint, The AddServiceEndpoint method returns an instance of ServiceEndpoint. So it would look something like this:
```c#
    app.UseServiceModel(builder => {
        builder.AddService<MessageService>();
        builder.UseEndpointDispatcherConfig(
        var serviceEndpoint = builder.AddServiceEndpoint<MessageService, IMessageService>(
            new BasicHttpBinding(),
            "/MessageService");
        IInstanceProvider myInstanceProvider = new MyInstanceProvider();
        serviceEndpoint.ConfigureEndpointDispatcher((endpointDispatcher) =>
        {
            endpointDispatcher.DispatchRuntime.InstanceProvider = myInstanceProvider;
        });
    });
```
I like that last option the most as an instance provider specific extension method can be composed on top of that easily. It would look something like this:
```c#
public static class InstanceProviderHelper
{
    public static ServiceEndpoint UseInstanceProvider(this ServiceEndpoint se, IInstanceProvider instanceProvider)
    {
        se.ConfigureEndpointDispatcher((endpointDispatchet) =>
        {
            endpointDispatcher.DispatchRuntime.InstanceProvider = instnaceProvider;
        });
    }
}
```
This composed utility class (along with others for message inspectors etc) could live in a different package with a lower testing and documentation requirement and wouldn't be part of the CoreWCF main packages.

**Comment by Kralizek** [comment]
Is there a strong requirement for AddServiceEndpoint to return an actual endpoint and not some kind of builder class?

This would allow to specify the type and let the DI provider create an instance for us (think of a logging behavior that needs ILogger, or similar cases).

**Comment by schovan** [comment]
@mconnew nice change, I will look at it after new year

**Comment by mconnew** [comment]
@Kralizek, can you please explain a bit more as I'm not quite understanding what you are suggesting. For you final point of letting DI provider the ILogger, my preferred option can still do that.
```c#
public class MyInstanceProvider<TService> : IInstanceProvider where TService : class
{
    ILogger _logger;
    TService _instance;
    public MyInstanceProvider(ILogger logger, TService instance)
    {
        _logger = logger;
        _instance = instance;
    }
    public object GetInstance(InstanceContext instanceContext, Message message) => _instance;
    public object GetInstance(InstanceContext instanceContext) => _instance;
    public void ReleaseInstance(InstanceContext instanceContext, object instance) { }
}
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddServiceModelServices();
        services.AddSingleton<MessageService>();
        services.AddSingleton<IInstanceProvider, MyInstanceProvider<MessageService>>();
    }
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        app.UseServiceModel(builder =>
        {
            builder.AddService<MessageService>();
            var serviceEP = builder.AddServiceEndpoint<MessageService, IMessageService>(new BasicHttpBinding(), "/MessageService");
            serviceEP.ConfigureEndpointDispatcher((ed) =>
            {
                ed.DispatchRuntime.InstanceProvider = app.ApplicationServices.GetRequiredService<IInstanceProvider>();
            });
        });
    }
}
```
If I implemented the ConfigureEndpointDispatcher extension method on ServiceEndpoint, as you can see there's no limitations of what you are able to inject. If you feel a little queezy about all the implicit closures (not on a hot code path so not really a problem), it you can put a strong enough argument as to why, I might be able to be convinced to have the delegate which is passed to ConfigureEndpointDispatcher use the signature `Action<IServiceProvider, EndpointDispatcher>`.  
If that doesn't resolve your concern, can you please provide an example of how you suggest the code might look to help me understand the limitation of this approach.

**Comment by schovan** [comment]
@mconnew I like the example you showed to @Kralizek. If you implement it like that, it will cover all my requirements.

**Comment by Kralizek** [comment]
@mconnew sorry for the lack of clarity.

My post was based on the  wrong assumption that the WCF initialization was happening in the `ConfigureServices` method where only the `ServiceCollection` is available, not in the `Configure` one where we have indirect access to the `ServiceProvider`.

Given the wrong assumption, I was suggestion to have `AddServiceEndpoint` return a builder class so that we could have specified additional specifications without the assumption of a parameterless constructor (needed in the `ConfigureServices` since there is no access to `ServiceProvider` to request for instances).

I don't think this post is any clearer 😅

**Comment by mconnew** [comment]
@Kralizek, there is no longer a presumption of a parameterless constructor. If you use DI to provide your service implementation, the ASP.NET Core DI feature will populate all the constructor parameters from DI. I've tried to make things as flexible as possible without perpetuating the WCF tradition of if a feature is worth providing, it's worth providing 10 different ways to implement it.  
I was thinking about the ConfigureEndpointDispatcher idea on my ride to work this morning and I believe it can be done outside of CoreWCF easily. So I might create a prototype which would also work on WCF on .NET Framework in my Capri nuget package. Basically allow the same functional style of extending CoreWCF for WCF.

**Comment by schovan** [comment]
Hello @mconnew, is there any progress with setting custom `InstanceProvider`?

**Comment by mconnew** [comment]
@schovan, sorry this got lost off my radar. Currently the easiest way to configure a custom `IInstanceProvider` is via an `IServiceBehavior`. You can see an example one [here](https://github.com/CoreWCF/CoreWCF/blob/master/src/CoreWCF.Primitives/tests/Extensibility/TestServiceBehavior.cs). That behavior is also used to set other things for test purposes so you would be able to strip some of that out. The easiest way to add an IServiceBehavior is simply add it to DI as an `IServiceBehavior`. For example `services.AddSingleton<IServiceBehavior>(myConfiguredBehaviorInstance);`. If your behavior takes the `IInstanceProvider` as a constructor argument, then you can add your `IInstanceProvider` to DI, then add your `IServiceBehavior` to DI without providing an instance. For example `services.AddSingleton<IServiceBehavior, MyServiceBehaviorType>();`.  
I'm going to close this issue now as I believe that provides a solution. If that doesn't fit what you need, feel free to reopen the issue and provide more info.

**Comment by schovan** [comment]
@mconnew Your solution works. Thank you. I have a little issue with InstanceContext mentioned here #271.
