### ISSUE TITLE
NullReferenceException in RequestDelegateHandler constructor

### ISSUE THREAD

**Issue by gvkries** [CoreWCF/CoreWCF#566]
When the `ServiceModelHttpMiddleware` is building the application branch for a path, it does not check whether building an service dispatcher has actually succeeded. It then passes null to the `RequestDelegateHandler` which will in turn fail with a NRE. 
There should be a better error message when the current binding does not support the desired channel shape.

**Comment by mconnew** [comment]
This is a bug. This is a service configuration problem and not something where a working service will sometimes fail. @g7ed6e can you look at this?

**Comment by g7ed6e** [comment]
sure

**Comment by g7ed6e** [comment]
@gvkries can you please share the configuration you used so I can add unit tests to #576 ?

**Comment by gvkries** [comment]
In this particular case, I had a duplex contract with a `NetHttpBinding`. If I remember correctly, it failed because the service dispatcher was not created when the default configuration for the `TransportUsage` of the `WebSocketSettings` was used.
 
Anyway, the basic steps to reproduce the exception are:

```c# 
app.UseServiceModel(builder =>
{
    var binding = new NetHttpBinding();
    // Set this to "Always" or "WhenDuplex" to fix the error
    binding.WebSocketSettings.TransportUsage = CoreWCF.Channels.WebSocketTransportUsage.Never;

    builder.AddService<EchoService>()
        .AddServiceEndpoint<EchoService, IEchoService>(binding, "/EchoService/nethttp");
});
```
where the service is a duplex service:

```c#
[ServiceContract(
    CallbackContract = typeof(IEchoServiceCallbackContract))]
  public interface IEchoService
  {
     [...]
  }

  public interface IEchoServiceCallbackContract
  {
      [OperationContract]
      void SomeOperation(string text);
  }
```
