### ISSUE TITLE
NetHttpBinding.WebSocketSettings must be set on HTTPS transport binding element too

### ISSUE THREAD

**Issue by gvkries** [CoreWCF/CoreWCF#567]
When using the NetHttpBinding with HTTPS transport, configuring any WebSocketSettings is not passed to the actual transport binding element. This happens because `HttpBindingBase` is only exposing the HTTP web socket settings - in .NET 4.8 that instance is forwarded to the HTTPS transport binding element too.

**Comment by mconnew** [comment]
I'll take a look.

**Comment by mconnew** [comment]
@gvkries, can you take a look at #568 and check that everything looks good? This should solve the problem for you.

**Comment by mconnew** [comment]
The fix won't be published in a release build on nuget until we release the 1.0 package. In the short term, you can either pull the package from the dev feed (details in main project readme), or you can create your binding like this:
```c#
var netHttpBinding = new NetHttpBinding(BasicHttpSecurityMode.Transport);
// Make any other necessary binding changes which aren't related to WebSocketTransportSettings
var customBinding = new CustomBinding(netHttpBinding);
var httpsTransport = customBinding.Elements.Find<HttpsTransportBindingElement>();
var websocketTransportSettings = httpsTransport.WebSocketSettings;
// make any changes you need to websocketTransportSettings then use pass CustomBinding to AddServiceEndpoint
```

I'm leaving this issue closed as you now have 2 workaround (dev build, and above code) that you can use until the 1.0 release.
