### ISSUE TITLE
Plans to port ServiceHost?

### ISSUE THREAD

**Issue by wouterroos** [CoreWCF/CoreWCF#57]
Hi,

Are there any plans for porting the WCF ServiceHost class to CoreWCF? From what I could make from the samples it seems that it has been replaced by the ServiceBuilder implementation, is this correct? If so, will other features currently present on ServiceHost (Description.Behaviors etc.) be ported as well?

Regards,

Wouter

**Comment by mconnew** [comment]
Porting of ServiceHost can't happen as the pattern of control is backwards for using AspNetCore. ServiceHost would be the one to create an instance of AspNetCore and configure it which prevents you running other endpoints such as an MVC endpoint on the same port.  
Behaviors are supported. You just add them a different way. In the ConfigureServices method, you simple add your IServiceBehavior to the services collection similar to this:
```
    services.AddSingleton<IServiceBehavior>(behavior);
```
I've taken the approach that implementation code shouldn't need to change by plumbing code might. So for example you should be able to change a using statement to switch to CoreWCF and use your existing behavior implementation with no other changes, you just have to add your behavior using DI. There's only a few things which you can't do in behaviors that you could do before. The only one I'm aware of is modifying the bindings from the Validate method but there's likely a couple of other scenarios which don't work. If you come across one, let me know and I will find a way to make it work if possible.

**Comment by mconnew** [comment]
I believe I've answered your question so closing the issue. If you have any follow up questions, feel free to reopen the issue.

**Comment by OhSoGood** [comment]
@mconnew : could you explain your first paragraph above, I don't understand it (sorry...)

> Porting of ServiceHost can't happen as the pattern of control is backwards for using AspNetCore. ServiceHost would be the one to create an instance of AspNetCore and configure it which prevents you running other endpoints such as an MVC endpoint on the same port.

Are you saying, in porting my .NET framework app which was self hosting WCF (using ServiceHost), I should no more use ServiceHost but use AspNetCore ? Can't I avoid using AspNetCore?
Thank you!

**Comment by mconnew** [comment]
You can't avoid using AspNetCore as CoreWCF has been rebuilt on top of AspNetCore as middleware. AspNetCore is a multi-protocol host for hosting various services. For example, WebAPI/WebMVC, Razor apps etc. CoreWCF is now another type of service you can host on AspNetCore. It's also now not so strongly HTTP opinionated and can support multiple protocols. For example, CoreWCF doesn't know anything about the Socket class when talking NetTcp. I rebuilt it to use AspNetCore's generic connection handler mechanism.  
AspNetCore doesn't need IIS to host but can do if you want, and can also run on Linux. The reason for rebuilding on AspNetCore is to leverage the multi-platform and multi-hosting support it provides without having to reinvent those same wheels.  
Is there a specific reason you wish to avoid AspNetCore?

**Comment by OhSoGood** [comment]
I was thinking about the lightweight aspect of the solution, but that may be a "wrong good idea"... So let's go for aspnetcore

**Comment by Treit** [comment]
@OhSoGood the sample service under src\Samples\NetCoreServer shows exactly how to host a WCF process in a simple executable. If you need a 'Windows Service', write the service like you would normally (without WCF) and then just do what the sample does to bootstrap the WCF service at startup to listen on the appropriate port, etc.

**Comment by mconnew** [comment]
@OhSoGood, as @Treit said there's nothing different about CoreWCF for this. For any hosting questions, think first that this is an ASP.NET Core service where the service type is CoreWCF (as opposed to MVC or Razor). [Here's the documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio) for running an ASP.NET Core service, so follow that, and once you've got it working, add the CoreWCF pieces.

**Comment by DavidRMaltby** [comment]
> NetCoreServer

Sample is now located at https://github.com/CoreWCF/samples/tree/main/Scenarios/Getting-Started-with-CoreWCF/NetCoreServer
