### ISSUE TITLE
This should be driven by DI and the newer configuration api's. Out of scope for this change. Can you open an issue for configuring SecurityTokenHandler's via config and DI.

### ISSUE THREAD

**Issue by birojnayak** [CoreWCF/CoreWCF#577]
This should be driven by DI and the newer configuration api's. Out of scope for this change. Can you open an issue for configuring SecurityTokenHandler's via config and DI.

_Originally posted by @mconnew in https://github.com/CoreWCF/CoreWCF/pull/538#discussion_r830414053_

**Comment by mconnew** [comment]
This work was completed as part of fixing CookieTransform
