### ISSUE TITLE
FaultCode.CreateReceiverFaultCode is not public

### ISSUE THREAD

**Issue by jecook** [CoreWCF/CoreWCF#580]
We have some legacy code that catches some specific `Exception`s, does some additional processing and spits out a custom `FaultException`. This code calls `FaultCode.CreateReceiverFaultCode`, but since that is now marked `internal`, the code doesn't compile when using CoreWCF.
There is, of course, a simple workaround (just create the receiver `FaultCode` manually), but the fix in CoreWCF for this seems pretty simple too.

**Comment by mconnew** [comment]
This will be coming in the next release. The change has already been checked in to the feature/WebHttpBinding branch.
