### ISSUE TITLE
Implement a compression format option for binary messages sent over a TCP transport

### ISSUE THREAD

**Issue by glsolaria** [CoreWCF/CoreWCF#595]
I get an NotSupportedException when I try to enable GZip compression on a NetTcpBinding ...
```csharp
var netTcpBinding = new NetTcpBinding();
netTcpBinding.Security.Mode = SecurityMode.Transport;
netTcpBinding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Certificate;
                    
var customBinding = new CustomBinding(netTcpBinding);

var binaryEncoding = customBinding.Elements.Find<BinaryMessageEncodingBindingElement>();
binaryEncoding.CompressionFormat = CompressionFormat.GZip;
```

> Unhandled exception. System.NotSupportedException: The transport configured on this binding does not appear to support the CompressionFormat specified (GZip) on the message encoder.  To resolve this issue, set the CompressionFormat on the BinaryMessageEncodingBindingElement to 'None' or use a different transport. 
> at CoreWCF.Channels.BinaryMessageEncodingBindingElement.VerifyCompression(BindingContext context) in C:\corewcf\ReferenceSource\CoreWCF-1.0.0-preview1\src\CoreWCF.Primitives\src\CoreWCF\Channels\BinaryMessageEncodingBindingElement.cs:line 163

**Comment by jonlouie** [comment]
I'm interested in helping with this issue

**Comment by birojnayak** [comment]
@jonlouie assigning to you
