### ISSUE TITLE
readme link to license file is broken

### ISSUE THREAD

**Issue by KunalSaini** [CoreWCF/CoreWCF#597]
Current link in README is broken
![image](https://user-images.githubusercontent.com/4111254/162269342-d412fa65-d0b0-465a-b1ef-9c30aa30c84f.png)

**Comment by KunalSaini** [comment]
This PR fixes the link https://github.com/CoreWCF/CoreWCF/pull/596 , 

If you want to rename the file to `LICENSE.txt` , i can update the pr.

**Comment by mconnew** [comment]
Thank you, closing as merged. BTW, if you put on a line on it's own at the start of the first comment that you submit with the PR "Fixes #issuenumber", merging the PR automatically closes the issue.
