### ISSUE TITLE
Plans to support WSHttpBinding?

### ISSUE THREAD

**Issue by wouterroos** [CoreWCF/CoreWCF#60]
Hi,

Is WSHttpBinding planned in the near future?

Regards,

Wouter

**Comment by dotnetchris** [comment]
Personally i would advocate never including the ws* nightmare ever again.

The atrocities the WS* "standards" created all the (unfounded) hatred of WCF that exists.

Http is a terrible protocol, it shouldn't be used with WCF.

**Comment by mconnew** [comment]
@wouterroos, WSHttpBinding enables a lot of different WS-* features. Some of them will be easier to port over, some will be harder or even impossible (such as Transactions support without full System.Transactions implementation). Can you provide your current binding and I can give you an idea of size/difficulty to port the features you are using.

**Comment by mconnew** [comment]
This is being worked on in #172

**Comment by mconnew** [comment]
WSHttpBinding is now supported, but not all features. If there's a specific feature that's missing, please open a separate issue for that feature.
