### ISSUE TITLE
WSDL import URLs loading default WSDL instead of correct document

### ISSUE THREAD

**Issue by jecook** [CoreWCF/CoreWCF#604]
When there are imports in the WSDL, e.g. `<wsdl:import namespace="myns" location="https://localhost:8088/MyService?wsdl=wsdl0" />`, the import URL returns the same document as the default.

It looks like there might be a problem in `ServiceMetadataExtension.HttpGetImpl.FindQuery` when there is a Value. The returned query does not include the value, so it cannot find the correct doc:
```
. . .
if (string.Compare(q.Key, WsdlQueryString, StringComparison.OrdinalIgnoreCase) == 0)
{
    query = q.Key;
}
. . .
```
should be something like:
```
. . .
if (string.Compare(q.Key, WsdlQueryString, StringComparison.OrdinalIgnoreCase) == 0)
{
    query = string.IsNullOrWhiteSpace(q.Value) ? q.Key : $"{q.Key}={q.Value}";
}
. . .
```
This is true for at least `?wsdl=wsdlN` and `?xsd=xsdN`.

It look like the way it's done is slightly different from System.ServiceModel, which passes in the queries, e.g. `"wsdl=wsdl0"`, as a `string[]` and then checks a substring for `"wsdl"`, etc.

**Comment by roend83** [comment]
I hit this issue too.  I can submit a PR if you'd like.

**Comment by mconnew** [comment]
I'll take a look at the PR. Thank you.
