### ISSUE TITLE
NetTcpBinding won't listen on IPV6

### ISSUE THREAD

**Issue by FreeAndNil** [CoreWCF/CoreWCF#606]
Hi,

we use 

IWebHostBuilder result = WebHost.CreateDefaultBuilder().UseNetTcp(805);

void Configure(IApplicationBuilder app, IHostingEnvironment env)
=> app.UseServiceModel(builder =>
{
  builder.AddService(typeof(MyService));
  builder.AddServiceEndpoint(typeof(MyService), typeof(IMyService), netTcpBinding, "nettcp://<hostname>:805/MyService.svc", "nettcp://<hostname>:805/MyService.svc");
}

After starting the server, it won't listen on IPV6.

Now listening on: http://**0.0.0.0**:805
Application started. Press Ctrl+C to shut down.

When using HTTP we get:
Now listening on: http://**[::]**:805

But the client tries to connect via IPV6 and won't get a response.

Is this a known problem?
How can this be fixed?

Regards.

**Comment by MsLilu2** [comment]
@FreeAndNil @mconnew Have you confirmed the fix resolved the not listening on IPV6 issue? It does not take effect in my side. :(

Here is my web host builder
`WebHost.CreateDefaultBuilder().UseNetTcp(8089).UseStartup<Startup>();`

`app.UseServiceModel(builder =>
 {
builder.AddService<EchoService>().AddServiceEndpoint<EchoService, IEchoService>(new NetTcpBinding(), $"net.tcp://localhost:{NETTCP_PORT}/netTcp");
 });`

And my package reference
`<PackageReference Include="CoreWCF.NetTcp" Version="1.1.0" />`
`<PackageReference Include="CoreWCF.Primitives" Version="1.1.0" />`

And the result only shows 0.0.0.0:8089, no [::]:8089
![image](https://user-images.githubusercontent.com/109129479/178923757-2bd34980-51a6-4d8a-9caa-88accaaf87bf.png)

**Comment by FreeAndNil** [comment]
@MsLilu2 you need to call another overload:
`.UseNetTcp(IPAddress.IPv6Any, 8089)`

**Comment by MsLilu2** [comment]
Great! @FreeAndNil Thank you so much, it works!
