### ISSUE TITLE
About FaultException

### ISSUE THREAD

**Issue by mzuvin** [CoreWCF/CoreWCF#620]
The background task is stopped because an exception is thrown at the library I am using (Hangfire).
Can I return a result without throwing the FaultException object?

**Comment by mzuvin** [comment]
my solution :

#523 thanks. 
```cs
HttpContext httpContext = (OperationContext.Current.RequestContext.RequestMessage.Properties.TryGetValue("Microsoft.AspNetCore.Http.HttpContext", out var @object)
                                   && @object is HttpContext context)
            ? context 
            : null;
byte[] data = Encoding.UTF8.GetBytes("<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\"><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Receiver</soap:Value></soap:Code><soap:Reason><soap:Text xml:lang=\"en\">...</soap:Text></soap:Reason><soap:Detail><ns3:EFault xmlns:xmime=\"http://www.w3.org/2005/05/xmlmime\"><code>1</code><msg>msg</msg></ns3:EFault></soap:Detail></soap:Fault></soap:Body></soap:Envelope>");
        httpContext.Response.Headers.Add("Content-Type","application/soap+xml;charset=UTF-8");
        httpContext.Response.Headers.Add("Content-Length",data.Length.ToString());
        httpContext.Response.Body.WriteAsync(data);
        
```

**Comment by mconnew** [comment]
What's your reason for wanting to avoid throwing a FaultException? If you create a class called EFault with a code and message property and add a FaultContract attribute specifying the fault detail type as your EFault type,

**Comment by mzuvin** [comment]
I'm a bit of a newbie in CoreWcf. I was throwing wrong faultexception object (System.ServiceModel.FaultException). I found too late where I went wrong. I thought of such a solution myself. Actually, it has nothing to do with hangfire.

> What's your reason for wanting to avoid throwing a FaultException? If you create a class called EFault with a code and message property and add a FaultContract attribute specifying the fault detail type as your EFault type,

**Comment by mzuvin** [comment]
I resorted to this method because there are model differences between the java wcf server running on another server and my (.net core) server. but I haven't fully tested the differences with Java. Maybe there is a problem, I'm not sure. Because corewcf's .wsdl import support does not fully work in my project. What I did fixed the problem, I also didn't touch it as it worked
