### ISSUE TITLE
Service metadata behavior does not consider Host header when setting port address

### ISSUE THREAD

**Issue by cpx86** [CoreWCF/CoreWCF#625]
When running WCF under IIS, if the client includes a Host header when requesting the service metadata, the port address in the resulting WSDL will have that host name instead of the host name that the service is actually bound to. In CoreWCF, this is not currently the case.

This behavior is quite useful when testing WCF services that are behind a reverse proxy (which arguably is usually the case) so you don't need to manually change the endpoint address in the generated client.

I wasn't able to reproduce this when hosting WCF in a console application. So I've no idea if this is all WCF's doing, or if it's the combination of WCF and IIS that allows for this behavior. Here's a sample request of how WCF behaves under IIS:
![image](https://user-images.githubusercontent.com/209890/164754709-2134978e-b516-4c43-a5b3-f8c008561084.png)

**Comment by mconnew** [comment]
This isn't enabled by default even in WCF. It is a feature you need to turn on, but it's easily done. You just need to add an instance of `UseRequestHeadersForMetadataAddressBehavior` to the service description behaviors. With CoreWCF this is easy as we check DI for instances of IServiceBehavior so you can enable this feature with this single line::
```c#
services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();
```
You can see the (very sparse) documentation for it is [here](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.description.userequestheadersformetadataaddressbehavior?view=netframework-4.8).  

If you need to modify DefaultPortsByScheme, just create an instance and modify that property, then add it to DI as an IServiceBehavior.

**Comment by cpx86** [comment]
Thanks, the correct solution seems so obvious now - I'll close this issue then 😅 What threw me off was, it seems WCF adds this behavior automatically if `serviceHostingEnvironment.multipleSiteBindingsEnabled` is enabled - I mistakenly thought the ServiceMetadataBehavior handled this by default.

**Comment by mconnew** [comment]
@cpx86, I didn't know it did that automatically when you enable MultipleSiteBindingsEnabled, I found the code where it does this. I've been working with WCF for nearly 11 years and I still learn new things from time to time. I'm glad you are unblocked.
