### ISSUE TITLE
Compatibility expectations for extensions

### ISSUE THREAD

**Issue by Kralizek** [CoreWCF/CoreWCF#63]
Hi,

I know this question gets asked a lot, but mostly people focuses on contracts.

In my spare time I'm working on adding support for AWS X-Ray to our Windows WCF services. https://github.com/Kralizek/xray-wcf/

Which level of compatibility am I to expect for the service behavior and the dispatch message inspector?

I am expecting the need of pointing to new packages and do some namespace update, but I'm hoping to keep the operational logic the same. Am I being too optimistic?

PS: Thank you for the great work you're putting into this project!

**Comment by mconnew** [comment]
You are not being too optimistic. That is the goal, to only require namespace updates in your extensibility implementations. Some plumbing code will change such as how to add a behavior which adds the message inspector. But even your behavior code should still work. There are going to be a tiny number of obscure scenarios which can't be made to work, but the expectation is the majority will just work.  
If you have an extensibility implementation which isn't behaving the same way as on .NET Framework WCF, I would consider that a bug in most cases.

**Comment by Kralizek** [comment]
Great to hear. Thanks for your quick reply! :)
