### ISSUE TITLE
CoreWCF source generator interfers with usages of [FromServicesAttribute] in ASP.NET Core MVC Controllers

### ISSUE THREAD

**Issue by g7ed6e** [CoreWCF/CoreWCF#635]
Installing CoreWCF packages in an ASP.NET Core application that already expose routes MVC framework is triggering false positive build errors. The CoreWCF source generator requires the user implemented `Controller` classe to be `partial`.

**Comment by mconnew** [comment]
I thought we only modified classes which implemented an interface which is attributed with ServiceContract?

**Comment by g7ed6e** [comment]
> I thought we only modified classes which implemented an interface which is attributed with ServiceContract?

I just had a look to the code and this is not exactly the case because we are issuing a report diagnostic when the class containing the method to « enrich » does not implement an interface service contract.
The « entry point »  of the algorithm, as is, is the presence of the attribute attached to a method parameter. I did things like this to avoid a full scan of all potential interfaces being a service contract in current and referenced assemblies as much as possible as source generator code is executed a lot in VS. Also it allows to warn user about missing condition for code generation.
