### ISSUE TITLE
Global exception handling

### ISSUE THREAD

**Issue by ThomasArdal** [CoreWCF/CoreWCF#657]
I'm playing around with CoreWCF and like what I see so far. I noticed that logging works out of the box with `ILogger`. But I'm wondering if there's a way to create a global exception handler. When throwing an exception from the `EchoService` class in the sample:

```csharp
public string Echo(string text)
{
    System.Console.WriteLine($"Received {text} from client!");
    throw new ApplicationException("Oh no from CoreWCF");
    return text;
}
```

The exception is not logged by CoreWCF. Am I missing something or is there another way to make sure this gets logged? Other log messages logged through `ILogger` gets logged, why I'm sure that logging is configured correctly.

**Comment by alexey-kostylev** [comment]
I think you can do it in a usual way: 
`app.UseMiddleware<ExceptionHandler>()`

[https://jasonwatmore.com/post/2022/01/17/net-6-global-error-handler-tutorial-with-example](https://jasonwatmore.com/post/2022/01/17/net-6-global-error-handler-tutorial-with-example)

**Comment by ThomasArdal** [comment]
I don't think middleware will work in the sample. It is using `UseNetTcp` which is not HTTP-based. At least that is what I found here: https://gitter.im/CoreWCF/CoreWCF?at=607f38712e5574669b4bcd66.

It would be cool to be able to use middleware. But it doesn't change that uncaught errors don't seem to be logged through `ILogger`. If CoreWCF should follow how things are done in ASP.NET Core in general, errors should probably be logged. At least that's my opinion.

**Comment by alexey-kostylev** [comment]
I agree with you, for Tcp its probably a different story,

**Comment by mconnew** [comment]
@alexey-kostylev, that won't work for CoreWCF. If your service implementation throws an exception, CoreWCF turns that into a generic Fault message which simply says something went wrong with no details for the client (for security reasons) and returns that to the client in the response. An exception thrown in a service does not propagate out of CoreWCF to earlier middleware.  

You can turn on providing the exception details in the returned Fault message and when the client turns the Fault message into a FaultException and throws it, the server side exception message and call stack will be included. If you want server side logging, you can implement an IErrorHandler. There's a really good article explaining it all for WCF [here](https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/extending-control-over-error-handling-and-reporting). You don't have to implement the behavior as an attribute, you can add it to DI instead. Either way works.  

I'm going to close this issue as I believe this solves your problem. If it doesn't, then feel free to reopen.

**Comment by ThomasArdal** [comment]
I had forgotten everything about `IErrorHandler` 👍  I still think it would make sense to log errors to `ILogger` but I see the need for providing an error handler as part of the framework which may not be preferable.

The article you have linked to is great. I just think it misses the possibilities from CoreWCF. You mention that the `IErrorHandler` implementation can be dependency injected to avoid having to implement the behavior attribute. But the article doesn't say anything about this possibility since that's for WCF. At least that's my understanding 😄

**Comment by mconnew** [comment]
I still need to work out how we're going to approach logging in general. Many people use svctraceviewer so it's important that however we log, it can be transformed/output into something readable by that. But we need to do it in a cross platform way, and also have an eye to integrating into newer tooling which uses OpenTelemetry. I don't know if that's sufficient or whether we need a dual approach, do things the old way and support doing things the new way too. There's also perf counters in the mix to consider.  

The DI stuff I believe is in one of the blog posts. You just do `services.AddSingleton<IServiceBehavior, MyBehaviorType>()` and it gets picked up by CoreWCF as a behavior automatically. But that's obviously only a CoreWCF thing. We are working on documentation, but it's a big task and taking some time. The goal has been to make most things from WCF applicable with the change of a using namespace so it hasn't been too big of a problem, but we do have some areas where we need new docs like DI capabilities. I have some ideas to make DI easier to handle too, to enable things to be scoped per service.  

In this case, the DI injectability is really useful as it enables you to inject an ILogger into your IErrorHandler (via your behavior) really easily. We are working on a samples repo similar to the old WCF samples and a sample IErrorHandler would make a good addition. Were you hinting at asking me to write an example using IErrorHandler?

**Comment by ThomasArdal** [comment]
I think people would expect `ILogger` to work (which is does).

As for the DI stuff, being CoreWCF-specific is actually fine for this issue I believe. That was what I was after in the first place 👍 

The purpose of this task was really to find out how to do global error logging ("Global exception handling" was a misleading title). But an example of how to do this either as documentation somewhere or as a code sample would be really awesome. My job probably causes me to have some strange fetishes around logging in general, but I think it's important for all projects to have it set up.

**Comment by ThomasArdal** [comment]
BTW, your proposed solution with injecting the `IServiceBehavior` works perfectly 🙌 Thank you for your help 🙏

![image](https://user-images.githubusercontent.com/563206/168247305-d84f4adc-742a-472c-94eb-5c3146e8f8d6.png)

**Comment by mconnew** [comment]
I want to go a step further and have a method which looks something like this:
```c#
public static IServiceCollection AddServiceBehavior<TService, TBehavior>(this IServiceCollection services)
    where TBehavior : IServiceBehavior { }
```
Then under the hood have some other class which is specific TService and acts as a holder for TBehavior. That way you can scope a behavior to a specific service. This will then require another helper method to act against the IServiceProvider to fetch the helper type and get the specific behavior for the service. That extension method would something like this:
```c#
public static TBehavior GetServiceBehavior<TService, TBehavior>(this IServiceProvider provider)
    where TBehavior : IServiceBehavior { }
```
I wouldn't want to create a helper which adds a service behavior for all services as that has caused a few problems, notably with the WSDL support. It might make sense to have a method where you add it once and each service type gets it's own instance. So basically a per service singleton. I could see that being useful behavior to do with the extension method signatue you suggested. So calling AddServiceBehavior would require using GetServiceBehavior to get the service for the specific service type and you wouldn't be able to use the usual GetRequiredService method as it would be wrapped in a wrapped internally. This whole area requires a discussion thread to get everyones thoughts as there are lots of interesting things which could be done, and it's a grey line for what should be done. For example, you could have a factory AddServiceBehavior method which looks like this:
```c#
public static IServiceCollection AddServiceBehavior<TBehavior>(this IServiceCollection, Func<Type, TBehavior> factory) where TBehavior : IServiceBehavior { }
```
You would pass a factory delegate which is passed a Type object for the service type that is being created and you would instantiate the behavior and do any configuration before returning it. I've been thinking about something similar for easily adding message inspectors and other extensibility point, but where you get passed a ServiceEndpoint so you can decide which message inspector type to return (and configure it if needed), or return null if you don't want to provide one. We could also have it where the delegate returns true or false to specify whether the message inspector (or other extensibility) should be used for the particular endpoint. There's a lot that we can do, but you don't want to end up being more confusing by having hundreds of variations.
