### ISSUE TITLE
ServiceBehaviorAttribute -> UseSynchronizationContext missing

### ISSUE THREAD

**Issue by skurth** [CoreWCF/CoreWCF#668]
In .NET-Framework WCF, there is a property on ServiceBehaviorAttribute named UseSynchronizationContext. When you set it to false, there is less blocking with multiple (long running) requests:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/1873eb17-a711-4512-84be-463b74b087b5/wcf-long-running-task-blocks-all-other-calls?forum=wcf

https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.servicebehaviorattribute.usesynchronizationcontext?redirectedfrom=MSDN&view=netframework-4.8#System_ServiceModel_ServiceBehaviorAttribute_UseSynchronizationContext

Is this not an issue anymore in CoreWCF or can/will this feature be added?

**Comment by mconnew** [comment]
We do have support for this in the implementation, but it looks like we didn't add it to this behavior to modify it. It's only an issue if you have a sync context set when you start the service. This generally only happens with a UI app. We'll use this issue to track adding that API back in.

**Comment by bjornhellander** [comment]
I can have a go at this. Do you have any thoughts about what kind of tests you would like to see?
