### ISSUE TITLE
CreateBufferedCopy and CreateMessage fail when the ServiceAuthorizationManager is set

### ISSUE THREAD

**Issue by oruchreis** [CoreWCF/CoreWCF#683]
Hi,
I copy the request and response messages with `CreateMessage` after `CreateBufferedCopy` for logging the raw request and responses. But `CreateMessage` method fails at `CopyProperties` because the properties has `null` keys.
https://github.com/CoreWCF/CoreWCF/blob/40610b671b75b145f2b90f39be713712bb4c69c8/src/CoreWCF.Primitives/src/CoreWCF/Channels/MessageBuffer.cs#L284
I've looked into `CreateBufferedCopy` method and it doesn't add keys if a property is not set, or its private backend field is null:
https://github.com/CoreWCF/CoreWCF/blob/40610b671b75b145f2b90f39be713712bb4c69c8/src/CoreWCF.Primitives/src/CoreWCF/Channels/Message.cs#L1841
In my situation, the `AllowOutputBaching` property's backend field is null:
![resim](https://user-images.githubusercontent.com/3736187/170048940-7fc79875-f1c4-416e-b2de-f870f637dd76.png)
so the `CreateBufferedCopy` method copies properties like this:
![resim](https://user-images.githubusercontent.com/3736187/170049944-811eee8b-77ea-4166-9e71-6fffe3bc7b61.png)
If I set private field `_allowOutputBaching` to a value true or false by reflection, then it succeeds.

### Update
I've figure out what cause this. I'm using a custom `ServiceAuthorizationManager`, previously I set this in a custom `ServiceHostFactory` in old WCF. And now I'm setting this in `ConfigureServiceHostBase` like that:
```csharp
serviceBuilder
    .ConfigureServiceHostBase(myServiceType, hostBase =>
    {
        hostBase.Authorization.ServiceAuthorizationManager = new ApiKeyAuthorization();
        hostBase.Description.Behaviors.Add(new ErrorServiceBehavior());
```
If I comment out `ServiceAuthorizationManager` line, it works, but when I set this custom auth manager, it fails like above post at CreateMessage method.
My `ApiKeyAuthorization` is simple a class derived from `ServiceAuthorizationManager`, and it checks api key for security. And it gets api key from message properties like that:
```csharp
    private string GetApiKey(OperationContext operationContext)
    {
        var request = operationContext.RequestContext.RequestMessage;
        var requestProp = (HttpRequestMessageProperty)request.Properties[HttpRequestMessageProperty.Name];
        var query = UrlHelper.ParseQueryString(requestProp.QueryString);
        return query["api"];
    }
```
Maybe I can get api key from httpContext now, but this auth manager works in old WCF. Maybe I set this in wrong place?

**Comment by oruchreis** [comment]
I've figure out what cause this. I'm using a custom `ServiceAuthorizationManager`, before I was set this in a custom `ServiceHostFactory` in old WCF. And now I'm setting this in `ConfigureServiceHostBase` like that:
```
serviceBuilder
    .ConfigureServiceHostBase(myServiceType, hostBase =>
    {
        hostBase.Authorization.ServiceAuthorizationManager = new ApiKeyAuthorization();
        hostBase.Description.Behaviors.Add(new ErrorServiceBehavior());
```
If I comment out `ServiceAuthorizationManager` line, it works, but when I set this custom auth manager, it fails like above post at CreateMessage method.
My `ApiKeyAuthorization` is simple a class derived from `ServiceAuthorizationManager`, and it checks api key for security. And it gets api key from message properties like that:
```
    private string GetApiKey(OperationContext operationContext)
    {
        var request = operationContext.RequestContext.RequestMessage;
        var requestProp = (HttpRequestMessageProperty)request.Properties[HttpRequestMessageProperty.Name];
        var query = UrlHelper.ParseQueryString(requestProp.QueryString);
        return query["api"];
    }
```
Maybe I can get api key from httpContext now, but this auth manager works in old WCF. Maybe I set this in wrong place?

**Comment by mconnew** [comment]
I think I found the bug. Can you check the `Message.Security` property before you make the buffered copy? The code handling this special property had been commented out when copying the properties in the `ICollection<KeyValuePair<string, object>>.CopyTo` method. Basically some properties (like `Security`) aren't stored in the backing dictionary but still act like they are. The property copying code checks how many properties there are (and the count is adjusted based on whether the special properties are null or not) and creates an array to hold them. The `CopyTo` method maintains an index as it copies the data into the array and increments it as it checks each of the special properties if they aren't null. I think what's happening is the Security property is not null so gets included into the count, an array is created to hold all the properties in the MessageBuffer, but the security property didn't get copied in making the last entry in the array null. When it creates the new MessageProperties, it tries to copy the array across and the last entry is null causing the exception. I think you can do the following to work around this until I have a fix out:
```c#
message.Properties.Add("SecurityBackup", message.Properties.Security);
message.Properties.Security = null;
var bufferedCopy = message.CreateBufferedCopy(int32.MaxValue);
var copiedMessage = bufferedCopy.CreateMessage();
copiedMessage.Properties.Security = copiedMessage.Properties["SecurityBackup"] as SecurityMessageProperty;
```
I would suggest leaving SecurityBackup in the properties as removing an item from the properties results in it getting disposed.  If you do want to remove it, you need to clone it when setting it back as Security. So the last line would become this:
```c#
// CreateCopy() returns an IMessageProperty so you need to cast it a second time
copiedMessage.Properties.Security = (copiedMessage.Properties["SecurityBackup"] as SecurityMessageProperty).CreateCopy() as SecurityMessageProperty;
```

I'll reference this issue in the PR I'll create.

**Comment by oruchreis** [comment]
I've tested the workaround, it worked first but after repeating second request it throwed this:
```
IndexOutOfRangeException: Index was outside the bounds of the array.
    CoreWCF.Channels.MessageProperties.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.CopyTo(KeyValuePair`2[] array, Int32 index)
    CoreWCF.Channels.BufferedMessage.OnCreateBufferedCopy(Int32 maxBufferSize)
    CoreWCF.Channels.Message.CreateBufferedCopy(Int32 maxBufferSize)
```
It is interesting that if I restart application it works first time. 
I don't know if it is worth to help the bug, I had done the following workaround by reflection before:
```csharp
message.Properties.GetType().GetField("_allowOutputBatching", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).SetValue(request.Properties, false);
message.Properties.GetType().GetField("_propertyCount", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).SetValue(request.Properties, request.Properties.Count - 1);
message.Properties.AllowOutputBatching = true;
message.Properties.AllowOutputBatching = false;
```
If I don't decrease the `_propertyCount` by 1, it throws same `IndexOutOfRangeException` above. If I don't set `AllowOutputBatching` true/false, it throws same exception when the `ServiceAuthorizationManager` is set.

I really appreciate your spending your time.
Best Regards.
