### ISSUE TITLE
Should I chose the scoped life cycle for the Channel?

### ISSUE THREAD

**Issue by PccCodesix** [CoreWCF/CoreWCF#698]
Should I Create one callClient  for each request or Only one for all requests? create client  like this

var binding = new BasicHttpBinding();
var endpoint = new EndpointAddress(_url);
var factory = new ChannelFactory<MirrorWsdlSearchableSoap>(binding, endpoint);
var callClient = factory.CreateChannel();

**Comment by mconnew** [comment]
This repo is for the CoreWCF server. Questions about the client should be directed to https://github.com/dotnet/wcf
