### ISSUE TITLE
Netstandart 2.0??

### ISSUE THREAD

**Issue by Serjaru** [CoreWCF/CoreWCF#723]
library for Net standart 2.0 or old core 3.1 ?? But sample net 6.0?? 

Do correct for net 6.0

Forget netstandar and core 3.1 

a u sure? )))))))

**Comment by mconnew** [comment]
We support netstandard2.0 so that CoreWCF will run on .NET Framework. This will be dropped in the 2.0 release. This allows an easier migration as you can validate that CoreWCF has the features you need without having to migrate your service implementation to .NET Core/.NET 6 first.
