### ISSUE TITLE
Is Windows Authentication supported at version 1.0.2

### ISSUE THREAD

**Issue by hatzhang** [CoreWCF/CoreWCF#725]
I tried different bindings, and i am using ConfigurationManagerFile at the server side.
With basicHttpBinding, and security mode of Transport, ServiceSecurityContext won't be populated.
```
<basicHttpBinding>
  <binding name = "SecuredBasic" >
	  <security mode = "Transport">
		  <transport clientCredentialType="Windows"  />
	  </security>
  </binding>
</basicHttpBinding>
```
And with wsHttpBinding and security mode of Message, PlatformNotSupportedException will be thrown.
```  
<wsHttpBinding>
	<binding name="MixedWsHttp">
		<security mode="Message">
			<message clientCredentialType="Windows"  />
		</security>
	</binding>
</wsHttpBinding>
```
And security mode of TransportWithMessageCredential, does not have clientCredentialType of Windows.

I understand that Windows Authentication seems to platform dependent, but [AspNetCore supported it](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-6.0&tabs=visual-studio).

So is it supported, and what is the right way to do it?

**Comment by mconnew** [comment]
TransportWithMessageCredential does support client credential type of Windows. You set the security mode to TransportWithMessageCredential and then modify the message security node. You should be able to do something like this:
```xml
<wsHttpBinding>
	<binding name="MixedWsHttp">
		<security mode="TransportWithMessageCredential">
			<message clientCredentialType="Windows" />
		</security>
	</binding>
</wsHttpBinding>
```
I know this works as @birojnayak spent a lot of time making sure this scenario works. We now have (as of this morning) the Transport security with Windows auth working, but we haven't released a nuget package onto nuget.org with that yet. You can use the latest package on the dev feed that's mentioned in the main readme. I don't know whether we've tested setting it by config, but I have no reason to believe that scenario wouldn't work.

**Comment by hatzhang** [comment]
Thanks.
I verified Transport security with Windows auth work with the version of 1.1.0-alpha.41.

On client side:
```
static BasicHttpBinding HttpsBinding()
{
    var result = new BasicHttpBinding();
    result.MaxReceivedMessageSize = 2147483647;
    result.Security.Mode = BasicHttpSecurityMode.Transport;
    result.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
    
    return result;
}
```
And on server side:
```
<basicHttpBinding>
  <binding name = "SecuredBasic" maxReceivedMessageSize="2147483647">
	  <security mode = "Transport">
		  <transport clientCredentialType="Windows"  />
	  </security>
  </binding>
</basicHttpBinding>
```
And AspNetCore authentication need to be enabled, i used the [Kestrel way](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-6.0&tabs=visual-studio#kestrel).
