### ISSUE TITLE
CoreWCF survey

### ISSUE THREAD

**Issue by samsp-msft** [CoreWCF/CoreWCF#739]
We'd like to better understand how you are using WCF, and where CoreWCF is or isn't meeting your needs. Can you take a couple of minutes to fill out our [survey](https://www.surveymonkey.com/r/QM5CXX5)

Thanks.

**Comment by samsp-msft** [comment]
Thank you to everyone who took the time to fill out the survey. It is now closed. If you would like to provide input, please add votes for feature requests to #234, or start a new issue for discussion.

**Comment by Kralizek** [comment]
Not sure if worth a whole discussion thread but I'd love to see this library to step up from just a tool to modernize legacy applications to a tool potentially suggested for green development.

I've worked with grpc a bit and while it has many interesting features, it also lacks of a lot of things that WCF then and CoreWCF now have out of the box.
