### ISSUE TITLE
Colliding namespaces

### ISSUE THREAD

**Issue by TrabacchinLuigi** [CoreWCF/CoreWCF#747]
CoreWCF has colliding namespaces with System.ServiceModel.* packages rendering quite difficult to make a business layer library, even if I know how to use compile time conditional expressions and how to link those files to avoid having that library at all, i still think all those colliding types should be merged somehow

**Comment by mconnew** [comment]
It's not possible as some of the api shapes are different. There's also the issue of some of the types are used on the client and the server and it would mean polluting the client with server apis and vice versa. For example, BindingElement has CanBuildChannelFactory in the client side, but not on the server. Also the WCF client library api surface is identical to .NET Framework, but the server side has dropped all the APM api's and uses Task's instead.  

In case you aren't aware, CoreWCF supports all the attributes from the WCF client library. So if you add a reference to System.ServiceModel.Primitives to your service project, you can use the attribute `System.ServiceModel.ServiceContract` and the rest of the attributes too. I wouldn't expect a business layer library to reference any WCF or CoreWCF types though. That would normally be in your data layer. The data layer still uses the same DataContract and DataMember types from the runtime so there's no collision there.

If this isn't enough to make things easier for you, could you provide an example of an api which is colliding that you are having a problem with?

**Comment by TrabacchinLuigi** [comment]
Did as you suggested, now everything build fine, yet can't connect to my app. But that's another story, Thanks!
