### ISSUE TITLE
CoreWcf.WebHttp should support System.ServiceModel.Web.Attributes

### ISSUE THREAD

**Issue by arontsang** [CoreWCF/CoreWCF#748]
If CoreWcf is compiled against netstandard2.0 AND framework, it would be possible to have CoreWcf support DotNet Framework `System.ServiceModel.Web.Attributes`.

This would allow for a much more painless transition from dotnet framework to dotnet core.

Developers can run WcfCore on dotnet framework without changing the contracts, allowing for a smoother migration experience.

**Comment by mconnew** [comment]
That wouldn't be required. The current approach for the S.SM.ServiceContract attribute is to get all attributes, check the FQN for the type and if it is the equivalent in the S.SM namespace, we use reflection to get the values. This would work against .NET Framework just as easily as it would against .NET Core as there's no multi-targeting needed.  

If you would like to contribute this compatibility capability, I can point you at our existing code so you can see the pattern and duplicate it for the S.SM.Web attributes in the CoreWCF.WebHttp project. The trickiest part would be writing tests to run only against .NET Framework and not have a compilation issue when compiling against .net6 etc.

**Comment by arontsang** [comment]
@mconnew 

https://github.com/CoreWCF/CoreWCF/blob/33a24198a9e3853413f2d614af73c83273743054/src/CoreWCF.WebHttp/src/CoreWCF/Description/WebHttpBehavior.cs#L299

This does not look like reflection to me...

Sure it could be rewritten to use reflection...

**Comment by mconnew** [comment]
Try reading my comment again.

**Comment by arontsang** [comment]
@mconnew Sorry, had just woken up.

I can try put together a PR after work today.

**Comment by arontsang** [comment]
@mconnew Bumped into a problem.

The mappings are done at `CoreWCF.Description.CustomAttributeProvider, CoreWCF.Primitives` but the Web Attributes live in `CoreWCF.WebHttp`.

**Comment by arontsang** [comment]
https://github.com/CoreWCF/CoreWCF/pull/752

**Comment by arontsang** [comment]
@mconnew any chance you could review my PR again?

**Comment by mconnew** [comment]
Sorry, I have been crazy busy recently. I did look at your PR briefly and there was at least one issue. One problem was checking the assembly name as that is going to be fragile. In the not too distant future we're going to bring WebHttp support to the client side, and when that happens, the attributes will be in a totally differently named assembly. I'll try and take a look later next week. I have another busy week coming up. Feel free to ping again around Thursday next week if you haven't heard anything.
