### ISSUE TITLE
when use scoped dependency injection,visual studio 2022 will consume a lot of CPU

### ISSUE THREAD

**Issue by mbpframework** [CoreWCF/CoreWCF#779]
when I use scoped dependency injection follw the [sample](https://github.com/CoreWCF/samples/tree/main/Scenarios/Logging-and-Dependency-Injection/LoggingSample) ,visual studio 2022 will consume a lot of CPU
![image](https://user-images.githubusercontent.com/6149683/182570502-35810f31-f6e8-4e8c-b1b5-ffd111d12464.png)
I found it was caused by corewcf.buildtools.roslyn4.0，And the more and more complex methods in the service class, the more CPU the analyzer consumes

**Comment by mbpframework** [comment]
I use simple dependency injection to solve this problem ，now it is work well

**Comment by g7ed6e** [comment]
thanks @mbpframework for creating the issue. I'm trying to reproduce 
- were the `ServiceContract` interface and implementations in the same assembly ?
- what is the size of the solution (approximative number of projects, line of codes, interface attributed with `ServiceContract`, dependencies you tried to inject using the Injected attribute) ?
