### ISSUE TITLE
Latest CoreWCF not building, cannot find git directory

### ISSUE THREAD

**Issue by dgxhubbard** [CoreWCF/CoreWCF#79]
Sorry but I pulled down the latest code today using zip file download. Then I extract and build all and get the error "Can't find the .git directory". What am I doing wrong?

`.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error : DirectoryNotFoundException: Can't find the .git directory in 
1>.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 73
1>.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25
1>.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error :    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54
1>.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65
1>.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20
1>.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31
1>.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets(10,9): error :
1>Done building project "CoreWCF.Primitives.csproj" -- FAILED.`

**Comment by BradBarnich** [comment]
The build scripts expect a git checkout, not a zip extract.

**Comment by dgxhubbard** [comment]
Thanks I stumbled my through getting everything setup and it is building now

**Comment by mconnew** [comment]
If you just want to consume CoreWCF, there are packages now available. See the readme.md for details. They aren't signed yet, I'm working on that.
