### ISSUE TITLE
Could not load type 'System.ServiceModel.Description.IWsdlExportExtension' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

### ISSUE THREAD

**Issue by stephen-swensen** [CoreWCF/CoreWCF#802]
I have a 3rd party DLL that was built for .NET Framework 4.x that I am trying to reference from a .NET 6 app that is throwing the following exception:

```
Could not load type 'System.ServiceModel.Description.IWsdlExportExtension' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

I've added references to all of the `CoreWCF` and `System.ServiceModel` nuget packages but the issue remains. Something I notice is that the namespace for `IWsdlExportExtension` is different under the `CoreWCF` implementation than the old .NET Framework 4 implementation... perhaps it's possible to forward this and other types to the new namespace? 

Thanks!

**Comment by FreeAndNil** [comment]
It's not possible to use an .net4 library in a .net6 project.
You should contact the owner of the 3rd party library and request to provide either an .netstandard or .net6 version of the library.

**Comment by stephen-swensen** [comment]
> It's not possible to use an .net4 library in a .net6 project.

Thank you for your response. Actually you can via "Compatibility Mode" but alas there are no guarantees it will work if it is using APIs that weren't ported to .NET 6. I was able to work through the first set of type load errors by adding NuGet `System.ServiceModel.*` package references for the client-side WCF APIs. But got stuck on this server side one.

**Comment by FreeAndNil** [comment]
I know of the "Compatibility Mode", but I would use it only as a last resort.
In this case it is not possible because CoreWCF uses different namespaces than System.ServiceModel.

**Comment by mconnew** [comment]
The compatibility mode provides type forwarding shims from assemblies with the same identity as on .NET Framework to point to the same types with the same signature in the .NET Core implementation. So for example, System.Private.ServiceModel exposes a System.ServiceModel.dll which type forwards to the implementation in System.Private.ServiceModel.dll so when a .NET 4 library loads System.ServiceModel.dll and references for example ChannelFactory, it finds it in System.Private.ServiceModel.dll.  
CoreWCF has a different namespace (CoreWCF.*) which means we can't do this same approach. Even if we were in the same namespace, we couldn't provide our own System.ServiceModel.dll type forwarding facade as there's already one in the client libraries.  
So unfortunately the compatibility mechanism is only going to work for the client API's and as @FreeAndNil suggested, your best option is to contact the library author and ask if they can also target .NET 6 and reference CoreWCF instead.
