### ISSUE TITLE
How to register CoreWCF.Description.IEndpointBehavior implementation?

### ISSUE THREAD

**Issue by WiseSewaTroll** [CoreWCF/CoreWCF#804]
### Discussed in https://github.com/CoreWCF/CoreWCF/discussions/787

<div type='discussions-op-text'>

<sup>Originally posted by **WiseSewaTroll** August  8, 2022</sup>
Hi,
I just started using CoreWCF because we have a lot of WCF SOAP code and are migrating to .net6. I'm using CoreWCF 1.1.0. I have a 
SchemaValidationBehavior that implements **CoreWCF.Description.IEndpointBehavior** (because I needed EndpointDispatcher.DispatchRuntime member). It does schema validation on client and server side for both requests and responses.

```
public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime)
{
    var clientMessageInspector = new SchemaValidationMessageInspector(
        schemaSet,
        validateRequest,
        validateReply,
        isClientSide: true);
    clientRuntime.ClientMessageInspectors.Add(clientMessageInspector);
}

public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher)
{
    var dispatchInspector = new SchemaValidationMessageInspector(
        schemaSet,
        validateRequest,
        validateReply,
        isClientSide: false);
    endpointDispatcher.DispatchRuntime.MessageInspectors.Add(dispatchInspector);
}
```
How can I register this behaviour on my client?
```
var endpointBehavior = new SchemaValidationBehavior(schemaSet, true, true);
client.Endpoint.EndpointBehaviors.Add((System.ServiceModel.Description.IEndpointBehavior)endpointBehavior); // TODO: Cast probably won't work...
```
I even downloaded CoreWCFWithSamples src but must have missed something? 

Thanks for looking into this.</div>

**Comment by g7ed6e** [comment]
CoreWCF brings server side support of WCF features with net6. Regarding client side you should still use System.ServiceModel.* nuget packages. Thus i think you should split your EndpointBehavior having one implementation implementing System.ServiceModel.Description.IEndpointBehavior for client side and another one implementing CoreWCF.Description.IEndpointBehavior for server side.

**Comment by WiseSewaTroll** [comment]
Thanks.

**Comment by HassanBakri** [comment]
Greetings @WiseSewaTroll , @smartnik83 , 
I'm actually in need of this feature, and it's not working, even after trying this [
ClientRuntime.MessageInspectors is internal #209](https://github.com/CoreWCF/CoreWCF/issues/209) suggestion.

any help is welcomed!

**Comment by g7ed6e** [comment]
> Greetings @WiseSewaTroll , @smartnik83 , 
> 
> I'm actually in need of this feature, and it's not working, even after trying this [
> 
> ClientRuntime.MessageInspectors is internal #209](https://github.com/CoreWCF/CoreWCF/issues/209) suggestion.
> 
> 
> 
> any help is welcomed!

Hi @HassanBakri can you share a simple repro?
