### ISSUE TITLE
How to use Config Section Map for WebHttpBinding

### ISSUE THREAD

**Issue by jvnvenu** [CoreWCF/CoreWCF#805]
I have a tried to load a config which has webHttpBinding but it fails to load and gave a error Unrecognized element webHttpBinding

**Comment by mconnew** [comment]
I don't think we have config support for WebHttpBinding yet as the two features were being developed at the same time.

**Comment by mconnew** [comment]
If this is an important scenario to you, I can point you to the relevant place where the implementation needs to be added. It's mostly copying code from .NET Framework with some changes to fit into the new code base.

**Comment by jvnvenu** [comment]
I have made the changes to work but just want to know when can we expect this changes in this repository or is there any option to push those changes here?

**Comment by g7ed6e** [comment]
Hello @jvnvenu. Good to know! You can follow this article to contribute to CoreWCF: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models.
Basic required steps are:
1. Fork the CoreWCF repo in your GitHub account.
2. Clone your CoreWCF fork repository on your local machine.
3. Create a branch and commit your contribution.
4. Push the branch
5. Open a pull request in CoreWCF repo to merge the branch from your fork.
Please notice that once you open the pull request you will have to sign the .NET Foundation CLA to submit your contribution. More details here: https://cla.dotnetfoundation.org/
