### ISSUE TITLE
Missing [AttributeUsage]

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [CoreWCF/CoreWCF#82]
It looks like at least some of the `CoreWCF` attributes lack respective `[AttrbiuteUsage]`.
For instance, [`[ServiceBehavior]`](https://github.com/CoreWCF/CoreWCF/blob/master/src/CoreWCF.Primitives/src/CoreWCF/ServiceBehaviorAttribute.cs) should have `[AttributeUsage(AttributeTarget.Class)]` (like legacy [`ServiceBehaviorAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.servicebehaviorattribute?view=netframework-4.8)).
The same applies to at least one more attribute, [`[OperationBeahvior]`](https://github.com/CoreWCF/CoreWCF/blob/master/src/CoreWCF.Primitives/src/CoreWCF/OperationBehaviorAttribute.cs).

**Comment by mconnew** [comment]
Thank you. Good catch. Thankfully this doesn't stop them being used in the right way. It just doesn't stop them being used in the wrong places. Using them in the wrong place also won't do any harm. I'll fix this next time I'm making any code changes.

**Comment by mconnew** [comment]
@Ilia-Kosenkov, would you be willing to code review my PR #93?

**Comment by Ilia-Kosenkov** [comment]
@mconnew, not sure I have qualification/expertise, but I am happy to help and contribute whatever I can.
