### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by pi343** [CoreWCF/CoreWCF#83]
Hi,

When is the first release planned for CoreWCF? 

Thanks!

**Comment by mconnew** [comment]
Currently waiting for a signing certificate from the dotnet foundation to be able to publish packages to nuget. Then iniitially it will still be an alpha release until I'm happy the basic features have been tested. After which I'll move it to a pre-release label. Might be beta or prerelease. After enough people have tried it out and things are working for them and we've had enough feedback, then it will get a proper release.  
I also need to do some formal stress testing and performance testing before it gets released. I suppose I need to set some release goals. Currently I'm thinking being able to handle at least 50% of the RPS as WCF on the same hardware and being able to scale up to the same number of simultaneous clients. on the same hardware. But I need to get community feedback about that.

**Comment by AndreyTretyak** [comment]
Hi, @mconnew  any update on this one? 
It would very helpful to have at least a prerelease version in nuget.org. 
In my use case, we need to update Service Fabric libraries that provide WCF listeners, they are published to nugget.org so they could not take dependencies from the private feed.

**Comment by mconnew** [comment]
This will be going GA early in the new year, currently planned for late January.
