### ISSUE TITLE
Service type does not implement interface argument exception being thrown

### ISSUE THREAD

**Issue by dgxhubbard** [CoreWCF/CoreWCF#85]
I tried to integrate our older services in CoreWCF and I saw the exception:
"Service type SchedulerService does not implement ISchedulerService"
I commented that out and then our next service threw the same exception.
So I added an empty SchedulerService and the ISchedulerService interface to
NetCoreServer example in CoreWCF (and ITask and SecurityToken).

Then I changed Startup.Configure and replaced EchoService with SchedulerService:
```c#
    builder.AddService<SchedulerService>();
    builder.AddServiceEndpoint<EchoService, ISchedulerService>(new BasicHttpBinding(), "/basichttp");
```
and I was able to reproduce the same exception. What am I doing wrong here.

SchedulerService:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Threading;

namespace NetCoreServer
{
    public class SchedulerService : ISchedulerService
    {
        #region Constructors
        public SchedulerService ()
        {
        }
        #endregion

        #region ISchedulerService Implementation
        public bool Cancel(Guid taskID, string message, SecurityToken securityToken)
        {
            bool res = false;
            return res;
        }

        public bool Cancel(System.Collections.Generic.List<Guid> tasks, string message, SecurityToken securityToken)
        {
            bool res = false;
            return res;
        }

        public Guid Add(ITask task, SecurityToken securityToken)
        {
            Guid res = Guid.Empty;
            return res;
        }

        public ITask Terminate(Guid taskID, string message, SecurityToken securityToken)
        {
            ITask res = null;
            return res;
        }

        public ITask TerminateByName(string taskName, string message, SecurityToken securityToken)
        {
            ITask res = null;
            return res;
        }

        public bool IsTaskQueued(Guid taskID, SecurityToken securityToken)
        {
            bool res = false;
            return res;
        }

        public bool IsTaskQueuedByName(string taskName, SecurityToken securityToken)
        {
            bool res = false;
            return res;
        }

        public TimeSpan GetMinimumWaitTime(SecurityToken securityToken)
        {
            TimeSpan res = TimeSpan.MaxValue;
            return res;
        }

        public List<ITask> GetTasks(SecurityToken securityToken)
        {
            List<ITask> res = null;
            return res;
        }

        public List<ITask> GetRunningTasks(SecurityToken securityToken)
        {
            List<ITask> res = null;
            return res;
        }

        public List<ITask> GetWaitingTasks(SecurityToken securityToken)
        {
            List<ITask> res = null;
            return res;
        }
        #endregion
    }
}
```

ISchedulerScervice:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.ServiceModel;

namespace NetCoreServer
{
    public interface ISchedulerService
    {
        #region Methods
        bool Cancel ( Guid taskID, string message, SecurityToken securityToken );
        bool Cancel ( List<Guid> tasks, string message, SecurityToken securityToken );
        Guid Add ( ITask task, SecurityToken securityToken );
        ITask Terminate ( Guid taskID, string message, SecurityToken securityToken );
        ITask TerminateByName ( string taskName, string message, SecurityToken securityToken );
        bool IsTaskQueued ( Guid taskID, SecurityToken securityToken );
        bool IsTaskQueuedByName( string taskName, SecurityToken securityToken );
        TimeSpan GetMinimumWaitTime ( SecurityToken securityToken );
        List<ITask> GetTasks ( SecurityToken securityToken );
        List<ITask> GetRunningTasks ( SecurityToken securityToken );
        List<ITask> GetWaitingTasks ( SecurityToken securityToken );
        #endregion
    }
}
```

ITask:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace NetCoreServer
{
    public interface ITask 
    {
        #region Properties
        object Tag { get; set; }
        string ActionName { get; }
        DateTime LastRun { get; set; }
        DateTime NextRun { get; set; }
        TimeSpan Timeout { get; set; }
        TimeSpan RunTime { get; set; }
        TimeSpan WaitTime { get; set; }
        DateTime LastCheck { get; set; }
        Guid ID { get; }
        #endregion
    }
}
```

SecurityToken:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace NetCoreServer
{
    public class SecurityToken
    {
        #region Constructors
        public SecurityToken ()
        {
            Id = Guid.NewGuid();
        }
        #endregion

        #region Properties
        public Guid Id { get; set; }
        public object Payload { get; set; }
        #endregion 
    }

    public class BypassToken : SecurityToken
    {}
}
```

**Comment by dgxhubbard** [comment]
There exception is thrown in DispatcherBuilder method
List<IServiceDispatcher> BuildDispatcher<TService>(ServiceConfiguration<TService> serviceConfig, IServiceProvider services) where TService : class.
The serviceHost ReflectedContracts collection is empty.

**Comment by mconnew** [comment]
You still have EchoService as your first generic parameter to AddServiceEndpoint. You need to change that to SchedulerService

**Comment by dgxhubbard** [comment]
My fault I typed that in by hand, here is my startup. It has the parameters correct and produces the exception:

Service type NetCoreServer.SchedulerService doesn't implement interface NetCoreServer.ISchedulerService

**Startup**

`using CoreWCF;
using CoreWCF.Configuration;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;

namespace NetCoreServer
{
    public class Startup
    {
        public void ConfigureServices ( IServiceCollection services )
        {
            services.AddServiceModelServices ();
        }

        public void Configure ( IApplicationBuilder app, IHostingEnvironment env )
        {
            app.UseServiceModel ( builder =>
              {
                  builder.AddService<SchedulerService> ();
                  builder.AddServiceEndpoint<SchedulerService, ISchedulerService> ( new BasicHttpBinding (), "/basichttp" );
              } );
        }
    }
}
`

**Comment by dgxhubbard** [comment]
I know interfaces to do not work with WCF, so I converted ITask to Task and got the same result.

**Comment by mconnew** [comment]
I hope you don't mind, I updated your comments to fix formatting to make things easier to read. When pasting a large chunk of code, start with three backticks followed by the language (e.g. c#, xml) on it's own line, paste the code, then end with three backticks on their own line. E.g.:
\`\`\`c#  
&nbsp;&nbsp;&nbsp;&nbsp;Console.WriteLine("Hello");
\`\`\`  
 Will produce:
```c#
    Console.WriteLine("Hello");
```

I was on my phone so wasn't able to fully read your code. I see the problem now. The problem is with your interface. You don't have a ServiceContract attribute on your interface, and you don't have OperationContract attributes on your methods. E.g.:
```c#
    [CoreWCF.ServiceContract]
    [CoreWCF.ServiceKnownType(typeof(BypassToken))]
    public interface ISchedulerService
    {
        #region Methods
        [CoreWCF.OperationContract]
        bool Cancel(Guid taskID, string message, SecurityToken securityToken);
        [CoreWCF.OperationContract]
        bool Cancel(List<Guid> tasks, string message, SecurityToken securityToken);
        [CoreWCF.OperationContract]
        Guid Add(ITask task, SecurityToken securityToken);
        [CoreWCF.OperationContract]
        ITask Terminate(Guid taskID, string message, SecurityToken securityToken);
        [CoreWCF.OperationContract]
        ITask TerminateByName(string taskName, string message, SecurityToken securityToken);
        [CoreWCF.OperationContract]
        bool IsTaskQueued(Guid taskID, SecurityToken securityToken);
        [CoreWCF.OperationContract]
        bool IsTaskQueuedByName(string taskName, SecurityToken securityToken);
        [CoreWCF.OperationContract]
        TimeSpan GetMinimumWaitTime(SecurityToken securityToken);
        [CoreWCF.OperationContract]
        List<ITask> GetTasks(SecurityToken securityToken);
        [CoreWCF.OperationContract]
        List<ITask> GetRunningTasks(SecurityToken securityToken);
        [CoreWCF.OperationContract]
        List<ITask> GetWaitingTasks(SecurityToken securityToken);
        #endregion
    }
```
You are also going to have problems with BypassToken not being recognized as you only have SecurityToken in your contract. To account for that, I've added the ServiceKnownType attribute to your contract interface. This basically tells WCF that the BypassToken class can also be received on the contract. So when that type arrives in the XML, it knows which CLR type matches the XML namespace and name and will correctly deserialize it where ever you have SecurityToken as a parameter type. See the WCF [documentation here](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.serviceknowntypeattribute?view=netframework-4.8) for more details.

**Comment by dgxhubbard** [comment]
Thank you very much. I was going to ask about the ServiceContract, KnownType and OperationContract. When I looked at the code I did not see anything on EchoService and forgot to look at IEchoService which I should have looked at. Doh! Thanks again.
