### ISSUE TITLE
IIS Hosting not work, erro code 404

### ISSUE THREAD

**Issue by rspulini** [CoreWCF/CoreWCF#866]
I need your help:

I have a traditional WCF service, hosted on IIS, working as a WebService.

Follow the instructions in the link

https://devblogs.microsoft.com/dotnet/corewcf-v1-released/

I configured IIS to support hosting for Asp.NET

Using an example from microsoft, I managed to get the answer "Hello world!". So my IIS is able to host asp.net with coreWCF.

I compiled the sample coreWCF project. I published to a folder. I copied it to the folder in IIS where the application was configured.

But when trying to open the service in the browser, the error 404 appears

I checked the Windows log (event log) there is no error.

Would you help me? I'm using HTTP bindings.

An observation:
In the traditional WCF service, binding configurations were done in web.config. Now the bindings are done in code? I couldn't understand this very well. In this case I use the svc file to configure the service in IIS

Thank you very much.

**Comment by mconnew** [comment]
We have a sample basic service which supports hosting in IIS Express that you [can find here](https://github.com/CoreWCF/samples/tree/main/Basic/Binding/Basic/Http). That should be easy to modify to IIS as it already works in IIS Express. Can you try that as a basis and let me know if that works for you?

**Comment by rspulini** [comment]
Thank you very much.

It worked out!

Excellent job.

________________________________
De: Matt Connew ***@***.***>
Enviado: quinta-feira, 13 de outubro de 2022 16:55
Para: CoreWCF/CoreWCF ***@***.***>
Cc: rspulini ***@***.***>; Author ***@***.***>
Assunto: Re: [CoreWCF/CoreWCF] IIS Hosting not work, erro code 404 (Issue #866)


We have a sample basic service which supports hosting in IIS Express that you can find here<https://github.com/CoreWCF/samples/tree/main/Basic/Binding/Basic/Http>. That should be easy to modify to IIS as it already works in IIS Express. Can you try that as a basis and let me know if that works for you?

**Comment by mconnew** [comment]
Closing as your issue was resolved.
