### ISSUE TITLE
Question: Is it possible to eliminate top-level xml node in the body of envelope?

### ISSUE THREAD

**Issue by szyb** [CoreWCF/CoreWCF#869]
Hi,

I have a legacy WCF service to rewrite to CoreWCF and one of requirements is that the new service should accept the same legacy contract. Basically, the request classes are already mapped and they look as the original, however the envelope body in CoreWCF is adding one top-level node with the same name as name of the operation contract which is missing in legacy service. For instance, let's take a contract from basic template
```C#
  [ServiceContract]
  public interface IService
  {
    [...]
    [OperationContract]
    CompositeType GetDataUsingDataContract(CompositeType composite);
  }
```
The request for such contract (auto generated by SoapUI) looks like this:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:cor="http://schemas.datacontract.org/2004/07/CoreWCFService1">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetDataUsingDataContract>
         <tem:composite>
            <cor:BoolValue>?</cor:BoolValue>
            <cor:StringValue>?</cor:StringValue>
         </tem:composite>
      </tem:GetDataUsingDataContract>
   </soapenv:Body>
</soapenv:Envelope>
```
and I would like to remove from Body the node `<tem:GetDataUsingDataContract>` so it could looks like this:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:cor="http://schemas.datacontract.org/2004/07/CoreWCFService1">
   <soapenv:Header/>
   <soapenv:Body>
       <tem:composite>
          <cor:BoolValue>?</cor:BoolValue>
          <cor:StringValue>?</cor:StringValue>
       </tem:composite>
   </soapenv:Body>
</soapenv:Envelope>
```

Is it possible?

**Comment by szyb** [comment]
It turns out that I've got wrong WSDL file so this question is no longer valid. In the right one there is top-level node, so I'm closing this issue.

**Comment by mconnew** [comment]
FYI (for anyone finding this via a search engine), the way you remove the wrapping element is to create a request object which contains all the parameters you want for your request and attribute that type with `[MessageContractAttribute]`. The following code should produce what you specified:
```c#
[ServiceContract]
public interface IService
{
  [OperationContract]
  CompositeType GetDataUsingDataContract(CompositeType composite);
}

[MessageContract(WrapperName = "composite", WrapperNamespace = "http://tempuri.org/")]
public class CompositeType
{
    [MessageBodyMember(Name = "BoolValue", Namespace = "http://schemas.datacontract.org/2004/07/CoreWCFService1")]
    public bool BoolValue { get; set; }
    [MessageBodyMember(Name = "StringValue", Namespace = "http://schemas.datacontract.org/2004/07/CoreWCFService1")]
    public string StringValue { get; set; }
}
```

If you set the `IsWrapped` property of the `MessageContractAttribute` to `false`, it will also remove the `<tem:composite>` wrapping element.
