### ISSUE TITLE
Add to FaultException a constructor that accepts the TDetail as its only arg

### ISSUE THREAD

**Issue by dgxhubbard** [CoreWCF/CoreWCF#88]
In our old service methods, we use FaultException like so:

```c#
throw new FaultException<Exception> ( ex );
```

However that does not exist in CoreWCF, but it does in System.ServiceModel so in our service implementations we have been using System.ServiceModel so we don't have to change all our 
service methods. Is it possible to add to FaultException a constructor that accepts the TDetail as its only arg?

**Comment by mconnew** [comment]
This is done
