### ISSUE TITLE
How do I use CoreWCF in the generated client?

### ISSUE THREAD

**Issue by ricardoboss** [CoreWCF/CoreWCF#886]
Hi there!

I want to consume a SOAP service using CoreWCF in Blazor.
To get a client generated I use `SvcUtil` and pass the URL to my service WSDL. This client however uses `System.ServiceModel` which I can't use in wasm as it is not supported.

Can you give me a hint how I can use CoreWCF in the SOAP client?

**Comment by g7ed6e** [comment]
@ricardoboss I think you need to take dependency on System.ServiceModel.* nuget packages which are net6.0 compatibles.

**Comment by ricardoboss** [comment]
Hi @g7ed6e! Yes, that's right, I need those. But as I said: MS doesn't support the default Bindings for WASM:
![image](https://user-images.githubusercontent.com/6266356/197575930-9cc3673a-7202-41ea-8d18-7d28a3dacd1d.png)

That's why hoped to find an alternative implementation of `System.ServiceModel.Binding` from CoreWCF that works with .NET Core packages somehow.

**Comment by g7ed6e** [comment]
Interesting. I think you can open an issue in the dotnet/wcf repo to track your need. In the meantime the quickest way to solve this, i think, is to make the server side of you blazor app proxy the call to the WCF service acting as a backend for frontend.

**Comment by ricardoboss** [comment]
I hoped to not re-implement the existing API, as it is quite large, and a rewrite will happen anyway in the future (but not now). Does CoreWPF provide an alternative tool to `SvcUtil.exe` that uses the CoreWCF infrastructure?

**Comment by g7ed6e** [comment]
AFAIK no. What binding is your CoreWCF binding exposing ?

**Comment by g7ed6e** [comment]
Is interop with JavaScript an option ?

**Comment by ricardoboss** [comment]
Yes, but only for fetching data, if this is what you intend to do.

**Comment by g7ed6e** [comment]
Another option would be adding a WebHttpBinding to your service so you can use HttpClient to interact with it.

**Comment by ricardoboss** [comment]
Can you provide an example I can try? If it would help, I can provide an example repository for you to play with.

**Comment by mconnew** [comment]
I've opened an issue in the WCF repo and will fill in some details of what's happening in a comment there. Closing this issue as it's not a problem with CoreWCF.

**Comment by ricardoboss** [comment]
Thanks @mconnew!

**Comment by mconnew** [comment]
I've opened an issue in the runtime repo here: https://github.com/dotnet/runtime/issues/77405
