### ISSUE TITLE
Implement WebSockets with NetHttpBinding

### ISSUE THREAD

**Issue by mconnew** [CoreWCF/CoreWCF#90]

**Comment by Ximik87** [comment]
Hi, I want to try to do this, I already have a test version, but I'm not sure that everything works as it should, most of the code I took from the source code of the .net framework.

**Comment by mconnew** [comment]
I'm sorry, I had forgotten to remove the help wanted tag. I've actually got this work in progress. I had to redo some of the dispatcher logic as I hadn't nailed down the final api pattern (WCF is pull using APM, CoreWCF is all push with chained handlers like ASP.NET Core middleware) and I discovered the pattern I had was insufficient for the WebSockets scenario. I'm nearly done with it.

**Comment by kasajian** [comment]
Will a .NET Framework 4.7.2 based WCF named-pipe server be usable from a client that uses the result of this work?

**Comment by mconnew** [comment]
@kasajian, NetNamePipeBinding is different than NetHttpBinding. Named pipes aren't supported yet. That will be after the initial release as the way ASP.NET Core handles named pipes is different in later versions.
