### ISSUE TITLE
Time to support .net 7 that was released recently

### ISSUE THREAD

**Issue by SychevIgor** [CoreWCF/CoreWCF#903]
Time to support .net 7 that was released recently

**Comment by arontsang** [comment]
What about .net 7 isn't supported?

**Comment by mconnew** [comment]
@arontsang, the WSDL support didn't work. I have released new 1.1.1 and 1.2.1 packages with the fix back ported a couple of days ago. I haven't written up the release notes yet, but it's available on nuget.

**Comment by mconnew** [comment]
Closing this issue, if there's any specific .net7 compatibility problems, please open a new issue for the specific problem.
