### ISSUE TITLE
Wrong logger category in ServiceModelApplicationBuilderExtensions

### ISSUE THREAD

**Issue by mus65** [CoreWCF/CoreWCF#926]
The logger created here in `ServiceModelApplicationBuilderExtensions` should be using `typeof` instead of `nameof`. Currently the "CoreWCF" prefix is missing in the logger category, so the messages here are still logged, even if the logger configuration has a separate log level for CoreWCF.

https://github.com/CoreWCF/CoreWCF/blob/6772206daa830666d29e229924eaea3e458528f8/src/CoreWCF.Primitives/src/CoreWCF/Configuration/ServiceModelApplicationBuilderExtensions.cs#L39

**Comment by g7ed6e** [comment]
Thanks @mus65 for reporting the issue. Would you be able to submit a fix? If not please let me know I will.
