### ISSUE TITLE
no 1.2.1 release note info into this github project ?

### ISSUE THREAD

**Issue by fforjan** [CoreWCF/CoreWCF#933]
Does it mean it was a hacked by someone ? 

I'm picky, but for me it is a bad smell when I see a newer version of  a package in nuget.org but no release info on its project website, I'm always worried it was hacked by someone else ?

**Comment by Koichi-Kobayashi** [comment]
The reason was written here.

https://github.com/CoreWCF/CoreWCF/issues/903#issuecomment-1310665082

**Comment by mconnew** [comment]
I'm sorry, I didn't get them out. The only changes were fixing WSDL as the api's we use in the runtime have changed in .NET 7, and a fix in honoring MaxRecievedMessageSize when using NetTcp streamed mode. I will make sure to not delay release notes in the future, time got away from me this time. I see the importance of them being done immediately now.

**Comment by mconnew** [comment]
Release notes now published. This won't happen again.
