### ISSUE TITLE
Crashes when MaxReceivedMessageSize is increased

### ISSUE THREAD

**Issue by Koichi-Kobayashi** [CoreWCF/CoreWCF#934]
Hi,
NET 4.8 to CoreWCF and thought it was working fine, but now I'm in trouble, please help.

The first problem is that I seem to have sent a large object and received the following error.

> CoreWCF.ProtocolException: The maximum message size quota for incoming messages (65536) has been exceeded. To increase the quota, use the MaxReceivedMessageSize property on the appropriate binding element.
>    at CoreWCF.Channels.HttpInput.ThrowHttpProtocolException(String message, HttpStatusCode statusCode, String statusDescription)
>    at CoreWCF.Channels.HttpInput.ThrowMaxReceivedMessageSizeExceeded()
>    at CoreWCF.Channels.HttpInput.GetMessageBuffer()
>    at CoreWCF.Channels.HttpInput.ReadBufferedMessageAsync(Stream inputStream)
>    at CoreWCF.Channels.HttpInput.ParseIncomingMessageAsync()
>    at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context)
>    at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
>    at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
>    at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I thought this could be solved with MaxReceivedMessageSize as follows.

```C#
var builder = WebApplication.CreateBuilder();
builder.Services.AddServiceModelServices();
//builder.Services.AddServiceModelConfigurationManagerFile("wcf.config");
builder.Services.AddServiceModelMetadata();
builder.Services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();

// debug log
// https://learn.microsoft.com/ja-jp/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0
builder.Logging.AddConsole();

var app = builder.Build();

app.UseServiceModel(serviceBuilder =>
{
    serviceBuilder.AddService<ServiceFacade>();
    var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
    binding.MaxReceivedMessageSize = 100000;     <------------------------------------------------------ This way.
    serviceBuilder.AddServiceEndpoint<ServiceFacade, IServiceFacade>(binding, "/Service.svc");
});

var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
serviceMetadataBehavior.HttpsGetEnabled = true;

app.Run();
```

However, increasing the MaxReceivedMessageSize causes the server to crash.
Here is the location of the crash.

System.Private.CoreLib\src\System\Runtime\CompilerServices\ConfiguredValueTaskAwaitable.cs
```C#
    /// <summary>Provides an awaitable type that enables configured awaits on a <see cref="ValueTask{TResult}"/>.</summary>
    /// <typeparam name="TResult">The type of the result produced.</typeparam>
    [StructLayout(LayoutKind.Auto)]
    public readonly struct ConfiguredValueTaskAwaitable<TResult>
    {
        /// <summary>The wrapped <see cref="ValueTask{TResult}"/>.</summary>
        private readonly ValueTask<TResult> _value;

        /// <summary>Initializes the awaitable.</summary>
        /// <param name="value">The wrapped <see cref="ValueTask{TResult}"/>.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal ConfiguredValueTaskAwaitable(in ValueTask<TResult> value) => _value = value;

        /// <summary>Returns an awaiter for this <see cref="ConfiguredValueTaskAwaitable{TResult}"/> instance.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ConfiguredValueTaskAwaiter GetAwaiter() => new ConfiguredValueTaskAwaiter(in _value);

        /// <summary>Provides an awaiter for a <see cref="ConfiguredValueTaskAwaitable{TResult}"/>.</summary>
        [StructLayout(LayoutKind.Auto)]
        public readonly struct ConfiguredValueTaskAwaiter : ICriticalNotifyCompletion, IStateMachineBoxAwareAwaiter
        {
            /// <summary>The value being awaited.</summary>
            private readonly ValueTask<TResult> _value;

            /// <summary>Initializes the awaiter.</summary>
            /// <param name="value">The value to be awaited.</param>
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal ConfiguredValueTaskAwaiter(in ValueTask<TResult> value) => _value = value;

            /// <summary>Gets whether the <see cref="ConfiguredValueTaskAwaitable{TResult}"/> has completed.</summary>
            public bool IsCompleted
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => _value.IsCompleted;
            }

            /// <summary>Gets the result of the ValueTask.</summary>
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult GetResult() => _value.Result;    <-------------------------------------------- This way.
            ...
```

How should I deal with this?
I look forward to hearing from you.

The development environment is as follows
Windows 11 Pro 22H2 (22621.900)
Microsoft Visual Studio Professional 2022 (64 bit) - Current Version 17.4.2
.NET 6.0.11
CoreWCF 1.2.1 (nget)

**Comment by mconnew** [comment]
The property you set should be the correct way to solve this. The class you linked to is part of the async/await infrastructure of the runtime and is just how an exception in a Task is retrhown so doesn't point to the underlying problem. Can you provide the call stack and exception message that causes the app to crash.  
By crash, do you mean the entire process exits or are you talking about an individual request failing?

**Comment by Koichi-Kobayashi** [comment]
Sorry.
After much trial and error, we found that there is an error in the way DataMember is specified.
The crash was caused by the DataMember attribute being attached to a member variable and a property, and then specifying itself in the set accessor of the property.

This matter has been Resolved.
