### ISSUE TITLE
How to define Identity when create client with ssl

### ISSUE THREAD

**Issue by torgashov** [CoreWCF/CoreWCF#944]
Hello!
When i use ChannelFactory to create proxy for request to wcf service on https://test.mydomain.com/test.svc with ssl (Security transport with certificate), i get error :
The expected identity of the remote endpoint in DNS (test.mydomain.com) does not match the DNS requirement specified by the remote endpoint (*.mydomain.com).
In certificate i see subject alternative name:
DNS *.mydomain.com
How can i create client with define identity?
And why identity validation can not check host/dns/identity in certificate by asterik?
If i create certificate with SAN test.domain.com request complete succcess.
Should i override some IdentityValidator?

**Comment by mconnew** [comment]
This is a client issue. Can you open this issue in the http://github.com/dotnet/wcf repo where the WCF client lives.
