### ISSUE TITLE
AuthorizeAttribute not working as expected

### ISSUE THREAD

**Issue by joecuevasjr** [CoreWCF/CoreWCF#953]
I've set up Authorization in a CoreWCF sample application and it appears service methods fully run before the Authorize Attribute check occurs. This issue occurs with the following attributes in my sample: `[Authorize(Policy = ("Read"))]`, `[Authorize("Read")]`, and `[Authorize]`. 

Snippets of setup: 
NET 7.0 (also 6.0)
CoreWCF.Http 1.3.0
CoreWCF.Primitives 1.3.0

Program.cs
````c#
 // Microsoft.Identity.Web v2.0.8-preview
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration);

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("Read", policy => policy
    .RequireClaim(ClaimTypes.Role, new[] { "Service.Read" }));
});
````
IService.cs
````c#
[Authorize(Policy = ("Read"))]
//[Authorize("Read")]
//[Authorize]
public string GetData(int value)
{
    DoSomething();
    return string.Format("You entered: {0}", value);
}
````
Client code
````c#
var client = new CoreWCF.ServiceClient();
var httpRequestProperty = new HttpRequestMessageProperty();
httpRequestProperty.Headers[HttpRequestHeader.Authorization] = $"Bearer {accessToken}";

var context = new OperationContext(client.InnerChannel);
using var _ = new OperationContextScope(context);
context.OutgoingMessageProperties[HttpRequestMessageProperty.Name] = httpRequestProperty;
Result = await client.GetDataAsync(1000);
````
Prerequisite: Pass in an invalid JWT token

Expected outcome: `MessageSecurityException` at the client side without `GetData()` executing in `IService.cs`.
Actual outcome: `MessageSecurityException` at the client side **after** `DoSomething()` and `return` statement are executed within `GetData()` in `IService.cs`.

This behavior can be troublesome when trying to protect endpoints that manipulate persisted data.
Is this the intended behavior of CoreWCF?

As a workaround, I do this to avoid the issue:
````c#
public string GetData(int value)
{
    /* Accessing the httpContext.User property seems to trigger an exception 
       of type System.ObjectDisposedException when the JWT token is invalid 
       or missing the required policy, which eventually returns the 
       `MessageSecurityException` when the method exits.
    */
    var httpContext = OperationContext.Current.IncomingMessageProperties["Microsoft.AspNetCore.Http.HttpContext"] as HttpContext;
    if (httpContext.User.Identity.IsAuthenticated == false) throw new UnauthorizedAccessException();

    return string.Format("You entered: {0}", value);
}
````
Note: Using a valid token at the service method executes the policy as expected, without issues.

Edit: Updated the sample code.

**Comment by g7ed6e** [comment]
Thanks @joecuevasjr for reporting issue. 
Did you set ClientCredentialType to InheritedFromHost ? Please see there to configure the binding https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/tests/Authorization/AuthorizationIntegrationTests.Startup.cs

**Comment by joecuevasjr** [comment]
> Thanks @joecuevasjr for reporting issue. Did you set ClientCredentialType to InheritedFromHost ? Please see there to configure the binding https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/tests/Authorization/AuthorizationIntegrationTests.Startup.cs

Yes, here's the setup:

````c#
app.UseServiceModel(serviceBuilder =>
{
    serviceBuilder.AddService<Service>();
    serviceBuilder.AddServiceEndpoint<Service, IService>(new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.InheritedFromHost
            }
        }
    }, "/Service.svc");
    var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    serviceMetadataBehavior.HttpsGetEnabled = true;
});
````

**Comment by joecuevasjr** [comment]
I forgot to mention, this happens on both NET 7.0 and 6.0.

**Comment by g7ed6e** [comment]
> I forgot to mention, this happens on both NET 7.0 and 6.0.

Thanks I will investigate.

**Comment by g7ed6e** [comment]
@joecuevasjr I reproduced the issue.

**Comment by joecuevasjr** [comment]
> @joecuevasjr I reproduced the issue.

Excellent! I see that there's a PR to address the issue. Thanks for looking into it.

**Comment by g7ed6e** [comment]
> > @joecuevasjr I reproduced the issue.
> 
> 
> 
> Excellent! I see that there's a PR to address the issue. Thanks for looking into it.

This should have been the first test I wrote for this feature..

**Comment by joecuevasjr** [comment]
@g7ed6e 

I've tested v1.3.1 and can confirm the original issue is resolved. 
However, say I add the following method to the `IService.cs` code snippet on my original post.

````csharp
public string GetDataWithNoAuth(int value)
{
    return value;
}
````
Then If I try the following:

````csharp
// CoreWCF service
var client = new ServiceClient();

// Call an endpoint that doesn't have an Authorization attribute
var noAuthResult = await client.GetDataWithNoAuth(1000);
````

The call to client.GetDataWithNoAuth() fails with the following error: `MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer'.`

It also fails when I add the `[AllowAnonymous]` attribute to the GetDataWithNoAuth() service endpoint.

Essentially, it seems that by adding the "AddAuthentication" service to the CoreWCF WebApplicationBuilder ServiceCollection registrations, all endpoints implicitly require Authorization. Is that the intended workflow with Authorization in CoreWCF?

**Comment by g7ed6e** [comment]
@joecuevasjr  When the security mode is set to `Transport` or `TransportCredentialOnly` and ClientCredentialType is set to `InheritedFromHost`, CoreWCF calls `AuthenticateAsync` with the default configured AuthenticationScheme which means that the Service will require an authenticated to process the message.
Regarding `[AllowAnonymous]` attribute we decided not to support it to avoid a non authenticated request going too far in the request pipeline. please notice a COREWCF_0200 warning is issued when `[AllowAnonymous]` is set on an operation contract implementation.
Adding @mconnew

**Comment by joecuevasjr** [comment]
@g7ed6e Thank you for the clarification.

**Comment by mconnew** [comment]
@joecuevasjr, the solution to have a mix of authenticated and unauthenticated requests in a service is to have 2 interfaces, one which requires authentication for all the methods, and one which doesn't. You can have a single service implement both interfaces and add 2 endpoints with 2 bindings. You configure one endpoint binding to use InheritedFromHost, and the other to use a client credential type of None. That way you can have clients connect to one endpoint for methods which require authentication, and another client connect to the unauthenticated endpoint for methods which are okay to call unauthenticated.  
I think you should also be able to keep things simple for clients which will be authenticating by having the authenticated interface derive from the unauthenticated one so that unauthenticated methods can also be called from the authenticated client. E.g:
```c#
[ServiceContract]
public interface IUnauthenticated
{
    [OperationContract]
    DateTime GetTodaysDate();
}

[ServiceContract]
public interface IAuthenticated : IUnauthenticated
{
    [OperationContract]
    Customer GetCustomer(int customerId);
}

app.UseServiceModel(serviceBuilder =>
{
    serviceBuilder.AddService<Service>();
    serviceBuilder.AddServiceEndpoint<Service, IUnauthenticated>(new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.None
            }
        }
    }, "/Service.svc/noauth");
    serviceBuilder.AddServiceEndpoint<Service, IAuthenticated>(new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.InheritedFromHost
            }
        }
    }, "/Service.svc/auth");
    var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    serviceMetadataBehavior.HttpsGetEnabled = true;
});
```
You could create an authenticated client which connects to `/Service.svc/auth` and can call `GetTodaysDate` and `GetCustomer`, but if you create a client which connects to `/Service.svc/noauth`, you will only be able to call `GetTodaysDate`. This is how you would achieve mixed authentication in WCF.  

@g7ed6e, do you think it's worth calling this out as a solution (with an example) in the blog post?

The problem with allowing authenticated and unauthenticated calls on a single endpoint is that an unauthenticated client can potentially cause a lot of work to be done by the service in preparation of dispatching the call before we discover that authentication is needed. The reason for this is the IOperationSelector interface is used to decide which operation is being called. We don't know which operation is being called before this interface is used, so we wouldn't know if there's a requirement for the call to be authenticated. The IOperationSelector method could potentially trigger a full deserialization of the incoming message (it doesn't by default, but it's extensible and I've seen at least one real world example of that being done) which can result in a lot of memory allocation.

**Comment by joecuevasjr** [comment]
@mconnew This seems like a great solution, but I don't think it's working as expected and I'm not sure if this is a Visual Studio issue or if I'm simply misusing the service URI. I tried testing it out, with the same "UseServiceModel" middleware lambda you provided as well as the usage of the `IUnauthenticated` and `IAuthenticated` interfaces, with the authenticated interface deriving from the unauthenticated one. 

````csharp
[ServiceContract]
public interface IUnauthenticated
{
    [OperationContract]
    DateTime GetTodaysDate();
}

[ServiceContract]
public interface IAuthenticated : IUnauthenticated
{
    [OperationContract]
    string GetData(int value);
    
    // Removed GetDataUsingDataContract() for brevity
}

public class Service : IAuthenticated
{
    public string GetData(int value)
    {
        return string.Format("You entered: {0}", value);
    }

    public DateTime GetTodaysDate()
    {
        return DateTime.Now;
    }
}
````

````csharp
app.UseServiceModel(serviceBuilder =>
{
    serviceBuilder.AddService<Service>();
    serviceBuilder.AddServiceEndpoint<Service, IUnauthenticated>(new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.None
            }
        }
    }, "/Service.svc/noauth");
    serviceBuilder.AddServiceEndpoint<Service, IAuthenticated>(new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.InheritedFromHost
            }
        }
    }, "/Service.svc/auth");
    var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    serviceMetadataBehavior.HttpsGetEnabled = true;
});
````

If I add a new WCF Web Service service reference to a project in Visual Studio Professional v17.4.3:

When I first specify the `/Service.svc/auth` `URI`, the service reference screen shows the following prompt:
![image](https://user-images.githubusercontent.com/82356181/211419608-7a8a8e37-a8f7-49fe-9066-25e11a10d00e.png)

But If I specify the `URI` to be  `/Service.svc/noauth` I get both Services available: `IUnauthenticated`, and `IAuthenticated`.

![image](https://user-images.githubusercontent.com/82356181/211419483-6389cab0-5d26-4090-843c-ca924e9b0981.png)

My expectations for `/auth` would be to only see the `IAuthenticated` Service, and `/noauth` would should only the `IUnauthenticated` Service.

If I modify the endpoint config and only specify the authenticated endpoint by removing the unauthenticated endpoint, everything works as expected:
![image](https://user-images.githubusercontent.com/82356181/211420563-06cbc349-4e6b-4671-9473-744c9c9e1c82.png)

**Comment by joecuevasjr** [comment]
Tagging @g7ed6e for some feedback on my last comment.

**Comment by mconnew** [comment]
That is expected. It only uses the first endpoint url as we don't really have the same concept of base address that exists in WCF. We have a heuristic where we guess what's a sensible place if you don't explicitly specify which basically picks the first http url. You can set an explicit BaseAddress like this:
```c#
serviceBuilder.AddService<Service>(serviceOptions => 
    { 
        serviceOptions.BaseAddresses.Add(new Uri("https://localhost/Service.svc")); 
    });
```
Then in the `AddServiceEndpoint` calls, you remove "/Service.svc" in the path and use just `"auth"` and `"noauth"`. This will result in the wsdl being available at https://localhost/Service.svc.

**Comment by joecuevasjr** [comment]
Thanks @g7ed6e @mconnew. Using an explicit `BaseAddress` is an effective resolution to move the metadata up to the appropriate address.

Here's my final configuration with added support for Kestrel, IIS, and IIS Express scenarios (HTTPS only).

````csharp
app.UseServiceModel(serviceBuilder =>
{
    serviceBuilder.AddService<Service>(serviceOptions =>
    {
        const string svcName = "Service.svc";
        if (app.Configuration["ASPNETCORE_HOSTINGSTARTUPASSEMBLIES"].Contains("Microsoft.AspNetCore.Server.IIS"))
        {
            // IIS integration
            var appPath = app.Configuration["ASPNETCORE_APPL_PATH"];
            serviceOptions.BaseAddresses.Add(new Uri($"https://localhost{appPath}/{svcName}"));
        }
        else 
        {
            // Kestrel and IIS Express integration
            var baseUrl = app.Configuration["ASPNETCORE_URLS"].Split(";").First();
            serviceOptions.BaseAddresses.Add(new Uri($"{baseUrl}/{svcName}"));
        }
    });
    serviceBuilder.AddServiceEndpoint<Service, IUnauthenticated>(new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.None
            }
        }
    }, "noauth");
    serviceBuilder.AddServiceEndpoint<Service, IAuthenticated>(new BasicHttpBinding
    {
        Security = new BasicHttpSecurity
        {
            Mode = BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity
            {
                ClientCredentialType = HttpClientCredentialType.InheritedFromHost
            }
        }
    }, "auth");
    var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    serviceMetadataBehavior.HttpsGetEnabled = true;
});
````
