### ISSUE TITLE
WindowsClaimSet

### ISSUE THREAD

**Issue by WiseSewaTroll** [CoreWCF/CoreWCF#966]
### Discussed in https://github.com/CoreWCF/CoreWCF/discussions/965

<div type='discussions-op-text'>

<sup>Originally posted by **WiseSewaTroll** January  2, 2023</sup>
Hi,

I have a wcf service with a custom binding with usernameovertransport using soap11. When authenticated i get a WindowsClaimSet for the user.

How do i need to configure this using a CoreWCF host?

So ultimately I would like:
- this to be populated: Operationcontext.Current.SecurityContext.PrimaryIdentity.Name.
- and I would like to get an exception when invalid windows credentials are passed.
wssecurity FailedAuthentication SoapFaultException when security tokens could not be validated.

Kind regards</div>

**Comment by mconnew** [comment]
This would require the class [WindowsUserNameSecurityTokenAuthenticator](http://index/?leftProject=System.IdentityModel&leftSymbol=ykr5wkkyozdo&file=System%5cIdentityModel%5cSelectors%5cWindowsUserNameSecurityTokenAuthenticator.cs) which we haven't ported as it can't be implemented in a cross platform way as it uses P/Invoke calls to win32 api's. It should be possible to copy this into your own application and wire it up. Can you provide a bit more info about what binding you are using as it's possible there's a couple of other pieces missing depending on your exact scenario. Are you using SecurityMode.TransportWithMessageCredentials (which would require a token serializer that I'm not sure if it's present or not), or are you using SecurityMode.Transport which would require transport integration to create the security token (which can be worked around with a small change to that class).

**Comment by WiseSewaTroll** [comment]
Hi, 
Thanks for the response. That would be great if we could get a working Win-only solution. 

This is our custom binding:

```
CustomBinding customBinding = new CustomBinding();

              var sbe = SecurityBindingElement.CreateUserNameOverTransportBindingElement();
              sbe.IncludeTimestamp = false;

              customBinding.Elements.Add(sbe);

              var tme = new TextMessageEncodingBindingElement()
              {
                  MaxReadPoolSize = 64,
                  MaxWritePoolSize = 16,
                  MessageVersion = MessageVersion.Soap11,
                  WriteEncoding = Encoding.UTF8,
                  ReaderQuotas = new XmlDictionaryReaderQuotas()
              };

              var largeNumber = 2147483647;
              tme.ReaderQuotas.MaxArrayLength = largeNumber;
              tme.ReaderQuotas.MaxBytesPerRead = largeNumber;
              tme.ReaderQuotas.MaxDepth = 32;
              tme.ReaderQuotas.MaxNameTableCharCount = 16384;
              tme.ReaderQuotas.MaxStringContentLength = largeNumber;

              customBinding.Elements.Add(tme);

              customBinding.Elements.Add(new HttpsTransportBindingElement()
              {
                  TransferMode = TransferMode.Buffered,
                  ManualAddressing = false,
                  MaxBufferPoolSize = largeNumber,
                  MaxReceivedMessageSize = largeNumber,
                  MaxBufferSize = largeNumber,
                  AuthenticationScheme = AuthenticationSchemes.Anonymous,
                  KeepAliveEnabled = true,
                  Realm = string.Empty,
                  RequireClientCertificate = false,
              });

              return customBinding;
```
This should be the equivalent of UserNameOverTransport with httpsTransport (the old WCF configuration).

**Comment by mconnew** [comment]
The good news is that you don't need any http transport integration, which means I believe this should be solvable for you without shipping any product changes. I believe you need to provide your own derived ServiceCredentials class which provides your own derived ServiceCredentialsSecurityTokenManager. Then in CreateSecurityTokenAuthenticator, you will provide the logic which would [execute this commented out code](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Primitives/src/CoreWCF/Security/ServiceCredentialsSecurityTokenManager.cs#L358).  You replace the ServiceCredentials class on the ServiceHostBase using the ConfigureServiceHostBase method. Basically you remove the existing ServiceCredentials instance from ServiceHostBase.Description.Behaviors and add your own.  
Let me know if that's enough information to unblock you.

**Comment by WiseSewaTroll** [comment]
Hi,
Thanks for the reply,
I looked around in the github repo sourcecode and found some problems concerning your suggestions:
- The ServiceCredentialsSecurityTokenManager is internal. Should I copy it?
- The commented line news a WindowsUserNameSecurityTokenAuthenticator, which isn't in the sourcecode.

Please advise.

Kind regards,

**Comment by mconnew** [comment]
You don't need to copy it. You can encapsulate it instead. Do something like this:
```c#
public class CustomServiceCredentials : ServiceCredentials
{
    public override SecurityTokenManager CreateSecurityTokenManager()
    {
        return new CustomSecurityTokenManager(base.CreateSecurityTokenManager());
    }
}

public class CustomSecurityTokenManager : SecurityTokenManager
{
    private readonly  SecurityTokenManager _innerManager;

    public CustomSecurityTokenManager(SecurityTokenManager innerManager)
    {
        _innerManager = innerManager;
    }

    public override SecurityTokenProvider CreateSecurityTokenProvider(SecurityTokenRequirement tokenRequirement)
    {
        return _innerManager.CreateSecurityTokenProvider(tokenRequirement);
    }

    public override SecurityTokenSerializer CreateSecurityTokenSerializer(SecurityTokenVersion version)
    {
        return _innerManager.CreateSecurityTokenSerializer(version);
    }

    public override SecurityTokenAuthenticator CreateSecurityTokenAuthenticator(SecurityTokenRequirement tokenRequirement, out SecurityTokenResolver outOfBandTokenResolver)
    {
        if ( /* tokenRequirement is the one we want */)
        {
            outOfBandTokenResolver = null;
            return CustomWindowsUsernameTokenAuthenticator(); // Copied from framework
        }
        return _innerManager.CreateSecurityTokenProvider(tokenRequirement, out outOfBandTokenResolver);
    }
}
````

You can get a copy of `WindowsUserNameSecurityTokenAuthenticator` [here](https://github.com/microsoft/referencesource/blob/master/System.IdentityModel/System/IdentityModel/Selectors/WindowsUserNameSecurityTokenAuthenticator.cs). It's MIT licensed so you're free to incorporate it into your code.

**Comment by WiseSewaTroll** [comment]
Hi,
Thanks for the clear example. But, I need this to be a net6.0 solution. So working System.IdentityModel types in WindowsUserNameSecurityTokenAuthenticator is not gonna work. Any ideas?

Kind regards,

**Comment by mconnew** [comment]
A lot of the types now exist in CoreWCF.IdentityModel. There's some code in helper classes you will need to copy. For example UnconditionalPolicy. There's some code in UnconfitionalPolicy that you can't copy as it references internal types. You can get away without that code, but it's going to take a bit of explaining what it does and why it's there so you understand the risks (short answer is it stops you from hurting your security if you do stupid things).  

The internal types are used for cloning the policy and cloning the WindowsClaimSet. This is done for a couple of related reasons. The scenario where it's cloned is when using WS-SecureConversation (which is used by default with TransportWithMessageCredentials and is controlled by the EstablishSecurityContext property on SecurityBindingElement). The reason it's cloned is that the WindowsClaimSet (and authorization policy) is created on an intital open handshake where a session is created and the session token is returned to the client. When the client makes an actual service request, it uses the session token, and the service uses that to lookup the authorization policy and claimset previously authenticated to associate with the request. It clones this cached session data so that the original doesn't get modified. ClaimsSet's are mutable so you could in theory modify it in a service. If it wasn't cloned, then you would be modifying the persistent cached copy. It ensures that you can't shoot yourself in the foot if you modify a mutable claimset. For example, if you had code which for some reason cleared out all the claims from the ClaimSet, if it wasn't a cached copy, all subsequent calls could fail during authorization. You could lose your principal identity and fail to impersonate in your service call.  

You should be good copying UnconditionalPolicy, and removing the IDisposable interface on it. Take out the code which clones a WindowsClaimSet and just store the original passed in instance. In any custom authorization code or in your service implementation, don't modify the WindowsClaimSet as any changes will get persisted to subsequent calls.

**Comment by WiseSewaTroll** [comment]
Hi,

Thanks for the thorough explanation. Appreciated. But, this is going to take too much custom code than we would like. 

So...we are going for a custom usernamepassword validation. Getting rid of the windows account requirement was also seen as an advantage. 

Almost works as expected. Our returned ValueTask.FromException(notAuthenticatedFaultException) in UserNamePasswordValidator.ValidateAsync causes a CoreWCF.Security.MessageSecurityException: Message security verification failed. It has an inner exception we were only hoping to see. How do we get rid of that MessageSecurityException? 

Already tried EnableUnsecuredResponse on the SecurityBindingElement. Is it required to set a certificate on the ServiceCredentials behaviour? The responses from our CoreWCF endpoints running in Kestrel behind IIS do get encrypted. Kestrel is running behind IIS under https.

```
"@x": "CoreWCF.Security.MessageSecurityException: Message security verification failed.
 ---> CoreWCF.FaultException`1[ZorgNed.WCFWebservices.Std.Core.FaultExceptionDetails.NietGeautoriseerdFaultDetail]: Niet geautoriseerd. De foutdetails zijn op de server in de logging terug te vinden met de code 583dc47b-8d06-4b3c-a2c4-0f55b46caa07. (Fault Detail is equal to ZorgNed.WCFWebservices.Std.Core.FaultExceptionDetails.NietGeautoriseerdFaultDetail).
   --- End of inner exception stack trace ---
   at async ValueTask<Message> CoreWCF.Security.TransportSecurityProtocol.VerifyIncomingMessageAsync(Message message, TimeSpan timeout)
   at async ValueTask<ValueTuple<Message, SecurityProtocolCorrelationState>> CoreWCF.Security.SecurityProtocol.VerifyIncomingMessageAsync(Message message, TimeSpan timeout, params SecurityProtocolCorrelationState[] correlationStates)
   at async ValueTask<ValueTuple<Message, SecurityProtocolCorrelationState>> CoreWCF.Dispatcher.ServerSecurityChannelDispatcher<UChannel>.VerifyIncomingMessageAsync(Message message, TimeSpan timeout, params SecurityProtocolCorrelationState[] correlationState)
   at async ValueTask<RequestContext> CoreWCF.Dispatcher.SecurityReplyChannelDispatcher.ProcessReceivedRequestAsync(RequestContext requestContext) x 2
   at async Task CoreWCF.Dispatcher.SecurityReplyChannelDispatcher.DispatchAsync(RequestContext context)
   at async Task CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context)
   at async Task CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
   at async Task CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at async Task Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at async Task Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at async Task Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at async Task ZorgNed.WebService.CoreWCFServices.Middlewares.CoreWCFRequestLoggingMiddleware.Invoke(HttpContext httpContext) in C:/repos/ZorgNedMain/Product/WMONED/_Apps/ZorgNed.WebService/CoreWCFServices/Middlewares/CoreWCFRequestLoggingMiddleware.cs:line 38
   at async IApplicationBuilder ZorgNed.WebService.Areas.Extensions.WebApplicationExtensions.UseControllerLogging(IApplicationBuilder app)+(?) => { } in C:/repos/ZorgNedMain/Product/WMONED/_Apps/ZorgNed.WebService/Areas/Extensions/WebApplicationExtensions.cs:line 28
   at async Task<bool> Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT<TContext>.ProcessRequestAsync()",
```

Kind regards,

**Comment by WiseSewaTroll** [comment]
I had the exact same issue with the [https://github.com/CoreWCF/samples/tree/main/Basic/Binding/WS/WsHttpUserPassword_server] project. And created an issue there. So, therefore, closing this one.
