### ISSUE TITLE
Transferring large amounts of data quickly

### ISSUE THREAD

**Issue by ctechid** [CoreWCF/CoreWCF#968]
What is the best scenario for transferring large amounts of data quickly? 

I read 1500 lines of rows from WCF Service which listening on local host, it takes 14 seconds. 
I used WsHttp with None Message credential type.

Thanks

**Comment by mconnew** [comment]
What type of data are you transferring? How large are we talking about? Does the data lend itself to an IEnumerable style return type? From a networking standpoint how far apart will the client and server be? For example, will they always be on the same machine? Or will it eventually transfer across the internet? Do you care more about time to first data item or total transfer time? What type of authentication/security do you need?  
 
Some general guidelines, any binding that starts with `Net` will be faster as it uses a binary XML encoding. WSHttp only uses the cross platform cross stack interoperable SOAP standards so can't take advantage of some performance features which you can use if you have .NET at both ends.  

If time to get all the data is most important, the size isn't prohibitive, and the data is fast to put together on the service side, then use buffered transfer mode (the default). If the amount of data will be large, and it's structured (not just a stream of bytes), then use streamed transfer mode with an IEnumerable\<MyDataType\> as the return type. For streamed mode transfer with any security, I would generally recommend NetHttpBinding as NetTcpBinding does a fresh security handshake for every single request with streamed mode. NetHttpBinding just uses the HttpClient/asp.net core connection reuse so you only do the SSL/TLS handshake one a new client connection once. For buffered mode, NetTcpBinding is generally the best. I can't tell you more than that without more information as I would need to write basically a mini whitepaper to cover all the variables in a general way.

**Comment by ctechid** [comment]
Thanks for point out.

The C# desktop Clients reads the database on the C# desktop Server via the WCF service.

The amount of data sent from the server to the client is tens of thousands to millions of lines.

Server and Client are located on separate machines and connected via the internet. Client more than one. 
On the server side, I use the tunnel service, so private IP can be accessed from the internet via the domain provided by the tunnel provider.

The need to be able to transfer quickly with large data.

Security can use a certificate.

**Comment by mconnew** [comment]
I would recommend using NetHttpBinding specifying at least `TransferMode.StreamedResponse` (sends the request buffered, the response streamed), although there's probably little harm in just using `TransferMode.Streamed` (buffer handling on the service side is slightly less efficient when the request isn't actually a streamable type like IEnumerable or Stream but will be negligable if the request message itself is small).  
I would make the return type `IEnumerable<MyDataType>`. Just make sure you return an instance which doesn't gather all the data up front (e.g. put the response into a `List<MyDataType>`) but returns an instance which generates the data as you iterate over it. This should cause the service to return the response headers, return the body start, then take the IEnumerable and call `HasNext()` (which should trigger generating the next data item) and then serialize the `.Current` object into XML and send it to the client. Then it calls `HasNext()` again and repeats until `HasNext()` returns false.  
This should allow you to have minimal memory allocation on the service side as we only buffer one row at a time which will scale to millions of rows without extra overhead. You will start getting your data as soon as the first row is available.  

Having said this, have you looked into using OData instead? It might be a better fit as it's purpose is to effectively remote data access? Another option is to use gRPC with streaming responses. It's a bit more code you need to write than you would with WCF, but gRPC does serialize and deserialize to a smaller payload and is a bit faster at it. It's a trade off between how much boiler plate code you need to write and raw performance. [Here's an interesting blog post](https://devblogs.microsoft.com/odata/tutorial-build-grpc-odata-in-asp-net-core/) about making OData work across gRPC. You can see there the concept of a repeated response in the gRPC response definition which translates to returning an IEnumerable and functions in a similar way as WCF's IEnumerable support works. [Here's another simpler](https://www.stevejgordon.co.uk/server-streaming-with-grpc-in-asp-dotnet-core) (no OData) example showing how you would return a stream of objects to the client.

WCF excels at complicated object models and non-trivial call patterns, but I think this might be a scenario where gRPC is the best solution.

**Comment by ctechid** [comment]
Thanks for point out
