### ISSUE TITLE
 The remote server returned an unexpected response: (400) Bad Request

### ISSUE THREAD

**Issue by ctechid** [CoreWCF/CoreWCF#975]
Hi,

I use wsHttp to access data via wcf service, the program works normally when the amount of data is small.

I get an error message when accessing large amounts of data as below, what is the solution?
Thank you.

> DiscountCard System.ServiceModel.ProtocolException: The remote server returned an unexpected response: (400) Bad Request. at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateResponseStatusCode() at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper) at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper) at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout) at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout) at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task) at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout) at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs) at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) at generatedProxy_1.ReadCustomers(String) at DiscountCard.Models.Model.ReadCustomers(String sortExpression)

Best Regards,
Nur

**Comment by mconnew** [comment]
Have you increased the MaxReceivedMessageSize on the service side binding?

**Comment by ctechid** [comment]
Thank you, now it works normally. 

I am using WSHttpBinding with listen and connect, it takes 106 seconds to read 91.144 characters.
I run Server and Client with background thread in local host (same machine between server and client).
