### ISSUE TITLE
404 when set ClientCredentialType not None

### ISSUE THREAD

**Issue by kamyaw010** [CoreWCF/CoreWCF#976]
The Service file is very easy, just is the sample code:
```C#
namespace Service {
    [ServiceContract]
    public interface ITestService {
        [OperationContract]
        string GetData(int value);

        [OperationContract]
        CompositeType GetDataUsingDataContract(CompositeType composite);
    }

    public class TestService : ITestService {

        public string GetData(int value) {
            return string.Format("You entered: {0}", value);
        }

        public CompositeType GetDataUsingDataContract(CompositeType composite) {
            if (composite == null) {
                throw new ArgumentNullException("composite");
            }
            if (composite.BoolValue) {
                composite.StringValue += "Suffix";
            }
            return composite;
        }
    }

    // Use a data contract as illustrated in the sample below to add composite types to service operations.
    [DataContract]
    public class CompositeType {
        bool boolValue = true;
        string stringValue = "Hello ";

        [DataMember]
        public bool BoolValue {
            get { return boolValue; }
            set { boolValue = value; }
        }

        [DataMember]
        public string StringValue {
            get { return stringValue; }
            set { stringValue = value; }
        }
    }
}
```

And I config it at my Program.cs:
```C#
// Add WCF
builder.Services.AddServiceModelServices();
builder.Services.AddServiceModelMetadata();
builder.Services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();
....
//// WCF
app.UseServiceModel(bld => {
    var basicHttpBindingSecure = new BasicHttpBinding() {
        Security = new BasicHttpSecurity {
            Mode = CoreWCF.Channels.BasicHttpSecurityMode.TransportCredentialOnly,
            Transport = new HttpTransportSecurity() {
                ClientCredentialType = HttpClientCredentialType.InheritedFromHost
            }
        }
    };
    var basicHttpBindingUnsecure = new BasicHttpBinding() {
        Security = new BasicHttpSecurity {
            Mode = CoreWCF.Channels.BasicHttpSecurityMode.Transport,
            Transport = new HttpTransportSecurity() {
                ClientCredentialType = HttpClientCredentialType.None
            }
        }
    };

    bld.AddService<TestService>();
    bld.AddServiceEndpoint<TestService, ITestService>(basicHttpBindingSecure, $"/wcf/{nameof(TestService)}.svc");

    var mb = app.Services.GetRequiredService<ServiceMetadataBehavior>();
    mb.HttpsGetEnabled = true;
});
```

In this scenario, if I debug the solution, I always can't access the WCF service from URL https://localhost/wcf/TestService.svc with `basicHttpBindingSecure` , it always get 404 in response. If I change the binding to `basicHttpBindingUnsecure`, it can be accessed normally. I don't know how to solve it.

**Comment by ctechid** [comment]
Look at example in [here](https://github.com/CoreWCF/samples/tree/main/Basic/Binding/Basic/Http)

**Comment by kamyaw010** [comment]
> Look at example in [here](https://github.com/CoreWCF/samples/tree/main/Basic/Binding/Basic/Http)

I have followed the example and just can use None ClientCredentialType for the service side, if I use any of the ClientCredentialType, it leads to 404

**Comment by ctechid** [comment]
> > Look at example in [here](https://github.com/CoreWCF/samples/tree/main/Basic/Binding/Basic/Http)
> 
> I have followed the example and just can use None ClientCredentialType for the service side, if I use any of the ClientCredentialType, it leads to 404

Look at [here](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/tests/SimpleWSHTTPTest.cs) how to listening and connect with different Credentials

**Comment by kamyaw010** [comment]
> > > Look at example in [here](https://github.com/CoreWCF/samples/tree/main/Basic/Binding/Basic/Http)
> > 
> > 
> > I have followed the example and just can use None ClientCredentialType for the service side, if I use any of the ClientCredentialType, it leads to 404
> 
> Look at [here](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/tests/SimpleWSHTTPTest.cs) how to listening ( **host.Start();** ) and connect ( **ClientHelper.GetBufferedModeWSHttpBinding(xxx)** ) with different Credentials

I'm using with dotnet 6 webapi, I want to support both environment, WCF needs BasicHttpBinding with TransportCredentialOnly and any of ClientCredentialType

**Comment by ctechid** [comment]
Look at [here](https://github.com/CoreWCF/CoreWCF/tree/main/src/CoreWCF.Http/tests). See section **WebSocketsTests.cs**

**Comment by mconnew** [comment]
I think your problem is because you are using TransportCredentialOnly instead of Transport. The difference between them is Transport uses HTTPS and TransportCredentialOnly uses HTTP. WCF/CoreWCF normally won't let you configure things where you are sending credentials without using HTTPS, and the TransportCredentialOnly mode is to override this restriction. We don't have any tests around this so there's probably some bug with the implementation. It was low priority because it's a bad idea from a security perspective.  
If you do actually need the ability to send credentials over an insecure connection (there are a small number of legitimate scenarios) then let me know and we'll consider this a bug needs fixing. I would recommend using security mode Transport and using SSL, especially as asp.net core has easy tooling for generating and trusting a self signed dev certificate.

**Comment by kamyaw010** [comment]
> I think your problem is because you are using TransportCredentialOnly instead of Transport. The difference between them is Transport uses HTTPS and TransportCredentialOnly uses HTTP. WCF/CoreWCF normally won't let you configure things where you are sending credentials without using HTTPS, and the TransportCredentialOnly mode is to override this restriction. We don't have any tests around this so there's probably some bug with the implementation. It was low priority because it's a bad idea from a security perspective. If you do actually need the ability to send credentials over an insecure connection (there are a small number of legitimate scenarios) then let me know and we'll consider this a bug needs fixing. I would recommend using security mode Transport and using SSL, especially as asp.net core has easy tooling for generating and trusting a self signed dev certificate.

Thank you very much, this makes me very clear. I and my team are not professional on WCF so don't exactly know this reason, my team decides to use another solution instead of using CoreWCF now. But I will check the suggestion for further usage, thanks a lot for CoreWCF team.
