### ISSUE TITLE
Every time when there is Post with that there is a Get request getting called

### ISSUE THREAD

**Issue by pritamkumarpanda1** [CoreWCF/CoreWCF#977]
Hello guys,
 I am facing one issue with CoreWCF. I just migrated my project from .Net 4.7 framework to .Net 6 with help of CoreWcf. When calling the service I am getting GET issue every time when there is POST along with in server. Locally when I test through SOAP UI I didn't get any issue but in server it does. I want to stop the GET call as every time it is automatically getting called. Tried with WebInvoke in Operation Contract and making changes in "serviceMetadataBehavior.HttpGetEnabled" but nothing worked. I have attached the app-insights of the request. Any suggestions please ? 

![get](https://user-images.githubusercontent.com/23519276/211568930-db463564-4211-45c9-8475-e13b28802aa4.PNG)

**Comment by mconnew** [comment]
This is a client issue and not a problem with CoreWCF. I presume you are using the .NET Core WCF client packages. Can you open the issue over there. https://github.com/dotnet/wcf

**Comment by pritamkumarpanda1** [comment]
https://github.com/dotnet/wcf/issues/4989 -  Opened a ticket here.
