### ISSUE TITLE
Update release notes for dotnet-svcutil 

### ISSUE THREAD

**Issue by kapsiR** [CoreWCF/CoreWCF#980]
The [dotnet-svcutil - Release Notes](https://github.com/dotnet/wcf/blob/main/release-notes/dotnet-svcutil-notes.md) do not mention versions > `2.0.1`

In the meantime [`v2.1.0` has been released](https://www.nuget.org/packages/dotnet-svcutil/2.1.0), what has actually changed? (framework support changed?)

Thanks 🙏

**Comment by mconnew** [comment]
This is the wrong repo. The correct repo is https://github.com/dotnet/wcf  
Can you open an issue over there and @HongGit will take a look.

**Comment by kapsiR** [comment]
Thanks for guiding me to the correct repo!
