### ISSUE TITLE
Add BasicHttpsBinding Support

### ISSUE THREAD

**Issue by JarredOddes** [CoreWCF/CoreWCF#994]
Hi,

I wanted to check if there are any plans to add BasicHttpsBinding support. I have a few old services that use BasicHttpsBinding and believe it would be a useful addition to this package.

I have done some of the work already for my own use and I would be happy to create a pull request.

**Comment by gstvudia** [comment]
> Hi,
> 
> I wanted to check if there are any plans to add BasicHttpsBinding support. I have a few old services that use BasicHttpsBinding and believe it would be a useful addition to this package.
> 
> I have done some of the work already for my own use and I would be happy to create a pull request.

Hi Jarred,

Could you please share with me? I'm on the same situation trying to migrate a service that uses **BasicHttpsBinding**

**Comment by JarredOddes** [comment]
> Hi Jarred,
> 
> Could you please share with me? I'm on the same situation trying to migrate a service that uses **BasicHttpsBinding**

Hi @gstvudia,

I created a fork with my changes. if you would like to use it you will have to build the solution and use the DLLs directly.
https://github.com/JarredOddes/CoreWCF

**Comment by mconnew** [comment]
BasicHttpBinding and BasicHttpsBinding are functionally equivalent when you pass the security mode of Transport to the constructor. BasicHttpsBinding just has that set by default. The distinction between these two was more important in WCF as we set up the HTTP/HTTPS listener and configured it, but in CoreWCF you do this by configuring asp.net core yourself and we just validate the request is using HTTPS if you specify transport security. You should be able to use BasicHttpBinding to set up an equivalent service. Please let me know if there's something you need from that binding that I missed.

**Comment by JarredOddes** [comment]
Hi @mconnew, Thanks for the clarification. The request was more for easier backward compatibility with client-side connections to connect to updated endpoints without a need to change anything on their side. However, I have done some testing with legacy connections and have not run into any issues when using BasicHttpBinding with the security mode of Transport on legacy systems.
