### ISSUE TITLE
 FaultExceptions thrown from UserNamePasswordValidators do not get serialised when using BasicHttpBinding

### ISSUE THREAD

**Issue by marlon-tucker** [CoreWCF/CoreWCF#995]
Hello,

Last year I submitted #676, I've just upgraded our CoreWCF references to bring in the change, but unfortunately in my case it is still present, at least for BasicHttpBindings. The unit test which the PR for was validated against covered WSHttpBidnings.

The root cause is the `TransportSecurityBindingElement.BuildServiceDispatcherCore` builds a `SecurityServiceDispatcher` and does not set `SendUnsecuredFaults` to true. 

This causes error responses to get lost, and the underlying connection is unexpectedly aborted for the client.

The `SecurityServiceDispatcher` is marked as internal and I can't see an obvious way to programmatically set the desired property to true.

In the mean time I'm going to have to revert back and continue using my exception catching middleware which "fakes" a correct WCF error response.

**Comment by McLea** [comment]
I'm currently trying to port a legacy WCF app to CoreWCF and reproducing this issue myself.
I'm stuck using the existing BasicHttpBinding but unfortunately can't get the FaultException back and the connection is interrupted.

**Comment by dtriana** [comment]
@marlon-tucker is this workaround you mention in your last paragraph publicly available or something that you can share? Looks like I will need to do the same while this issue is addressed, thanks!

**Comment by g7ed6e** [comment]
@marlon-tucker i investigated this and found that SendUnsecuredFaults is true which results in client side code receiving a MessageSecurityException.
@dtriana Can you confirm the unit test in #1162 reproduces your configuration.

**Comment by marlon-tucker** [comment]
Hello, looking through the code changes, it looks like this commit https://github.com/CoreWCF/CoreWCF/commit/8aad8508d82a65bc6ca79178943321fa9bf70f24 changed the default for the `SendUnsecuredFaults` property to true.

So yes I think this issue should now be resolved.

**Comment by dtriana** [comment]
@g7ed6e With the build released today, 1.5.0-alpha.18, I'm finally getting the SOAP error response for authentication errors in my migrated application, thank you so much!
